// Keyword, entity and internal-link map for every service and industry page.
// This is the single source of truth for: the contextual "Explore related topics" links on each page,
// the `isRelatedTo` links in Service schema, the audit in Admin > SEO audit, and the semantic network view.
//
//   kw   primary keyword the page should rank for (and be quoted for in AI answers)
//   sec  secondary / LSI keywords that should appear naturally in the copy
//   ent  entities the page should clearly mention (platforms, standards, concepts) for AEO and GEO
//   to   semantic links: [target, anchor text, why it helps the reader]. Targets are a service slug, `i:industry-slug` or a path.

export type Link = [target: string, anchor: string, why: string];
export type Entry = { kw: string; sec: string[]; ent: string[]; to: Link[] };

export const seoMap: Record<string, Entry> = {
  // ---- categories --------------------------------------------------------------------------------
  'digital-marketing': { kw: 'digital marketing services uk', sec: ['digital marketing agency', 'SEO and PPC', 'online marketing', 'lead generation', 'marketing ROI'], ent: ['Google', 'Meta', 'GA4', 'Google Business Profile'],
    to: [['search-engine-optimization', 'SEO, AEO and GEO services', 'Rank on Google and in AI answers'], ['google-ads', 'Google Ads management', 'Paid search for fast leads'], ['content-marketing', 'content marketing', 'Content that earns links and trust'], ['reputation-management', 'online reputation management', 'Reviews that convert'], ['i:e-commerce', 'ecommerce marketing', 'Growth for online stores']] },
  'social-media-marketing': { kw: 'social media marketing services uk', sec: ['social media agency', 'paid social', 'community management', 'social media advertising', 'content creation'], ent: ['Facebook', 'Instagram', 'LinkedIn', 'TikTok', 'Pinterest'],
    to: [['facebook-marketing', 'Facebook marketing', 'Ads and page growth'], ['instagram-marketing', 'Instagram marketing', 'Reels, stories and shopping'], ['linkedin-marketing', 'LinkedIn marketing for B2B', 'Reach decision makers'], ['paid-media', 'paid media management', 'Scale what works'], ['content-marketing', 'content marketing', 'Fuel your social channels']] },
  'web-design-development': { kw: 'web design and development services uk', sec: ['website design agency', 'website development', 'responsive web design', 'WordPress development', 'ecommerce website'], ent: ['WordPress', 'Shopify', 'Laravel', 'Core Web Vitals'],
    to: [['website-design', 'website design', 'UX and UI that converts'], ['wordpress-development', 'WordPress development', 'Flexible, fast sites'], ['ecommerce-development', 'ecommerce development', 'Stores that sell'], ['website-maintenance', 'website maintenance', 'Keep your site fast and secure'], ['conversion-rate-optimization', 'conversion rate optimisation', 'Turn visits into leads']] },
  'custom-software-development': { kw: 'custom software development company uk', sec: ['bespoke software', 'web application development', 'mobile app development', 'CRM development', 'business automation'], ent: ['API', 'SaaS', 'Laravel', 'React', 'AWS'],
    to: [['web-application-development', 'web application development', 'Portals and dashboards'], ['mobile-app-development', 'mobile app development', 'iOS and Android apps'], ['crm-erp-development', 'custom CRM and ERP', 'Systems around your process'], ['api-system-integration', 'API and system integration', 'Connect your tools'], ['mvp-development', 'MVP development', 'Launch and validate fast']] },
  'branding-strategy': { kw: 'branding and strategy agency uk', sec: ['brand identity', 'brand strategy', 'marketing advisory', 'conversion rate optimisation', 'brand guidelines'], ent: ['brand identity', 'positioning', 'CRO'],
    to: [['branding', 'brand identity design', 'A brand that stands out'], ['marketing-advisory', 'marketing advisory', 'A clear 12-month plan'], ['conversion-rate-optimization', 'conversion rate optimisation', 'More from your traffic'], ['website-design', 'website design', 'Bring the brand to life online']] },

  // ---- digital marketing -------------------------------------------------------------------------
  'search-engine-optimization': { kw: 'seo services uk', sec: ['seo agency', 'technical seo', 'on-page seo', 'link building', 'AEO', 'GEO', 'AI search optimisation'], ent: ['Google', 'AI Overviews', 'ChatGPT', 'Core Web Vitals', 'schema markup', 'E-E-A-T'],
    to: [['local-seo', 'local SEO services', 'Win the Google map pack'], ['ecommerce-seo', 'ecommerce SEO', 'Category and product rankings'], ['seo-backlinks', 'link building services', 'Authority from quality links'], ['content-marketing', 'SEO content marketing', 'Content that ranks and gets cited'], ['website-maintenance', 'technical website maintenance', 'Speed and security for rankings'], ['i:e-commerce', 'SEO for ecommerce businesses', 'See results in your sector']] },
  'local-seo': { kw: 'local seo services uk', sec: ['google business profile optimisation', 'map pack rankings', 'local citations', 'near me searches', 'google reviews'], ent: ['Google Maps', 'Google Business Profile', 'NAP', 'local pack'],
    to: [['search-engine-optimization', 'full SEO services', 'Beyond local rankings'], ['reputation-management', 'review management', 'More 5-star Google reviews'], ['seo-backlinks', 'local link building', 'Local authority signals'], ['i:healthcare', 'healthcare marketing', 'Local SEO for clinics'], ['i:real-estate', 'property marketing', 'Local SEO for agents']] },
  'ecommerce-seo': { kw: 'ecommerce seo services uk', sec: ['product page seo', 'category page seo', 'google shopping', 'technical seo for ecommerce', 'organic revenue'], ent: ['Shopify', 'WooCommerce', 'Google Merchant Center', 'product schema'],
    to: [['search-engine-optimization', 'SEO services', 'The wider SEO programme'], ['ecommerce-development', 'ecommerce development', 'Build for search and speed'], ['google-ads', 'Google Shopping ads', 'Paid + organic together'], ['conversion-rate-optimization', 'conversion rate optimisation', 'Convert the traffic you earn'], ['i:e-commerce', 'ecommerce marketing', 'Full-funnel store growth']] },
  'google-ads': { kw: 'google ads management uk', sec: ['ppc agency', 'performance max', 'google shopping ads', 'search ads', 'conversion tracking', 'ROAS'], ent: ['Google Ads', 'Performance Max', 'GA4', 'Google Merchant Center'],
    to: [['paid-media', 'paid media management', 'Beyond Google'], ['digital-advertising', 'digital advertising', 'Multi-channel campaigns'], ['conversion-rate-optimization', 'conversion rate optimisation', 'Lower cost per lead'], ['search-engine-optimization', 'SEO services', 'Organic + paid synergy'], ['i:finance', 'financial services marketing', 'Compliant PPC']] },
  'reputation-management': { kw: 'online reputation management uk', sec: ['review management', 'google reviews', 'brand reputation', 'trustpilot', 'reputation repair'], ent: ['Google Reviews', 'Trustpilot', 'brand SERP', 'AI search reputation'],
    to: [['local-seo', 'local SEO', 'Reviews drive map rankings'], ['search-engine-optimization', 'SEO and GEO', 'Own your brand results'], ['content-marketing', 'content marketing', 'Publish proof and thought leadership'], ['i:healthcare', 'healthcare marketing', 'Patient trust'], ['i:hospitality-hotels', 'hospitality marketing', 'Guest reviews']] },
  'content-marketing': { kw: 'content marketing services uk', sec: ['seo content writing', 'blog writing', 'content strategy', 'topic clusters', 'video content'], ent: ['topic clusters', 'E-E-A-T', 'pillar pages', 'featured snippets'],
    to: [['search-engine-optimization', 'SEO services', 'Strategy and technical foundation'], ['seo-backlinks', 'link building', 'Promote your best content'], ['social-media-marketing', 'social media marketing', 'Distribute content'], ['website-design', 'website design', 'Present content beautifully'], ['/blogs', 'GTech Digital blog', 'Guides from our team']] },
  'seo-backlinks': { kw: 'link building services uk', sec: ['seo backlinks', 'digital pr', 'guest posting', 'backlink audit', 'domain authority'], ent: ['Domain Rating', 'digital PR', 'anchor text', 'Google Search Essentials'],
    to: [['search-engine-optimization', 'SEO services', 'Links within a full strategy'], ['content-marketing', 'content marketing', 'Link-worthy assets'], ['local-seo', 'local citations', 'Local link signals'], ['reputation-management', 'reputation management', 'Brand mentions and reviews']] },
  'digital-advertising': { kw: 'digital advertising agency uk', sec: ['display advertising', 'retargeting', 'video advertising', 'programmatic', 'ad creative'], ent: ['Google Display Network', 'YouTube', 'Meta Ads', 'retargeting'],
    to: [['google-ads', 'Google Ads management', 'High-intent search'], ['paid-media', 'paid media', 'Cross-channel budgets'], ['facebook-marketing', 'Facebook advertising', 'Social reach'], ['conversion-rate-optimization', 'conversion rate optimisation', 'Better landing pages']] },
  'paid-media': { kw: 'paid media management agency uk', sec: ['paid social', 'ppc management', 'media buying', 'attribution', 'budget allocation'], ent: ['Google Ads', 'Meta Ads', 'TikTok Ads', 'LinkedIn Ads', 'GA4'],
    to: [['google-ads', 'Google Ads', 'Search and Shopping'], ['facebook-marketing', 'Facebook ads', 'Meta campaigns'], ['tiktok-marketing', 'TikTok advertising', 'Reach younger audiences'], ['linkedin-marketing', 'LinkedIn ads', 'B2B targeting'], ['marketing-advisory', 'marketing advisory', 'Budget planning']] },

  // ---- social ------------------------------------------------------------------------------------
  'facebook-marketing': { kw: 'facebook marketing services uk', sec: ['facebook ads', 'facebook page management', 'meta ads', 'lead generation ads', 'community management'], ent: ['Meta', 'Facebook Ads Manager', 'Meta Pixel', 'Conversions API'],
    to: [['instagram-marketing', 'Instagram marketing', 'Run Meta channels together'], ['paid-media', 'paid media', 'Scale spend profitably'], ['social-media-marketing', 'social media marketing', 'The wider social plan'], ['i:e-commerce', 'ecommerce marketing', 'Catalogue ads']] },
  'instagram-marketing': { kw: 'instagram marketing services uk', sec: ['instagram ads', 'reels', 'influencer marketing', 'instagram shopping', 'content creation'], ent: ['Instagram Reels', 'Instagram Shopping', 'Meta', 'UGC'],
    to: [['facebook-marketing', 'Facebook marketing', 'Shared Meta ad account'], ['tiktok-marketing', 'TikTok marketing', 'Short-form video'], ['content-marketing', 'content marketing', 'Creative that performs'], ['i:hospitality-hotels', 'hospitality marketing', 'Visual venues']] },
  'linkedin-marketing': { kw: 'linkedin marketing agency uk', sec: ['linkedin ads', 'b2b lead generation', 'thought leadership', 'employee advocacy', 'account based marketing'], ent: ['LinkedIn Ads', 'Lead Gen Forms', 'ABM', 'HubSpot'],
    to: [['i:b2b-marketing', 'B2B marketing', 'The full B2B programme'], ['content-marketing', 'thought leadership content', 'Authority content'], ['paid-media', 'paid media', 'Budget across channels'], ['crm-erp-development', 'CRM development', 'Track leads to revenue']] },
  'tiktok-marketing': { kw: 'tiktok marketing agency uk', sec: ['tiktok ads', 'spark ads', 'tiktok shop', 'creator marketing', 'short form video'], ent: ['TikTok Shop', 'Spark Ads', 'TikTok Pixel', 'UGC'],
    to: [['instagram-marketing', 'Instagram marketing', 'Repurpose Reels'], ['paid-media', 'paid media', 'Test and scale ads'], ['i:e-commerce', 'ecommerce marketing', 'Social commerce'], ['i:travel', 'travel marketing', 'Destination inspiration']] },
  'pinterest-marketing': { kw: 'pinterest marketing services uk', sec: ['pinterest ads', 'pinterest seo', 'pin design', 'shopping pins', 'visual search'], ent: ['Pinterest Ads', 'Rich Pins', 'Pinterest Tag', 'visual discovery'],
    to: [['ecommerce-seo', 'ecommerce SEO', 'Search and discovery together'], ['content-marketing', 'content marketing', 'Evergreen pins'], ['i:travel', 'travel marketing', 'Trip inspiration'], ['i:e-commerce', 'ecommerce marketing', 'Product discovery']] },

  // ---- web ---------------------------------------------------------------------------------------
  'website-design': { kw: 'website design services uk', sec: ['web design agency', 'ux design', 'ui design', 'responsive design', 'conversion focused design'], ent: ['UX', 'WCAG', 'Figma', 'design system'],
    to: [['web-design-development', 'web design and development', 'Design plus build'], ['conversion-rate-optimization', 'conversion rate optimisation', 'Test and improve designs'], ['branding', 'brand identity', 'Consistent visual identity'], ['wordpress-development', 'WordPress development', 'Build it on WordPress'], ['search-engine-optimization', 'SEO', 'Design for search']] },
  'wordpress-development': { kw: 'wordpress development services uk', sec: ['custom wordpress theme', 'woocommerce', 'gutenberg blocks', 'wordpress speed', 'wordpress security'], ent: ['WordPress', 'WooCommerce', 'Gutenberg', 'PHP'],
    to: [['website-maintenance', 'WordPress maintenance', 'Updates, backups, security'], ['php-development', 'PHP development', 'Custom back-end work'], ['cms-development', 'CMS development', 'Other CMS options'], ['ecommerce-development', 'ecommerce development', 'WooCommerce and Shopify']] },
  'php-development': { kw: 'php development company uk', sec: ['custom php applications', 'php api development', 'legacy php upgrade', 'php 8', 'web applications'], ent: ['PHP 8', 'Laravel', 'REST API', 'MySQL'],
    to: [['laravel-development', 'Laravel development', 'Modern PHP framework'], ['wordpress-development', 'WordPress development', 'PHP-powered CMS'], ['api-system-integration', 'API integration', 'Connect systems'], ['web-application-development', 'web application development', 'Bespoke web apps']] },
  'cms-development': { kw: 'cms development services uk', sec: ['headless cms', 'custom cms', 'content management system', 'cms migration', 'editorial workflows'], ent: ['headless CMS', 'WordPress', 'Contentful', 'structured content'],
    to: [['wordpress-development', 'WordPress development', 'The most popular CMS'], ['web-design-development', 'web design and development', 'Full site builds'], ['website-maintenance', 'website maintenance', 'Keep it updated'], ['search-engine-optimization', 'SEO migration support', 'Protect rankings']] },
  'laravel-development': { kw: 'laravel development company uk', sec: ['laravel web application', 'laravel api', 'admin panels', 'laravel devops', 'php framework'], ent: ['Laravel', 'PHP', 'Vue', 'MySQL', 'REST API'],
    to: [['php-development', 'PHP development', 'The wider PHP stack'], ['web-application-development', 'web application development', 'Portals and dashboards'], ['saas-product-development', 'SaaS product development', 'Subscription products'], ['api-system-integration', 'API development', 'Integrations']] },
  'website-maintenance': { kw: 'website maintenance services uk', sec: ['website support', 'wordpress maintenance', 'website security', 'uptime monitoring', 'website backups'], ent: ['uptime monitoring', 'backups', 'SSL', 'Core Web Vitals'],
    to: [['wordpress-development', 'WordPress development', 'Improve while you maintain'], ['search-engine-optimization', 'technical SEO', 'Speed and crawlability'], ['web-design-development', 'web design and development', 'Redesigns and rebuilds']] },
  'ecommerce-development': { kw: 'ecommerce development services uk', sec: ['ecommerce website development', 'shopify development', 'woocommerce development', 'checkout optimisation', 'payment integration', 'online store design'], ent: ['Shopify', 'WooCommerce', 'Stripe', 'PayPal'],
    to: [['ecommerce-seo', 'ecommerce SEO', 'Get found'], ['conversion-rate-optimization', 'conversion rate optimisation', 'Lift checkout conversion'], ['api-system-integration', 'system integration', 'Stock, courier and accounts'], ['i:e-commerce', 'ecommerce marketing', 'Drive store traffic']] },

  // ---- software ----------------------------------------------------------------------------------
  'web-application-development': { kw: 'web application development company uk', sec: ['custom web app', 'customer portal', 'dashboard development', 'saas', 'progressive web app'], ent: ['React', 'Next.js', 'Laravel', 'Node.js', 'API'],
    to: [['laravel-development', 'Laravel development', 'Our back-end stack'], ['api-system-integration', 'API integration', 'Connect third-party services'], ['saas-product-development', 'SaaS development', 'Subscription products'], ['crm-erp-development', 'CRM and ERP development', 'Internal systems']] },
  'mobile-app-development': { kw: 'mobile app development company uk', sec: ['ios app development', 'android app development', 'cross platform apps', 'app store launch', 'app ux design'], ent: ['iOS', 'Android', 'Flutter', 'React Native', 'App Store'],
    to: [['mvp-development', 'MVP development', 'Validate before you scale'], ['api-system-integration', 'API development', 'Power your app'], ['web-application-development', 'web applications', 'Web companion'], ['i:technology-saas', 'SaaS marketing', 'Grow your app']] },
  'api-system-integration': { kw: 'api and system integration services uk', sec: ['api integration', 'system integration', 'workflow automation', 'data sync', 'custom api', 'third party integration'], ent: ['REST API', 'webhooks', 'Zapier', 'Xero', 'HubSpot'],
    to: [['crm-erp-development', 'CRM and ERP development', 'Systems to connect'], ['web-application-development', 'web applications', 'Apps that use your data'], ['ecommerce-development', 'ecommerce development', 'Shop integrations'], ['custom-software-development', 'custom software', 'Bespoke builds']] },
  'crm-erp-development': { kw: 'custom crm and erp development uk', sec: ['custom crm development', 'erp software', 'business automation', 'sales pipeline software', 'workflow automation', 'data migration'], ent: ['CRM', 'ERP', 'HubSpot', 'Salesforce'],
    to: [['api-system-integration', 'API integration', 'Connect your tools'], ['custom-software-development', 'custom software development', 'The wider software service'], ['web-application-development', 'web applications', 'Portals for staff and clients'], ['i:b2b-marketing', 'B2B marketing', 'Close the loop on leads']] },
  'saas-product-development': { kw: 'saas development company uk', sec: ['saas product development', 'multi tenant architecture', 'subscription billing', 'saas onboarding', 'saas scalability'], ent: ['SaaS', 'Stripe', 'multi-tenancy', 'AWS'],
    to: [['mvp-development', 'MVP development', 'Start lean'], ['laravel-development', 'Laravel development', 'Our SaaS stack'], ['i:technology-saas', 'SaaS marketing', 'Acquire customers'], ['web-application-development', 'web application development', 'Front-end apps']] },
  'mvp-development': { kw: 'mvp development company uk', sec: ['minimum viable product', 'startup app development', 'product validation', 'rapid prototyping', 'mvp launch'], ent: ['MVP', 'prototype', 'product-market fit', 'user testing'],
    to: [['saas-product-development', 'SaaS product development', 'Scale after validation'], ['mobile-app-development', 'mobile app development', 'App MVPs'], ['marketing-advisory', 'marketing advisory', 'Plan the launch'], ['i:technology-saas', 'SaaS marketing', 'First customers']] },

  // ---- branding ----------------------------------------------------------------------------------
  'branding': { kw: 'branding agency uk', sec: ['brand identity design', 'logo design', 'brand guidelines', 'brand strategy', 'rebranding'], ent: ['brand identity', 'logo', 'tone of voice', 'brand guidelines'],
    to: [['branding-strategy', 'branding and strategy services', 'Identity plus a growth plan'], ['website-design', 'website design', 'Apply your brand online'], ['marketing-advisory', 'marketing advisory', 'Position and plan'], ['content-marketing', 'content marketing', 'Voice in action'], ['social-media-marketing', 'social media marketing', 'Brand on social']] },
  'marketing-advisory': { kw: 'marketing consultancy uk', sec: ['marketing strategy', 'fractional cmo', 'growth plan', 'marketing budget', 'marketing kpis'], ent: ['fractional CMO', 'marketing KPIs', 'growth plan', 'GA4'],
    to: [['branding-strategy', 'branding and strategy', 'Brand foundations for the plan'], ['digital-marketing', 'digital marketing services', 'Execute the plan'], ['conversion-rate-optimization', 'conversion rate optimisation', 'Quick wins'], ['paid-media', 'paid media', 'Budget allocation'], ['branding', 'branding', 'Positioning']] },
  'conversion-rate-optimization': { kw: 'conversion rate optimisation agency uk', sec: ['cro services', 'a/b testing', 'landing page optimisation', 'user research', 'funnel analysis'], ent: ['A/B testing', 'heatmaps', 'GA4', 'Core Web Vitals'],
    to: [['website-design', 'website design', 'Redesign what the data says'], ['google-ads', 'Google Ads', 'Lower cost per lead'], ['ecommerce-development', 'ecommerce development', 'Checkout improvements'], ['i:e-commerce', 'ecommerce marketing', 'Store conversion']] },

  // ---- industries --------------------------------------------------------------------------------
  'e-commerce': { kw: 'ecommerce marketing agency uk', sec: ['ecommerce seo', 'google shopping', 'email marketing', 'conversion optimisation', 'roas'], ent: ['Shopify', 'Google Shopping', 'Klaviyo', 'Meta Catalogue Ads'],
    to: [['ecommerce-seo', 'ecommerce SEO', 'Organic revenue'], ['google-ads', 'Google Shopping ads', 'Paid revenue'], ['ecommerce-development', 'ecommerce development', 'Better stores'], ['conversion-rate-optimization', 'conversion optimisation', 'More orders'], ['facebook-marketing', 'Meta ads', 'Catalogue campaigns']] },
  'education': { kw: 'education marketing agency uk', sec: ['student recruitment marketing', 'university marketing', 'school marketing', 'course seo', 'open day campaigns'], ent: ['UCAS', 'WCAG', 'TikTok', 'prospectus'],
    to: [['search-engine-optimization', 'course SEO', 'Rank for courses'], ['social-media-marketing', 'student social media', 'Reach students'], ['website-design', 'accessible website design', 'WCAG 2.2'], ['google-ads', 'Google Ads', 'Clearing and intake']] },
  'b2b-marketing': { kw: 'b2b marketing agency uk', sec: ['b2b lead generation', 'account based marketing', 'linkedin ads', 'demand generation', 'marketing pipeline'], ent: ['LinkedIn', 'ABM', 'HubSpot', 'Salesforce'],
    to: [['linkedin-marketing', 'LinkedIn marketing', 'Reach buyers'], ['search-engine-optimization', 'B2B SEO', 'Capture research'], ['content-marketing', 'B2B content', 'Nurture buyers'], ['crm-erp-development', 'CRM development', 'Closed-loop reporting']] },
  'automotive': { kw: 'automotive marketing agency uk', sec: ['car dealer marketing', 'garage marketing', 'vehicle ads', 'dealer website', 'test drive bookings'], ent: ['Google Vehicle Ads', 'AutoTrader', 'FCA', 'Meta Automotive'],
    to: [['local-seo', 'dealer local SEO', 'Maps visibility'], ['google-ads', 'Google Ads', 'Stock-led search'], ['website-design', 'dealer website design', 'Online showroom'], ['reputation-management', 'review management', 'Dealer reviews']] },
  'healthcare': { kw: 'healthcare marketing agency uk', sec: ['dental marketing', 'clinic marketing', 'patient acquisition', 'private healthcare seo', 'online booking'], ent: ['CQC', 'GMC', 'ASA', 'GDPR', 'Google Business Profile'],
    to: [['local-seo', 'clinic local SEO', 'Be found locally'], ['reputation-management', 'patient reviews', 'Trust signals'], ['google-ads', 'Google Ads', 'Treatment searches'], ['website-design', 'clinic website design', 'Easy booking']] },
  'hospitality-hotels': { kw: 'hospitality marketing agency uk', sec: ['hotel marketing', 'restaurant marketing', 'direct bookings', 'venue marketing', 'tripadvisor'], ent: ['Google Hotel Ads', 'TripAdvisor', 'OTA', 'booking engine'],
    to: [['local-seo', 'restaurant local SEO', 'Map visibility'], ['instagram-marketing', 'Instagram marketing', 'Visual venues'], ['reputation-management', 'review management', 'Guest reviews'], ['website-design', 'hotel website design', 'Direct booking engine']] },
  'travel': { kw: 'travel marketing agency uk', sec: ['tour operator marketing', 'travel seo', 'destination marketing', 'holiday bookings', 'travel agent marketing'], ent: ['ATOL', 'ABTA', 'Pinterest', 'YouTube'],
    to: [['search-engine-optimization', 'travel SEO', 'Destination rankings'], ['pinterest-marketing', 'Pinterest marketing', 'Trip inspiration'], ['google-ads', 'Google Ads', 'Booking windows'], ['content-marketing', 'travel content', 'Guides that rank']] },
  'real-estate': { kw: 'property marketing agency uk', sec: ['estate agent marketing', 'property marketing', 'letting agent marketing', 'valuation leads', 'area guides', 'property portals'], ent: ['Rightmove', 'Zoopla', 'Google Maps', 'valuation'],
    to: [['local-seo', 'estate agent local SEO', 'Branch rankings'], ['google-ads', 'Google Ads', 'Valuation leads'], ['website-design', 'estate agent websites', 'Instant valuation tools'], ['facebook-marketing', 'Facebook ads', 'Landlord campaigns']] },
  'finance': { kw: 'financial marketing agency uk', sec: ['financial services marketing', 'financial adviser marketing', 'mortgage broker marketing', 'accountant marketing', 'fca compliant marketing', 'consumer duty'], ent: ['FCA', 'Consumer Duty', 'financial promotions', 'Trustpilot'],
    to: [['search-engine-optimization', 'financial SEO', 'Authority content'], ['google-ads', 'Google Ads', 'Compliant PPC'], ['linkedin-marketing', 'LinkedIn marketing', 'B2B finance'], ['reputation-management', 'reputation management', 'Trust']] },
  'technology-saas': { kw: 'saas marketing agency uk', sec: ['b2b saas marketing', 'trial to paid', 'product led growth', 'comparison pages', 'ai search visibility'], ent: ['SaaS', 'G2', 'Capterra', 'ChatGPT', 'MRR'],
    to: [['search-engine-optimization', 'SaaS SEO', 'Comparison and alternative pages'], ['saas-product-development', 'SaaS development', 'Build the product'], ['linkedin-marketing', 'LinkedIn marketing', 'Reach buyers'], ['conversion-rate-optimization', 'conversion optimisation', 'Trial conversion']] },
};
