import type { ServiceContent } from '../types';

// Entity map: API and system integration -> REST and GraphQL APIs, webhooks, OpenAPI documentation,
// OAuth 2, middleware and integration hubs, iPaaS (Zapier, Make), ETL and data sync, ERP, CRM
// (Salesforce, HubSpot), accounting (Xero, QuickBooks), ecommerce (Shopify), payments (Stripe),
// legacy systems (SOAP, CSV, SFTP), queues and retries, monitoring, rate limits, single source of truth.

const content: ServiceContent = {
  slug: 'api-system-integration',
  short: 'API & System Integration',
  metaTitle: 'API & System Integration Services UK | GTech Digital',
  metaDescription:
    'UK API and system integration company connecting CRM, accounting, ecommerce, ERP and legacy systems so data flows automatically and accurately.',
  hero: {
    keyword: 'API and System Integration',
    title: 'API Integration That',
    highlight: 'Connects Your Systems',
    lead:
      'GTech Digital provides API and system integration services in the UK, connecting CRM, accounting, ecommerce and ERP systems so data flows automatically, accurately and securely, without manual entry or copying between spreadsheets.',
    motion: '/services/api.webp',
    points: ['Free integration review', 'Secure, documented APIs', 'Monitored around the clock'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-system-integration',
      nav: 'What is it',
      heading: 'What Is API and System Integration and How Does It Work?',
      paras: [
        'An API lets two pieces of software talk to each other. System integration uses APIs to connect your tools, such as CRM, accounting, ecommerce and warehouse systems, so they share data in real time instead of relying on manual re-typing and spreadsheets.',
      ],
      bullets: [
        'API development: secure APIs for your apps, partners and customers',
        'Integration: connecting off-the-shelf and in-house systems',
        'Automation: workflows triggered by events across your tools',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'API & System Integration Results and Key Statistics',
      text: 'The numbers behind the integrations we build and monitor.',
      stats: [
        { value: '1.2M', label: 'Records synced every month' },
        { value: '-94%', label: 'Average reduction in data errors' },
        { value: '99.9%', label: 'Sync success rate' },
        { value: '150+', label: 'Integrations built' },
      ],
    },
    {
      type: 'media',
      id: 'integrations',
      nav: 'Integrations',
      heading: 'CRM, Accounting and Ecommerce System Integration',
      image: '/pages/api/network.webp',
      alt: 'Integration hub connecting Salesforce, Xero, Shopify, ERP, Stripe and Slack',
      paras: ['We connect the systems you already rely on, so customers, orders, stock and invoices stay in sync everywhere.'],
      bullets: ['CRM: Salesforce, HubSpot, Dynamics', 'Accounts: Xero, QuickBooks, Sage', 'Commerce: Shopify, WooCommerce, Stripe', 'Operations: ERP, WMS and couriers'],
    },
    {
      type: 'media',
      id: 'api-development',
      nav: 'API development',
      heading: 'Custom API Development: REST, Webhooks and Third-Party APIs',
      image: '/pages/api/code.webp',
      alt: 'API code with fast median response, OAuth 2 security and OpenAPI documentation',
      flip: true,
      tone: 'grey',
      paras: ['We build fast, secure and well-documented APIs that your apps, partners and customers can rely on.'],
      bullets: ['REST and GraphQL APIs', 'OAuth 2 and API keys', 'OpenAPI documentation', 'Versioning and rate limiting'],
    },
    {
      type: 'media',
      id: 'automation',
      nav: 'Automation',
      heading: 'Workflow Automation and Real-Time Data Sync',
      image: '/pages/api/sync.webp',
      alt: 'Manual data entry hours falling from 96 to 4 with real-time sync and fewer errors',
      paras: ['When an order, lead or invoice is created, the right systems update instantly and the right people are notified.'],
      bullets: ['Real-time webhooks', 'Scheduled data sync', 'Event-driven workflows', 'Zapier and Make where they fit'],
    },
    {
      type: 'media',
      id: 'reliability',
      nav: 'Reliability',
      heading: 'Integration Monitoring, Error Alerts and Legacy System Connectors',
      image: '/pages/api/monitor.webp',
      alt: 'Integration reliability checklist with retries, rate limits, alerts, encryption and audit logs',
      flip: true,
      tone: 'grey',
      paras: ['Every integration is monitored, with automatic retries and alerts, and we can connect older systems using files, SFTP or SOAP.'],
      bullets: ['Retries and error queues', 'Alerts on failed syncs', 'Legacy SOAP, CSV and SFTP', 'Encrypted credentials and logs'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our API & System Integration Services',
      cards: [
        { icon: 'lucide:search', title: 'Systems Review', text: 'Data flows mapped.' },
        { icon: 'lucide:webhook', title: 'API Development', text: 'REST and GraphQL APIs.' },
        { icon: 'lucide:workflow', title: 'Integrations', text: 'Your tools connected.' },
        { icon: 'lucide:refresh-cw', title: 'Data Sync', text: 'Real-time or scheduled.' },
        { icon: 'lucide:database', title: 'Data Migration', text: 'Clean, mapped and moved.' },
        { icon: 'lucide:shield-check', title: 'Security', text: 'OAuth, encryption and logs.' },
        { icon: 'lucide:book-open', title: 'Documentation', text: 'OpenAPI specs and guides.' },
        { icon: 'lucide:activity', title: 'Monitoring', text: 'Alerts and support.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our API & System Integration Process, Step by Step',
      steps: [
        { title: 'Map', text: 'Systems and data flows.' },
        { title: 'Design', text: 'Fields, rules and errors.' },
        { title: 'Build', text: 'APIs and connectors.' },
        { title: 'Test', text: 'With real sample data.' },
        { title: 'Launch', text: 'Phased switch-over.' },
        { title: 'Monitor', text: 'Alerts and improvements.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'API & System Integration Case Studies and Results',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Custom vs Zapier',
      heading: 'Custom Integration vs Zapier or Make',
      columns: ['', 'Custom integration', 'Zapier or Make'],
      rows: [
        ['Best for', 'High volume and complex logic', 'Simple, low-volume tasks'],
        ['Running cost', 'Hosting only', 'Rises with every task'],
        ['Error handling', 'Retries, queues and alerts', 'Basic'],
        ['Legacy systems', 'Yes, including files and SOAP', 'Limited'],
      ],
      note: 'We often use both: no-code tools for quick wins and custom code where reliability matters.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does System Integration Cost?',
      intro: 'UK integration projects typically range from about £3,000 for a single connection to £40,000+ for an integration platform. Your quote depends on:',
      cards: [
        { icon: 'lucide:workflow', title: 'Systems', text: 'Number to connect.' },
        { icon: 'lucide:layers', title: 'Data volume', text: 'Records and frequency.' },
        { icon: 'lucide:file-code', title: 'API quality', text: 'Modern or legacy systems.' },
        { icon: 'lucide:git-branch', title: 'Logic', text: 'Rules and transformations.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'API & System Integration Client Reviews and Testimonials',
      reviews: [
        { name: 'Rachel D', role: 'Finance Director, Wholesale', text: 'Orders now flow from Shopify into our ERP and Xero automatically. Month-end is days faster.' },
        { name: 'Owen P', role: 'Head of Ops, Logistics', text: 'Their integration hub replaced three fragile scripts and has not missed a sync since.' },
        { name: 'Simran K', role: 'Sales Director, SaaS', text: 'Our CRM, billing and support tools finally agree on every customer.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'API & System Integration Services by Industry',
      items: [
        { slug: 'e-commerce', text: 'Store, stock, courier and accounts in sync.' },
        { slug: 'finance', text: 'Secure data feeds and client systems.' },
        { slug: 'healthcare', text: 'Booking, records and billing connected.' },
        { slug: 'travel', text: 'Supplier, booking and payment APIs.' },
        { slug: 'technology-saas', text: 'Public APIs and partner integrations.' },
        { slug: 'automotive', text: 'Stock feeds, DMS and marketplace listings.' },
      ],
    },
  ],
  faqs: [
    { q: 'What is an API?', a: 'An API (application programming interface) is a set of rules that lets one piece of software request data or actions from another, securely and automatically.' },
    { q: 'Can you connect systems that do not have an API?', a: 'Often, yes. We can use database connections, file exchanges such as CSV over SFTP, or older SOAP services to integrate legacy systems, then wrap them in a modern API so other tools can use the data safely.' },
    { q: 'Should we use Zapier or a custom integration?', a: 'Zapier and Make are great for simple, low-volume tasks. For high volumes, complex rules or critical data, a custom integration is more reliable and cheaper to run.' },
    { q: 'How do you keep integrations secure?', a: 'We use OAuth 2, encrypted credentials, least-privilege access and full audit logs, and follow GDPR rules for personal data. Every integration is tested against failure and abuse before it goes live.' },
    { q: 'What happens if an integration fails?', a: 'Failed messages are retried automatically and stored safely, and our team is alerted so nothing is lost. A dashboard shows every sync, so you can see what happened and replay any item that needs it.' },
    { q: 'Can you build an API for our customers or partners?', a: 'Yes. We build public and partner APIs with documentation, keys, rate limits and usage analytics, so customers and partners can connect to your platform safely, and you can see how they use it.' },
    { q: 'Do you support integrations after launch?', a: 'Yes. We monitor integrations and update them when connected systems change their APIs, which happens often. Support plans include alerts, fixes and a named contact, so your data keeps flowing without surprises.' },
    { q: 'What is a REST API and why use one for third party integration?', a: 'A REST API is the common standard that lets software exchange data over the web in a simple, predictable way. Most modern tools offer one, so third party integration with systems like HubSpot, Xero and Shopify is faster, cheaper and more reliable than manual exports.' },
  ],
  related: ['crm-erp-development', 'web-application-development', 'php-development', 'laravel-development', 'saas-product-development', 'ecommerce-development'],
};

export default content;
