import type { ServiceContent } from '../types';

// Entity map: branding -> brand strategy, brand purpose, mission, vision and values, target audience
// and personas, competitor analysis, brand positioning, brand name, logo design, visual identity
// (colour palette, typography, imagery, iconography), brand guidelines, tone of voice, tagline,
// brand story, rebranding, brand architecture, touchpoints (website, packaging, signage, social).

const content: ServiceContent = {
  slug: 'branding',
  short: 'Branding',
  metaTitle: 'Branding Agency UK | Brand Strategy, Logo & Identity Design | GTech Digital',
  metaDescription:
    'UK branding agency creating brand strategy, positioning, logos, visual identities and brand guidelines that make businesses memorable and easier to choose.',
  hero: {
    eyebrow: 'Branding Agency UK',
    title: 'A Brand That Makes You',
    highlight: 'Easy to Choose',
    lead:
      'We create brand strategies, logos and identities that make your business stand out, build trust at first glance and let you charge what you are worth.',
    motion: '/services/brandid.webp',
    points: ['Free brand review', 'Strategy before design', 'Full brand guidelines'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-branding',
      nav: 'What is it',
      eyebrow: 'The basics',
      heading: 'What Is Branding?',
      paras: [
        'Branding is far more than a logo. It is the strategy, visual identity and voice that shape how people see your business. A strong brand helps customers remember you, trust you and pick you over cheaper competitors.',
      ],
      bullets: [
        'Strategy: purpose, audience and positioning',
        'Identity: logo, colours, typography and imagery',
        'Voice: messaging, tagline and tone that sound like you',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      eyebrow: 'Results in numbers',
      heading: 'Brands That Earn Their Keep',
      text: 'The numbers behind the brands we create and refresh.',
      stats: [
        { value: '120+', label: 'Brands created or refreshed' },
        { value: '+64%', label: 'Average lift in brand recognition' },
        { value: '+22%', label: 'Average order value after rebrand' },
        { value: '38', label: 'Average touchpoints aligned' },
      ],
    },
    {
      type: 'media',
      id: 'strategy',
      nav: 'Strategy',
      eyebrow: 'Brand strategy',
      heading: 'Strategy Before Design',
      image: '/pages/brand/positioning.webp',
      alt: 'Brand strategy layers: purpose, audience, positioning, messaging and personality',
      paras: ['We start with research into your customers and competitors, then define why you exist and why people should choose you.'],
      bullets: ['Customer and competitor research', 'Purpose, mission and values', 'Positioning and value proposition', 'Brand personality'],
    },
    {
      type: 'media',
      id: 'identity',
      nav: 'Identity',
      eyebrow: 'Visual identity',
      heading: 'A Look That Is Unmistakably Yours',
      image: '/pages/brand/identity.webp',
      alt: 'Brand identity board with logo, typography and colour palette',
      flip: true,
      tone: 'grey',
      paras: ['We design a logo and visual system that work everywhere, from a website favicon to a shop sign.'],
      bullets: ['Logo and brand marks', 'Colour palette', 'Typography', 'Imagery and icon style'],
    },
    {
      type: 'media',
      id: 'guidelines',
      nav: 'Guidelines',
      eyebrow: 'Brand guidelines',
      heading: 'Guidelines That Keep You Consistent',
      image: '/pages/brand/guidelines.webp',
      alt: 'Brand guidelines covering logo, colour, type, voice, imagery and templates',
      paras: ['Clear guidelines and templates help your team, printers and agencies use the brand correctly every time.'],
      bullets: ['Logo usage rules', 'Colour and type specifications', 'Tone of voice guide', 'Social and print templates'],
    },
    {
      type: 'media',
      id: 'roll-out',
      nav: 'Roll-out',
      eyebrow: 'Brand roll-out',
      heading: 'One Brand Across Every Touchpoint',
      image: '/pages/brand/touchpoints.webp',
      alt: 'Brand applied across website, social media, email, packaging, signage and print',
      flip: true,
      tone: 'grey',
      paras: ['We bring the new brand to life across your website, social media, stationery, packaging and signage.'],
      bullets: ['Website and social media', 'Stationery and presentations', 'Packaging and signage', 'Launch plan'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      eyebrow: 'Our branding service',
      heading: 'Everything Included',
      cards: [
        { icon: 'lucide:search', title: 'Brand Research', text: 'Customers and competitors.' },
        { icon: 'lucide:compass', title: 'Positioning', text: 'Why choose you.' },
        { icon: 'lucide:gem', title: 'Logo Design', text: 'Primary logo and marks.' },
        { icon: 'lucide:palette', title: 'Colour & Type', text: 'A complete visual system.' },
        { icon: 'lucide:message-square', title: 'Messaging', text: 'Tagline and tone of voice.' },
        { icon: 'lucide:book-open', title: 'Guidelines', text: 'Clear rules and templates.' },
        { icon: 'lucide:layout-template', title: 'Brand Assets', text: 'Social, print and slides.' },
        { icon: 'lucide:rocket', title: 'Launch', text: 'Roll-out across channels.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      eyebrow: 'How we work',
      heading: 'Our Branding Process',
      steps: [
        { title: 'Discover', text: 'Workshop and research.' },
        { title: 'Define', text: 'Strategy and positioning.' },
        { title: 'Explore', text: 'Creative concepts.' },
        { title: 'Refine', text: 'Chosen route perfected.' },
        { title: 'Document', text: 'Guidelines and assets.' },
        { title: 'Launch', text: 'Roll-out support.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      eyebrow: 'Branding case studies',
      heading: 'Brands We Have Created',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Refresh vs rebrand',
      eyebrow: 'Compare',
      heading: 'Brand Refresh vs Full Rebrand',
      columns: ['', 'Brand refresh', 'Full rebrand'],
      rows: [
        ['What changes', 'Logo tidy, colours, type', 'Strategy, name or identity'],
        ['Best when', 'The brand feels dated', 'The business has changed'],
        ['Timeline', '3 to 5 weeks', '8 to 12 weeks'],
        ['Risk', 'Low, keeps recognition', 'Higher, needs a launch plan'],
      ],
      note: 'A refresh often delivers most of the benefit while keeping the recognition you have earned.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      eyebrow: 'Investment',
      heading: 'How Much Does Branding Cost?',
      intro: 'UK branding typically ranges from about £2,500 for a logo and starter identity to £25,000+ for a full brand strategy and rebrand. Your quote depends on:',
      cards: [
        { icon: 'lucide:search', title: 'Research', text: 'Interviews and market study.' },
        { icon: 'lucide:gem', title: 'Identity scope', text: 'Logo only or full system.' },
        { icon: 'lucide:message-square', title: 'Messaging', text: 'Voice and copy needs.' },
        { icon: 'lucide:layout-template', title: 'Assets', text: 'Templates and roll-out.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      eyebrow: 'Client reviews',
      heading: 'What Our Branding Clients Say',
      reviews: [
        { name: 'Victoria H', role: 'Founder, Interiors Brand', text: 'The new brand lets us charge premium prices with confidence.' },
        { name: 'Callum R', role: 'MD, Engineering Firm', text: 'We finally look like the established company we are. Tender wins went up.' },
        { name: 'Amara O', role: 'Owner, Restaurant', text: 'Guests now recognise our brand across the street and on Instagram.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      eyebrow: 'Industries we serve',
      heading: 'Branding for Your Industry',
      items: [
        { slug: 'hospitality-hotels', text: 'Restaurants, bars and hotels with personality.' },
        { slug: 'e-commerce', text: 'Product brands and packaging that sell.' },
        { slug: 'technology-saas', text: 'Clear, modern brands for tech companies.' },
        { slug: 'finance', text: 'Trustworthy brands for advisers and firms.' },
        { slug: 'healthcare', text: 'Calm, credible clinic and wellness brands.' },
        { slug: 'real-estate', text: 'Premium brands for agents and developers.' },
      ],
    },
  ],
  faqs: [
    { q: 'What is included in a branding project?', a: 'Typically research, brand strategy and positioning, logo and visual identity, messaging and tone of voice, brand guidelines and core templates.' },
    { q: 'How long does a branding project take?', a: 'Most projects take 6 to 10 weeks. A logo and starter identity can be done in 3 to 4 weeks.' },
    { q: 'How many logo concepts will we see?', a: 'Usually two or three distinct creative routes, each grounded in the strategy, followed by refinement of your chosen route.' },
    { q: 'Do we own the brand files?', a: 'Yes. You receive all final files and full ownership of the designs.' },
    { q: 'Can you help with a business name?', a: 'Yes. We offer naming, including trademark and domain checks, as part of a full brand project.' },
    { q: 'Can you apply the brand to our website?', a: 'Yes. Our web team can design and build a website around your new brand.' },
    { q: 'Do you work with start-ups?', a: 'Yes. We offer starter brand packages for new businesses that can grow with you.' },
  ],
  related: ['website-design', 'marketing-advisory', 'conversion-rate-optimization', 'facebook-marketing', 'content-marketing', 'instagram-marketing'],
};

export default content;
