import type { ServiceContent } from '../types';

// Entity map: branding and strategy -> brand strategy, brand positioning, brand identity (logo,
// colour palette, typography), brand guidelines, messaging and tone of voice, rebrand, marketing
// strategy, marketing advisory (fractional CMO), budget allocation, KPIs, conversion rate
// optimisation (CRO), A/B testing, customer research, brand equity, consistency across touchpoints.

const content: ServiceContent = {
  slug: 'branding-strategy',
  short: 'Branding & Strategy',
  metaTitle: 'Branding & Marketing Strategy Agency UK | Brand, Advisory & CRO | GTech Digital',
  metaDescription:
    'UK branding and strategy agency: brand identity and positioning, senior marketing advisory and conversion rate optimisation that make every marketing pound work harder.',
  hero: {
    keyword: 'Branding and Strategy',
    title: 'Branding and Strategy That',
    highlight: 'Drives Growth',
    lead:
      'GTech Digital is a UK branding and marketing strategy agency that creates brand identities, growth plans and conversion optimisation programmes, helping businesses stand out, spend their budget wisely and turn more visitors into customers.',
    motion: '/services/branding.webp',
    points: ['Free strategy session', 'Senior-led thinking', 'Decisions backed by data'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-branding-strategy',
      nav: 'What is it',
      heading: 'What Are Branding and Strategy?',
      paras: [
        'Your brand is how people recognise and remember you. Your strategy decides who you target, where you show up and how much you spend. Together they make every website, ad and post more effective, because each one builds on the last.',
      ],
      bullets: [
        'Branding: positioning, identity, guidelines and messaging',
        'Advisory: senior marketing guidance on channels, budget and growth',
        'CRO: research and testing that turn more visitors into customers',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'Branding & Strategy Results and Key Statistics',
      text: 'The numbers behind the branding and strategy work we do for UK businesses.',
      stats: [
        { value: '120+', label: 'Brands built or refreshed' },
        { value: '5.2x', label: 'Average marketing ROI' },
        { value: '+71%', label: 'Average conversion uplift from CRO' },
        { value: '-45%', label: 'Average cost per acquisition' },
      ],
    },
    {
      type: 'media',
      id: 'branding',
      nav: 'Branding',
      heading: 'Brand Identity Design: Logo, Colour and Typography',
      image: '/pages/brand/identity.webp',
      alt: 'Brand identity board with logo, typography and colour palette',
      paras: ['We build a distinctive identity from a clear strategy, so you look as good as the work you do.'],
      bullets: ['Brand strategy and positioning', 'Logo and visual identity', 'Messaging and tone of voice', 'Brand guidelines'],
    },
    {
      type: 'media',
      id: 'services-overview',
      nav: 'Our services',
      heading: 'Branding, Marketing Strategy and CRO Services Compared',
      image: '/pages/brandstrat/strategy.webp',
      alt: 'Branding and strategy services: branding, positioning, advisory, CRO, messaging and insight',
      flip: true,
      tone: 'grey',
      paras: ['Most agencies do one piece. We connect brand, strategy and conversion, so each improvement adds to the others.'],
      bullets: ['Positioning that sets you apart', 'Messaging that sells', 'Data-led decisions', 'One senior team throughout'],
    },
    {
      type: 'media',
      id: 'advisory',
      nav: 'Advisory',
      heading: 'Marketing Strategy, Growth Planning and Budget Allocation',
      image: '/pages/advisory/plan.webp',
      alt: 'Twelve-month growth plan with goals, audience, channels, budget and measurement',
      paras: ['We turn your goals into a 12-month plan with channels, budgets and KPIs, and stay on hand to guide it.'],
      bullets: ['Growth plan and targets', 'Channel and budget mix', 'KPI dashboards', 'Fractional CMO support'],
    },
    {
      type: 'media',
      id: 'cro',
      nav: 'CRO',
      heading: 'Conversion Rate Optimisation: A/B Testing and UX Research',
      image: '/pages/cro/abtest.webp',
      alt: 'A/B test where variant B beats variant A with higher conversion rate and confidence',
      flip: true,
      tone: 'grey',
      paras: ['We find where visitors drop off, test better versions and keep only what wins.'],
      bullets: ['Analytics and journey research', 'Heatmaps and user feedback', 'A/B and multivariate tests', 'Landing page optimisation'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our Branding & Strategy Services',
      cards: [
        { icon: 'lucide:compass', title: 'Brand Strategy', text: 'Purpose, audience and positioning.' },
        { icon: 'lucide:gem', title: 'Visual Identity', text: 'Logo, colour and type.' },
        { icon: 'lucide:message-square', title: 'Messaging', text: 'Tagline, story and tone.' },
        { icon: 'lucide:book-open', title: 'Brand Guidelines', text: 'Rules everyone can follow.' },
        { icon: 'lucide:lightbulb', title: 'Marketing Advisory', text: 'Senior strategic guidance.' },
        { icon: 'lucide:wallet', title: 'Budget Planning', text: 'Spend where it works.' },
        { icon: 'lucide:flask-conical', title: 'CRO & Testing', text: 'More conversions.' },
        { icon: 'lucide:chart-column-increasing', title: 'Reporting', text: 'KPIs that matter.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our Branding & Strategy Process, Step by Step',
      steps: [
        { title: 'Listen', text: 'Goals, customers and market.' },
        { title: 'Research', text: 'Competitors and insights.' },
        { title: 'Define', text: 'Positioning and plan.' },
        { title: 'Create', text: 'Identity and messaging.' },
        { title: 'Activate', text: 'Roll-out across channels.' },
        { title: 'Optimise', text: 'Test, measure and improve.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'Branding & Strategy Case Studies and Results',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Which service',
      heading: 'Branding, Advisory or CRO: Which Do You Need?',
      columns: ['', 'Branding', 'Marketing Advisory', 'CRO'],
      rows: [
        ['Best when', 'You blend in or are rebranding', 'Marketing lacks direction', 'Traffic does not convert'],
        ['Main output', 'Identity and guidelines', 'Growth plan and budget', 'Winning tests'],
        ['Timeline', '6 to 10 weeks', 'Ongoing monthly', 'Ongoing monthly'],
      ],
      note: 'Not sure where to start? A free strategy session will point you to the biggest opportunity.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Do Branding and Strategy Cost?',
      intro: 'UK branding projects typically range from about £3,000 to £25,000, and advisory or CRO from about £1,000 per month. Your quote depends on:',
      cards: [
        { icon: 'lucide:gem', title: 'Brand scope', text: 'Refresh or full rebrand.' },
        { icon: 'lucide:search', title: 'Research', text: 'Depth of customer research.' },
        { icon: 'lucide:clock', title: 'Advisory time', text: 'Days per month.' },
        { icon: 'lucide:flask-conical', title: 'Testing volume', text: 'Tests run each month.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'Branding & Strategy Client Reviews and Testimonials',
      reviews: [
        { name: 'Victoria H', role: 'Founder, Interiors Brand', text: 'The rebrand let us raise prices by 20% and customers did not blink.' },
        { name: 'Mark S', role: 'CEO, Professional Services', text: 'For the first time our marketing has a plan, a budget and numbers we trust.' },
        { name: 'Ellie D', role: 'Ecommerce Manager', text: 'CRO tests lifted our conversion rate by 40% without extra ad spend.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'Branding & Strategy Services by Industry',
      items: [
        { slug: 'technology-saas', text: 'Positioning and growth plans for SaaS.' },
        { slug: 'finance', text: 'Trustworthy brands for financial firms.' },
        { slug: 'hospitality-hotels', text: 'Memorable brands for venues and hotels.' },
        { slug: 'e-commerce', text: 'Brands and CRO that grow online sales.' },
        { slug: 'healthcare', text: 'Calm, credible brands for clinics.' },
        { slug: 'b2b-marketing', text: 'Clear B2B positioning and messaging.' },
      ],
    },
  ],
  faqs: [
    { q: 'What comes first, branding or marketing strategy?', a: 'Strategy usually comes first, because it defines who you serve and why they should choose you. The brand then expresses that clearly and consistently.' },
    { q: 'How do I know if I need a rebrand?', a: 'Common signs are looking dated next to competitors, attracting the wrong customers, inconsistent materials or a business that has outgrown its original identity.' },
    { q: 'What is marketing advisory?', a: 'It is senior marketing guidance without a full-time hire, covering strategy, budgets, channels and team or agency management.' },
    { q: 'What is conversion rate optimisation?', a: 'CRO uses research and A/B testing to improve your website so more visitors become leads or customers.' },
    { q: 'How long does branding take?', a: 'A typical brand project takes 6 to 10 weeks, from research and strategy to final guidelines.' },
    { q: 'Do you work with in-house teams?', a: 'Yes. We often work alongside marketing teams and other agencies, providing strategy and direction.' },
    { q: 'Do you need a contract?', a: 'Branding is a fixed project. Advisory and CRO run on rolling monthly terms.' },
  ],
  related: ['branding', 'marketing-advisory', 'conversion-rate-optimization', 'website-design', 'content-marketing', 'search-engine-optimization'],
};

export default content;
