import type { ServiceContent } from '../types';

// Entity map: CMS development -> content management system, traditional vs headless CMS,
// WordPress, Strapi, Sanity, Contentful, Drupal, Webflow, content model (content types, fields,
// relationships), page builder, editorial workflow (drafts, approvals, scheduling), user roles,
// media library, SEO fields, multilingual content, API-first delivery, CMS migration, 301 redirects.

const content: ServiceContent = {
  slug: 'cms-development',
  short: 'CMS Development',
  metaTitle: 'CMS Development Agency UK | WordPress & Headless CMS | GTech Digital',
  metaDescription:
    'UK CMS development agency building WordPress and headless CMS websites with structured content, simple editing and safe migrations that keep your SEO.',
  hero: {
    keyword: 'CMS Development',
    title: 'CMS Development Your Team',
    highlight: 'Will Enjoy Using',
    lead:
      'GTech Digital builds content management systems for UK businesses, from WordPress to headless CMS platforms such as Strapi and Sanity, so teams can publish pages, posts and products quickly without code or developer help.',
    motion: '/services/cms.webp',
    points: ['Free CMS consultation', 'Editing without code', 'Safe migration and SEO'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-cms-development',
      nav: 'What is it',
      heading: 'What Is CMS Development and How Does It Work?',
      paras: [
        'A content management system (CMS) is the admin area where your team edits your website. CMS development means choosing the right platform, modelling your content and building an editing experience that fits how your team works.',
      ],
      bullets: [
        'Traditional CMS: WordPress or Drupal, with website and editor in one',
        'Headless CMS: Strapi, Sanity or Contentful feeding a fast front end',
        'Migration: moving content from an old CMS without losing rankings',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'CMS Development Results and Key Statistics',
      text: 'The numbers behind the CMS projects we deliver for UK teams.',
      stats: [
        { value: '5 min', label: 'Average time to publish a page' },
        { value: '70+', label: 'CMS projects delivered' },
        { value: '100%', label: 'Rankings kept after migration' },
        { value: '350+', label: 'Editors trained' },
      ],
    },
    {
      type: 'media',
      id: 'platforms',
      nav: 'Platforms',
      heading: 'Choosing a CMS: WordPress, Headless CMS or Custom',
      image: '/pages/cms/platforms.webp',
      alt: 'CMS options compared: WordPress, Webflow, Strapi, Sanity, Contentful and Drupal',
      paras: ['Every CMS has strengths. We recommend one based on your content, team, budget and the channels you publish to.'],
      bullets: ['WordPress for flexible websites', 'Headless CMS for speed and multi-channel', 'Drupal for complex permissions', 'Honest, platform-neutral advice'],
    },
    {
      type: 'media',
      id: 'content-model',
      nav: 'Content model',
      heading: 'CMS Content Modelling and Structured Content',
      image: '/pages/cms/model.webp',
      alt: 'Content model with pages, services, blog posts, locations and media types',
      flip: true,
      tone: 'grey',
      paras: ['We break content into clear types and fields, so you write it once and use it across pages, apps and channels.'],
      bullets: ['Content types and fields', 'Relationships between content', 'Multilingual and multi-site', 'SEO fields on every type'],
    },
    {
      type: 'media',
      id: 'editor',
      nav: 'Editing',
      heading: 'CMS Editing, User Roles and Publishing Workflows',
      image: '/pages/cms/editor.webp',
      alt: 'CMS editor with live preview, drag-and-drop sections, media library, SEO fields and user roles',
      paras: ['Your team gets live previews, drag-and-drop sections and approval workflows, all locked to your brand.'],
      bullets: ['Live preview and page sections', 'Drafts, approvals and scheduling', 'User roles and permissions', 'Media library with alt text'],
    },
    {
      type: 'media',
      id: 'migration',
      nav: 'Migration',
      heading: 'CMS Migration Without Losing SEO Rankings or Traffic',
      image: '/pages/cms/migration.webp',
      alt: 'CMS migration plan with content mapping, 301 redirects, SEO metadata and training',
      flip: true,
      tone: 'grey',
      paras: ['We map every page, move content and metadata, and redirect every old URL so your traffic carries over safely.'],
      bullets: ['Content audit and mapping', 'Automated content import', '301 redirects for every URL', 'Editor training at launch'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our CMS Development Services',
      cards: [
        { icon: 'lucide:search', title: 'CMS Consultation', text: 'The right platform for you.' },
        { icon: 'lucide:layers', title: 'Content Modelling', text: 'Types, fields and relationships.' },
        { icon: 'lucide:layout-template', title: 'Page Sections', text: 'Flexible, on-brand building blocks.' },
        { icon: 'lucide:git-branch', title: 'Workflows', text: 'Drafts, approvals and scheduling.' },
        { icon: 'lucide:globe', title: 'Multilingual', text: 'Languages and regions managed.' },
        { icon: 'lucide:database', title: 'Migration', text: 'Content moved safely.' },
        { icon: 'lucide:zap', title: 'Fast Front End', text: 'Headless builds with Next.js.' },
        { icon: 'lucide:graduation-cap', title: 'Training', text: 'Guides and team sessions.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our CMS Development Process, Step by Step',
      steps: [
        { title: 'Discover', text: 'Content, team and workflows.' },
        { title: 'Recommend', text: 'Platform and content model.' },
        { title: 'Design', text: 'Templates and page sections.' },
        { title: 'Build', text: 'CMS and front end developed.' },
        { title: 'Migrate', text: 'Content moved and redirected.' },
        { title: 'Train', text: 'Your team publishing confidently.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'CMS Development Case Studies and Results',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Traditional vs headless',
      heading: 'Traditional CMS vs Headless CMS',
      columns: ['', 'Traditional (WordPress)', 'Headless (Strapi, Sanity)'],
      rows: [
        ['Best for', 'Websites and blogs', 'Websites, apps and multiple channels'],
        ['Speed', 'Good with optimisation', 'Excellent'],
        ['Setup cost', 'Lower', 'Higher'],
        ['Preview', 'Built in', 'Set up per project'],
      ],
      note: 'Many teams start with WordPress and move to headless when they publish to more channels.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does CMS Development Cost?',
      intro: 'UK CMS websites typically range from about £4,000 to £30,000+, depending on platform and scale. Your quote depends on:',
      cards: [
        { icon: 'lucide:layers', title: 'Content types', text: 'How much structure you need.' },
        { icon: 'lucide:globe', title: 'Languages', text: 'Regions and translations.' },
        { icon: 'lucide:database', title: 'Migration', text: 'Volume of content to move.' },
        { icon: 'lucide:git-branch', title: 'Workflows', text: 'Roles and approval steps.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'CMS Development Client Reviews and Testimonials',
      reviews: [
        { name: 'Laura F', role: 'Content Lead, University', text: 'Forty editors now publish safely, with approvals built into the CMS.' },
        { name: 'Mo A', role: 'Marketing Director, SaaS', text: 'Moving to a headless CMS made our site much faster and kept every ranking.' },
        { name: 'Grace T', role: 'Manager, Charity', text: 'We used to wait days for developers. Now we publish pages ourselves in minutes.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'CMS Development Services by Industry',
      items: [
        { slug: 'education', text: 'Large sites with many departments and editors.' },
        { slug: 'healthcare', text: 'Treatment and location content kept accurate.' },
        { slug: 'technology-saas', text: 'Headless CMS for product and docs sites.' },
        { slug: 'travel', text: 'Destinations and offers across languages.' },
        { slug: 'real-estate', text: 'Developments, listings and area guides.' },
        { slug: 'finance', text: 'Approval workflows for compliant content.' },
      ],
    },
  ],
  faqs: [
    { q: 'What is the best CMS for a business website?', a: 'For most small and medium businesses, WordPress is the best balance of cost and flexibility. Headless CMS platforms suit teams that need top speed or publish to apps and multiple sites.' },
    { q: 'What is a headless CMS?', a: 'A headless CMS stores and manages content, then sends it to your website or app through an API. It keeps content separate from design, which makes sites faster and content reusable.' },
    { q: 'Can we preview pages before publishing?', a: 'Yes. We set up live preview so editors see exactly how a page will look before it goes live.' },
    { q: 'Will we lose SEO when changing CMS?', a: 'Not if it is planned well. We keep URLs where possible, move metadata and set up 301 redirects for every changed URL.' },
    { q: 'Can different people have different permissions?', a: 'Yes. We set up user roles so writers, editors and admins see only what they need, with approvals where required.' },
    { q: 'Do you provide training?', a: 'Yes. Every project includes team training and simple written guides.' },
    { q: 'Do you support the CMS after launch?', a: 'Yes. Our support plans cover updates, security and new features.' },
  ],
  related: ['wordpress-development', 'website-design', 'website-maintenance', 'content-marketing', 'web-application-development', 'search-engine-optimization'],
};

export default content;
