import type { ServiceContent } from '../types';

// Entity map: content marketing -> content strategy, topic clusters, pillar pages, search intent,
// buyer journey (awareness, consideration, decision), blog articles, guides, comparison pages,
// cost guides, FAQs, video (YouTube, Shorts), infographics, email newsletters, distribution,
// E-E-A-T, helpful content, AI-ready content (AI Overviews, ChatGPT citations), content audits,
// content refresh, KPIs: organic traffic, engagement, assisted conversions, leads.

const content: ServiceContent = {
  slug: 'content-marketing',
  short: 'Content Marketing',
  metaTitle: 'Content Marketing Agency UK | SEO & AI-Ready Content | GTech Digital',
  metaDescription:
    'UK content marketing agency creating strategy, articles, guides and video that rank on Google, get cited in AI answers and turn readers into customers.',
  hero: {
    title: 'Content Marketing That Ranks',
    highlight: 'and Converts',
    lead:
      'We plan and create articles, guides and video that answer your buyers’ questions, rank on Google, get quoted by AI tools and move readers towards an enquiry.',
    motion: '/services/content.webp',
    points: ['Free content audit', 'Expert UK writers', 'Every piece tied to a goal'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-content-marketing',
      nav: 'What is it',
      heading: 'What Is Content Marketing?',
      paras: [
        'Content marketing means creating genuinely useful content that your buyers search for, share and trust. Done well, it brings in traffic every month, builds authority with Google and AI tools, and makes your sales conversations easier.',
      ],
      bullets: [
        'Strategy: the topics and questions that matter most to your buyers',
        'Creation: articles, guides, comparison pages, video and visuals',
        'Distribution: SEO, email, social and AI visibility so it gets seen',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'Content Marketing Results in Numbers',
      text: 'The numbers behind the content we create for UK businesses.',
      stats: [
        { value: '2,600+', label: 'Articles published' },
        { value: '+212%', label: 'Average organic growth' },
        { value: '310+', label: 'AI answer citations' },
        { value: '48', label: 'Average page-one articles' },
      ],
    },
    {
      type: 'media',
      id: 'strategy',
      nav: 'Strategy',
      heading: 'Content Strategy and Keyword Research',
      image: '/pages/content/strategy.webp',
      alt: 'Pillar page connected to supporting articles in a topic cluster',
      paras: ['We map every question your buyers ask, from first research to final decision, and group them into topic clusters that build authority around your core services.'],
      bullets: ['Keyword and question research', 'Topic clusters and pillar pages', 'Content audit and gap analysis', 'A 3 to 6 month content calendar'],
    },
    {
      type: 'media',
      id: 'articles',
      nav: 'Articles & guides',
      heading: 'SEO Content Writing',
      image: '/pages/content/articles.webp',
      alt: 'Monthly content plan with guides, FAQs, comparisons, cost guides and checklists',
      flip: true,
      tone: 'grey',
      paras: ['Our UK writers work with your team to add real experience and expertise, the E-E-A-T signals Google and AI tools look for, to every piece.'],
      bullets: ['Guides, how-tos and cost guides', 'Comparison and alternatives pages', 'FAQ hubs and glossaries', 'Refreshes of older, declining content'],
    },
    {
      type: 'media',
      id: 'video',
      nav: 'Video & visual',
      heading: 'Video and Visual Content',
      image: '/pages/content/video.webp',
      alt: 'Short explainer video with views, click-through and conversion figures',
      paras: ['Short explainers, product demos and infographics make complex ideas simple, rank on YouTube and Google, and work across every social channel.'],
      bullets: ['Explainer and product videos', 'YouTube and Shorts optimisation', 'Infographics and diagrams', 'Repurposing for social and email'],
    },
    {
      type: 'media',
      id: 'distribution',
      nav: 'Distribution',
      heading: 'Content Distribution and Promotion',
      image: '/pages/content/distribution.webp',
      alt: 'Organic traffic from content growing with articles published and AI citations',
      flip: true,
      tone: 'grey',
      paras: ['Publishing is only half the job. We make every piece easy for search engines and AI tools to understand and quote, then share it where your buyers are.'],
      bullets: ['On-page SEO and schema for every piece', 'Structured answers for AI Overviews and ChatGPT', 'Email newsletters and social snippets', 'Internal links to your service pages'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our Content Marketing Services',
      cards: [
        { icon: 'lucide:search', title: 'Content Audit', text: 'What works, what to refresh and what is missing.' },
        { icon: 'lucide:map', title: 'Strategy & Calendar', text: 'Topics, formats and dates planned months ahead.' },
        { icon: 'lucide:pen-line', title: 'Expert Writing', text: 'UK writers who research and interview your team.' },
        { icon: 'lucide:video', title: 'Video & Visuals', text: 'Explainers, infographics and social cut-downs.' },
        { icon: 'lucide:file-text', title: 'SEO Optimisation', text: 'Every piece optimised before it is published.' },
        { icon: 'lucide:sparkles', title: 'AI-Ready Content', text: 'Clear answers that AI tools can quote.' },
        { icon: 'lucide:mail', title: 'Distribution', text: 'Email, social and internal linking for reach.' },
        { icon: 'lucide:chart-column-increasing', title: 'Reporting', text: 'Traffic, engagement, citations and leads.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our Content Marketing Process',
      steps: [
        { title: 'Audit', text: 'We review your current content and competitors.' },
        { title: 'Research', text: 'Buyer questions, keywords and search intent mapped.' },
        { title: 'Plan', text: 'A calendar of topics, formats and goals.' },
        { title: 'Create', text: 'Expert drafts, edited and approved by you.' },
        { title: 'Publish & share', text: 'Optimised, published and distributed.' },
        { title: 'Measure & refresh', text: 'Results tracked and content kept up to date.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'Content Marketing Case Studies',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Content types',
      heading: 'Content Marketing Formats Compared',
      columns: ['', 'Guides & how-tos', 'Comparison pages', 'Video'],
      rows: [
        ['Buyer stage', 'Awareness and research', 'Decision', 'Every stage'],
        ['Main goal', 'Traffic and authority', 'Leads and sales', 'Engagement and trust'],
        ['AI visibility', 'Often cited in answers', 'Cited for "best" and "vs" queries', 'Shown in video results'],
        ['Typical lifespan', 'Years with refreshes', 'Updated yearly', 'Months to years'],
      ],
      note: 'We usually start with comparison and cost pages for quick leads, then build guides for long-term traffic.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does Content Marketing Cost?',
      intro: 'UK content marketing retainers typically range from about £500 to £4,000+ per month. Your quote depends on:',
      cards: [
        { icon: 'lucide:file-text', title: 'Volume', text: 'How many pieces you need each month.' },
        { icon: 'lucide:book-open', title: 'Depth', text: 'Quick answers or in-depth expert guides.' },
        { icon: 'lucide:video', title: 'Formats', text: 'Written only, or with video and design.' },
        { icon: 'lucide:graduation-cap', title: 'Expertise', text: 'Specialist sectors that need expert review.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'Content Marketing Client Reviews',
      reviews: [
        { name: 'Rachel G', role: 'Head of Marketing, SaaS', text: 'Their comparison pages now bring us more demo requests than our ads do.' },
        { name: 'Ben C', role: 'Owner, Ecommerce', text: 'Our buying guides rank on page one and are quoted in Google’s AI Overviews.' },
        { name: 'Laura D', role: 'Partner, Accountancy', text: 'They interview our team and turn it into content that sounds like us, only clearer.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'Content Marketing for Your Industry',
      items: [
        { slug: 'technology-saas', text: 'Comparison, alternatives and use-case content that drives demos.' },
        { slug: 'e-commerce', text: 'Buying guides and category content that lift organic sales.' },
        { slug: 'finance', text: 'Clear, compliant explainers reviewed by qualified experts.' },
        { slug: 'healthcare', text: 'Accurate, reviewed health content that patients trust.' },
        { slug: 'education', text: 'Course and career guides that attract the right students.' },
        { slug: 'b2b-marketing', text: 'Thought leadership and case studies for long sales cycles.' },
      ],
    },
  ],
  faqs: [
    { q: 'How long does content marketing take to work?', a: 'New articles usually start ranking within 2 to 4 months, with traffic building steadily over 6 to 12 months. Comparison and cost pages often produce leads sooner.' },
    { q: 'How many articles should we publish each month?', a: 'Quality matters more than volume. Most businesses do well with 4 to 8 in-depth pieces a month, plus regular refreshes of existing content.' },
    { q: 'Do you use AI to write content?', a: 'We use AI tools for research and efficiency, but every piece is planned, written and edited by experienced UK writers and checked with your experts. That is what makes content helpful, accurate and trustworthy.' },
    { q: 'How do you get content cited by AI tools?', a: 'AI tools favour clear, well-structured answers from trusted sources. We write direct answers to specific questions, add schema and supporting evidence, and build your authority so AI tools are more likely to quote you.' },
    { q: 'Who owns the content?', a: 'You do. All content, images and video we create for you belong to your business.' },
    { q: 'Can you refresh our existing content?', a: 'Yes. Updating and consolidating older content is often the fastest way to win back rankings and traffic.' },
    { q: 'Do you need a contract?', a: 'No. We work on rolling monthly terms.' },
  ],
  related: ['search-engine-optimization', 'seo-backlinks', 'reputation-management', 'website-design', 'linkedin-marketing', 'google-ads'],
};

export default content;
