import type { ServiceContent } from '../types';

// Entity map: conversion rate optimisation (CRO) -> conversion rate, A/B testing, multivariate
// testing, split URL tests, statistical significance, hypothesis, heatmaps, scroll maps, session
// recordings, user surveys, usability testing, funnel analysis, GA4 events, landing pages,
// checkout optimisation, form optimisation, value proposition, social proof, CTA, cost per lead.

const content: ServiceContent = {
  slug: 'conversion-rate-optimization',
  short: 'Conversion Rate Optimisation',
  metaTitle: 'Conversion Rate Optimisation Agency UK | CRO & A/B Testing | GTech Digital',
  metaDescription:
    'UK conversion rate optimisation (CRO) agency using research, heatmaps and A/B testing to turn more website visitors into leads and sales.',
  hero: {
    keyword: 'Conversion Rate Optimisation',
    title: 'Conversion Rate Optimisation',
    highlight: 'That Grows Sales',
    lead:
      'GTech Digital provides conversion rate optimisation (CRO) services in the UK, using analytics, heatmaps, user research and A/B testing to find why visitors leave and turn more website traffic into leads and sales.',
    motion: '/services/cro.webp',
    points: ['Free CRO audit', 'Research-led tests', 'Results proven by data'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-cro',
      nav: 'What is it',
      heading: 'What Is Conversion Rate Optimisation and How Does It Work?',
      paras: [
        'Conversion rate optimisation (CRO) is the process of improving your website so more visitors take action, such as buying, booking or enquiring. Doubling your conversion rate has the same effect as doubling your traffic, at a fraction of the cost.',
      ],
      bullets: [
        'Research: analytics, heatmaps and user feedback',
        'Testing: A/B tests that prove what works',
        'Growth: more leads and sales from the same budget',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'Conversion Rate Optimisation Results and Key Statistics',
      text: 'The numbers behind the CRO programmes we run.',
      stats: [
        { value: '+71%', label: 'Average conversion uplift' },
        { value: '-41%', label: 'Average cost per lead' },
        { value: '600+', label: 'A/B tests run' },
        { value: '58%', label: 'Test win rate' },
      ],
    },
    {
      type: 'media',
      id: 'research',
      nav: 'Research',
      heading: 'Conversion Research: Heatmaps, Analytics and User Insight',
      image: '/pages/cro/research.webp',
      alt: 'Web page annotated with conversion issues like unclear headline, weak value proposition and long form',
      paras: ['We combine analytics, heatmaps, recordings and surveys to pinpoint what stops people converting.'],
      bullets: ['GA4 funnel analysis', 'Heatmaps and session recordings', 'On-site surveys', 'Usability testing'],
    },
    {
      type: 'media',
      id: 'funnel',
      nav: 'Funnel',
      heading: 'Funnel Analysis, Checkout and Form Drop-Off Fixes',
      image: '/pages/cro/funnel.webp',
      alt: 'Conversion funnel from landing page to converted visitors with conversion rate and cost per lead',
      flip: true,
      tone: 'grey',
      paras: ['We map every step from landing to conversion and prioritise the drop-offs that cost you the most.'],
      bullets: ['Landing page optimisation', 'Form and checkout fixes', 'Mobile experience', 'Speed and trust signals'],
    },
    {
      type: 'media',
      id: 'testing',
      nav: 'A/B testing',
      heading: 'A/B Testing and Multivariate Experiments',
      image: '/pages/cro/abtest.webp',
      alt: 'A/B test where variant B beats variant A with higher conversion rate and 97% confidence',
      paras: ['Every change is tested against the original with real visitors, and we only roll out winners backed by statistical confidence.'],
      bullets: ['Hypotheses from research', 'A/B and multivariate tests', 'Statistical significance', 'Winners rolled out fast'],
    },
    {
      type: 'media',
      id: 'programme',
      nav: 'Programme',
      heading: 'Ongoing CRO Programme and Testing Roadmap',
      image: '/pages/cro/checklist.webp',
      alt: 'CRO programme checklist with tracking audit, heatmaps, surveys, roadmap and A/B tests',
      flip: true,
      tone: 'grey',
      paras: ['CRO works best as a steady programme. Each month we learn, test and build on the last result.'],
      bullets: ['Tracking audit and setup', 'Prioritised test roadmap', 'Monthly test cycles', 'Learnings shared with your team'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our Conversion Rate Optimisation Services',
      cards: [
        { icon: 'lucide:search', title: 'CRO Audit', text: 'Quick wins and big issues.' },
        { icon: 'lucide:settings-2', title: 'Tracking Setup', text: 'GA4 events you can trust.' },
        { icon: 'lucide:mouse-pointer-click', title: 'Heatmaps', text: 'Clicks, scrolls and recordings.' },
        { icon: 'lucide:message-square', title: 'User Research', text: 'Surveys and interviews.' },
        { icon: 'lucide:list-checks', title: 'Test Roadmap', text: 'Ideas ranked by impact.' },
        { icon: 'lucide:flask-conical', title: 'A/B Testing', text: 'Designed, built and run.' },
        { icon: 'lucide:layout-template', title: 'Landing Pages', text: 'Pages built to convert.' },
        { icon: 'lucide:chart-column-increasing', title: 'Reporting', text: 'Uplift and revenue impact.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our Conversion Rate Optimisation Process, Step by Step',
      steps: [
        { title: 'Audit', text: 'Tracking and quick wins.' },
        { title: 'Research', text: 'Data, heatmaps and users.' },
        { title: 'Prioritise', text: 'Test ideas ranked.' },
        { title: 'Test', text: 'A/B tests run properly.' },
        { title: 'Roll out', text: 'Winners go live.' },
        { title: 'Repeat', text: 'Monthly learning cycles.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'Conversion Rate Optimisation Case Studies and Results',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'CRO vs more traffic',
      heading: 'CRO vs Buying More Traffic',
      columns: ['', 'Conversion optimisation', 'More ad spend'],
      rows: [
        ['Effect', 'More results from every visitor', 'More visitors at the same rate'],
        ['Cost over time', 'Falls as wins compound', 'Rises with every click'],
        ['Lasting value', 'Improvements stay', 'Stops when spend stops'],
        ['Best together', 'Makes ads more profitable', 'Brings data for testing'],
      ],
      note: 'CRO makes every other channel, from SEO to paid ads, more profitable.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does CRO Cost?',
      intro: 'UK CRO programmes typically range from about £1,000 to £5,000+ per month, or from £1,500 for a one-off audit. Your quote depends on:',
      cards: [
        { icon: 'lucide:users', title: 'Traffic', text: 'Visitors available to test.' },
        { icon: 'lucide:flask-conical', title: 'Tests per month', text: 'Pace of experimentation.' },
        { icon: 'lucide:message-square', title: 'Research', text: 'Surveys and user testing.' },
        { icon: 'lucide:code-xml', title: 'Development', text: 'Complexity of test builds.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'Conversion Rate Optimisation Client Reviews and Testimonials',
      reviews: [
        { name: 'Ellie D', role: 'Ecommerce Manager', text: 'Conversion rate up 40% in six months, with no extra ad spend.' },
        { name: 'George N', role: 'Marketing Director, Insurance', text: 'A shorter quote form alone cut our cost per lead by a third.' },
        { name: 'Isla P', role: 'Founder, Subscription Box', text: 'Every test is explained clearly and we learn something new about our customers each month.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'Conversion Rate Optimisation Services by Industry',
      items: [
        { slug: 'e-commerce', text: 'Product, basket and checkout optimisation.' },
        { slug: 'finance', text: 'Quote and application forms that convert.' },
        { slug: 'technology-saas', text: 'Sign-up and trial-to-paid improvements.' },
        { slug: 'travel', text: 'Booking flows that drop fewer customers.' },
        { slug: 'education', text: 'Course pages and enquiry forms.' },
        { slug: 'healthcare', text: 'Booking journeys patients complete.' },
      ],
    },
  ],
  faqs: [
    { q: 'What is a good conversion rate?', a: 'It depends on your industry and goal. Many lead generation sites convert 2 to 5% of visitors, and ecommerce stores 1 to 3%. We benchmark against your own data and competitors.' },
    { q: 'How much traffic do I need for A/B testing?', a: 'Reliable A/B tests usually need at least a few thousand visitors a month to the page being tested. With less traffic, we focus on research-led improvements instead.' },
    { q: 'How long does each test run?', a: 'Most tests run for two to four weeks, long enough to cover full weekly cycles and reach statistical significance.' },
    { q: 'Will testing affect our SEO?', a: 'No. We follow Google’s guidance for testing, so your rankings are not affected.' },
    { q: 'Which tools do you use?', a: 'GA4, heatmap and recording tools such as Hotjar or Microsoft Clarity, and testing platforms such as VWO or Optimizely.' },
    { q: 'Do you build the test variations?', a: 'Yes. Our designers and developers create and QA every variation.' },
    { q: 'Do you need a contract?', a: 'No. CRO programmes run on rolling monthly terms.' },
  ],
  related: ['website-design', 'google-ads', 'marketing-advisory', 'ecommerce-development', 'search-engine-optimization', 'paid-media'],
};

export default content;
