import type { ServiceContent } from '../types';

// Entity map: CRM and ERP development -> customer relationship management, enterprise resource
// planning, sales pipeline, leads, deals, quotes, orders, invoicing, inventory and warehouse
// management, purchasing, job scheduling, field service, finance integration (Xero, Sage),
// reporting dashboards, workflow automation, user roles, data migration, Salesforce/HubSpot/Odoo
// customisation vs bespoke, per-user licence costs.

const content: ServiceContent = {
  slug: 'crm-erp-development',
  short: 'CRM & ERP Development',
  metaTitle: 'Custom CRM & ERP Development UK | Bespoke Business Systems | GTech Digital',
  metaDescription:
    'UK custom CRM and ERP development: bespoke systems for sales, orders, stock, scheduling and finance that automate admin and give you live control of the business.',
  hero: {
    eyebrow: 'CRM & ERP Development UK',
    title: 'One System to Run',
    highlight: 'Your Whole Business',
    lead:
      'We build custom CRM and ERP systems that bring sales, orders, stock, jobs and finance together, automating admin and giving you live numbers.',
    motion: '/services/crm.webp',
    points: ['Free process review', 'No per-user licence fees', 'Data migrated for you'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-crm-erp',
      nav: 'What is it',
      eyebrow: 'The basics',
      heading: 'What Are CRM and ERP Systems?',
      paras: [
        'A CRM (customer relationship management) system manages leads, customers and sales. An ERP (enterprise resource planning) system runs operations such as orders, stock, purchasing and finance. A custom system combines exactly the parts you need, built around how your business works.',
      ],
      bullets: [
        'CRM: leads, pipeline, quotes and customer history',
        'ERP: orders, stock, purchasing, jobs and invoicing',
        'Connected: synced with accounts, ecommerce and email',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      eyebrow: 'Results in numbers',
      heading: 'Less Admin, More Control',
      text: 'The numbers behind the CRM and ERP systems we build.',
      stats: [
        { value: '16h', label: 'Average admin saved per week' },
        { value: '+38%', label: 'Average win rate improvement' },
        { value: '-89%', label: 'Average reduction in order errors' },
        { value: '£0', label: 'Per-user licence fees' },
      ],
    },
    {
      type: 'media',
      id: 'crm',
      nav: 'CRM',
      eyebrow: 'Custom CRM',
      heading: 'A Sales Pipeline That Never Leaks',
      image: '/pages/crm/pipeline.webp',
      alt: 'Sales pipeline from new leads to won deals with win rate, sales cycle and pipeline value',
      paras: ['Every lead is captured, followed up and tracked to a sale, with reminders and quotes built in.'],
      bullets: ['Lead capture from web and email', 'Pipeline stages and reminders', 'Quotes and proposals', 'Customer history in one place'],
    },
    {
      type: 'media',
      id: 'erp',
      nav: 'ERP',
      eyebrow: 'Custom ERP',
      heading: 'Operations, Stock and Finance Together',
      image: '/pages/crm/modules.webp',
      alt: 'Business system modules: CRM, inventory, orders, finance, scheduling and reports',
      flip: true,
      tone: 'grey',
      paras: ['We build the modules you need, from stock and purchasing to job scheduling and invoicing, all sharing the same data.'],
      bullets: ['Orders, quotes and invoicing', 'Stock and multi-warehouse', 'Purchasing and suppliers', 'Jobs, staff and scheduling'],
    },
    {
      type: 'media',
      id: 'automation',
      nav: 'Automation',
      eyebrow: 'Automation & reporting',
      heading: 'Admin That Runs Itself',
      image: '/pages/crm/automation.webp',
      alt: 'Orders processed automatically rising to 96% with workflows automated and fewer errors',
      paras: ['Repetitive tasks happen automatically, and live dashboards show sales, margins and performance at a glance.'],
      bullets: ['Automated workflows and alerts', 'Live dashboards and KPIs', 'Xero and Sage integration', 'Email and document generation'],
    },
    {
      type: 'media',
      id: 'migration',
      nav: 'Migration',
      eyebrow: 'Migration & adoption',
      heading: 'A Smooth Switch for Your Team',
      image: '/pages/crm/migration.webp',
      alt: 'Data migration plan with cleansing, field mapping, trial run, training and parallel running',
      flip: true,
      tone: 'grey',
      paras: ['We clean and move your data, train your team and run old and new systems side by side until everyone is confident.'],
      bullets: ['Data cleansing and mapping', 'Trial migrations', 'Team training', 'Phased roll-out'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      eyebrow: 'Our CRM & ERP service',
      heading: 'Everything Included',
      cards: [
        { icon: 'lucide:search', title: 'Process Review', text: 'How work flows today.' },
        { icon: 'lucide:users', title: 'CRM Modules', text: 'Leads, pipeline and quotes.' },
        { icon: 'lucide:package', title: 'Stock & Orders', text: 'Inventory and fulfilment.' },
        { icon: 'lucide:calendar-days', title: 'Scheduling', text: 'Jobs, staff and resources.' },
        { icon: 'lucide:landmark', title: 'Finance Sync', text: 'Xero, Sage and QuickBooks.' },
        { icon: 'lucide:workflow', title: 'Automation', text: 'Workflows and alerts.' },
        { icon: 'lucide:chart-column-increasing', title: 'Dashboards', text: 'Live reporting.' },
        { icon: 'lucide:database', title: 'Migration', text: 'Data moved and checked.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      eyebrow: 'How we work',
      heading: 'Our CRM & ERP Process',
      steps: [
        { title: 'Review', text: 'Processes and pain points.' },
        { title: 'Design', text: 'Modules and data model.' },
        { title: 'Build', text: 'Phased sprints with demos.' },
        { title: 'Migrate', text: 'Data cleaned and moved.' },
        { title: 'Train', text: 'Team onboarding.' },
        { title: 'Improve', text: 'New modules over time.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      eyebrow: 'CRM & ERP case studies',
      heading: 'Business Systems We Have Delivered',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Custom vs Salesforce',
      eyebrow: 'Compare',
      heading: 'Custom CRM vs Salesforce or HubSpot',
      columns: ['', 'Custom CRM / ERP', 'Salesforce / HubSpot'],
      rows: [
        ['Fit', 'Exactly your process', 'Configured around their model'],
        ['Licence fees', 'None', 'Per user, per month'],
        ['Operations (stock, jobs)', 'Built in', 'Extra apps or tools'],
        ['Setup time', 'Months', 'Weeks'],
      ],
      note: 'If a standard CRM fits, we will tell you. Custom pays off when you need operations too, or licences get expensive.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      eyebrow: 'Investment',
      heading: 'How Much Does a Custom CRM or ERP Cost?',
      intro: 'UK custom CRM systems typically range from about £15,000, and ERP systems from about £35,000 to £150,000+. Your quote depends on:',
      cards: [
        { icon: 'lucide:layers', title: 'Modules', text: 'CRM, stock, jobs and finance.' },
        { icon: 'lucide:users', title: 'Users & roles', text: 'Teams and permissions.' },
        { icon: 'lucide:webhook', title: 'Integrations', text: 'Accounts, store and email.' },
        { icon: 'lucide:database', title: 'Migration', text: 'Data to clean and move.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      eyebrow: 'Client reviews',
      heading: 'What Our CRM & ERP Clients Say',
      reviews: [
        { name: 'Martin G', role: 'MD, Manufacturing', text: 'Orders, stock and invoicing are finally in one system. We know our margins every day.' },
        { name: 'Joanne E', role: 'Sales Director, Services', text: 'No lead slips through any more, and our win rate has jumped.' },
        { name: 'Yusuf H', role: 'Owner, Installation Company', text: 'Job scheduling that took a full day now takes an hour.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      eyebrow: 'Industries we serve',
      heading: 'CRM & ERP for Your Industry',
      items: [
        { slug: 'b2b-marketing', text: 'Pipeline and account management for B2B sales.' },
        { slug: 'e-commerce', text: 'Orders, stock and fulfilment across channels.' },
        { slug: 'real-estate', text: 'Properties, landlords and tenancies.' },
        { slug: 'automotive', text: 'Stock, servicing and customer records.' },
        { slug: 'healthcare', text: 'Patients, appointments and billing.' },
        { slug: 'education', text: 'Enquiries, enrolments and fees.' },
      ],
    },
  ],
  faqs: [
    { q: 'Should we buy a CRM or build one?', a: 'If a standard CRM fits your process and licence costs are reasonable, buy one. Build when you need operations features too, when workarounds are slowing you down, or when per-user fees become expensive.' },
    { q: 'What is the difference between CRM and ERP?', a: 'A CRM manages customers and sales. An ERP manages operations like stock, orders, purchasing and finance. Many businesses need parts of both in one system.' },
    { q: 'Can you migrate data from our current system?', a: 'Yes. We clean, map and migrate your data, with trial runs before the final switch.' },
    { q: 'Will it connect to Xero or Sage?', a: 'Yes. We integrate with Xero, Sage, QuickBooks and most other accounting systems.' },
    { q: 'How long does it take?', a: 'A focused CRM takes around 10 to 14 weeks. A full ERP is usually delivered in phases over 4 to 9 months.' },
    { q: 'Can staff use it on mobile?', a: 'Yes. Systems are responsive, and we can add a mobile app for field teams.' },
    { q: 'Who owns the system?', a: 'You do, including the code and all your data.' },
  ],
  related: ['api-system-integration', 'web-application-development', 'laravel-development', 'saas-product-development', 'mobile-app-development', 'linkedin-marketing'],
};

export default content;
