import type { ServiceContent } from '../types';

// Entity map: custom software development -> bespoke software, web applications, mobile apps,
// APIs and system integration, CRM and ERP, SaaS products, MVPs, discovery phase, agile sprints,
// UX/UI design, cloud (AWS, Azure), automated testing, CI/CD, security, GDPR, IP ownership,
// total cost of ownership vs off-the-shelf software, process automation, digital transformation.

const content: ServiceContent = {
  slug: 'custom-software-development',
  short: 'Custom Software',
  metaTitle: 'Custom Software Development Company UK | Bespoke Software | GTech Digital',
  metaDescription:
    'UK custom software development company building web apps, mobile apps, integrations, CRM and ERP systems, SaaS products and MVPs that automate work and grow revenue.',
  hero: {
    keyword: 'Custom Software Development',
    title: 'Custom Software Development',
    highlight: 'Built Around You',
    lead:
      'GTech Digital is a UK custom software development company that designs and builds web applications, mobile apps, integrations, CRM and ERP systems, SaaS products and MVPs around the way each business works.',
    motion: '/services/software.webp',
    points: ['Free discovery call', 'Fixed-scope sprints', 'You own the code'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-custom-software',
      nav: 'What is it',
      heading: 'What Is Custom Software Development and How Does It Work?',
      paras: [
        'Custom software is built for your exact processes, rather than forcing your team to work around an off-the-shelf tool. It replaces spreadsheets and disconnected systems with one platform that automates the work, gives you live data and grows with you.',
      ],
      bullets: [
        'Internal tools: portals, dashboards and back-office systems',
        'Customer products: web apps, mobile apps and SaaS',
        'Connected systems: integrations that make your tools work as one',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'Custom Software Results and Key Statistics',
      text: 'The numbers behind the software we build for UK businesses.',
      stats: [
        { value: '90+', label: 'Software projects delivered' },
        { value: '420h', label: 'Average admin hours saved a month' },
        { value: '-91%', label: 'Average reduction in data errors' },
        { value: '87%', label: 'Average test coverage' },
      ],
    },
    {
      type: 'media',
      id: 'solutions',
      nav: 'What we build',
      heading: 'Bespoke Software Solutions for UK Businesses',
      image: '/pages/software/apps.webp',
      alt: 'Custom software types: web apps, mobile apps, integrations, CRM and ERP, SaaS and MVP',
      paras: ['Whether you need a better way to run the business or a product to take to market, we build it on proven, modern technology.'],
      bullets: ['Web applications and portals', 'iOS and Android apps', 'CRM, ERP and back-office systems', 'SaaS products and MVPs'],
    },
    {
      type: 'media',
      id: 'automation',
      nav: 'Automation',
      heading: 'Business Process Automation and Workflow Software',
      image: '/pages/software/automation.webp',
      alt: 'Admin hours saved growing each month with spreadsheets replaced and processes automated',
      flip: true,
      tone: 'grey',
      paras: ['We map how work really flows through your business, then automate the repetitive steps that cost time and cause errors.'],
      bullets: ['Process mapping workshops', 'Automated workflows and approvals', 'Live dashboards and reports', 'Fewer errors, faster turnaround'],
    },
    {
      type: 'media',
      id: 'integration',
      nav: 'Integration',
      heading: 'Software Integration With Your CRM, ERP and Accounting Systems',
      image: '/pages/software/integration.webp',
      alt: 'Platform connected to Xero, HubSpot, Stripe, Shopify, warehouse and email systems',
      paras: ['Your new software connects to the tools you already use, so data is entered once and flows everywhere it is needed.'],
      bullets: ['Accounting and payment systems', 'CRM and marketing tools', 'Ecommerce and warehouse systems', 'Legacy system connectors'],
    },
    {
      type: 'media',
      id: 'quality',
      nav: 'How we build',
      heading: 'Agile Software Development: Discovery, Build and Support',
      image: '/pages/software/quality.webp',
      alt: 'Software delivery checklist with discovery, sprints, automated tests, security and documentation',
      flip: true,
      tone: 'grey',
      paras: ['You see working software every two weeks, with automated tests and security built in, so there are no surprises at the end.'],
      bullets: ['Discovery and fixed-scope phases', 'Two-week sprints with demos', 'Automated testing and CI/CD', 'Security and GDPR by design'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: 'Our services',
      heading: 'What\'s Included in Our Custom Software Services',
      cards: [
        { icon: 'lucide:app-window', title: 'Web Applications', text: 'Portals, dashboards and tools.' },
        { icon: 'lucide:smartphone', title: 'Mobile Apps', text: 'iOS and Android apps.' },
        { icon: 'lucide:webhook', title: 'API & Integration', text: 'Your systems connected.' },
        { icon: 'lucide:database', title: 'CRM & ERP', text: 'Custom business systems.' },
        { icon: 'lucide:cloud', title: 'SaaS Products', text: 'Subscription software.' },
        { icon: 'lucide:rocket', title: 'MVP Development', text: 'Launch and validate fast.' },
        { icon: 'lucide:pen-tool', title: 'UX & UI Design', text: 'Software people enjoy using.' },
        { icon: 'lucide:life-buoy', title: 'Support', text: 'Hosting, fixes and features.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our Custom Software Process, Step by Step',
      steps: [
        { title: 'Discover', text: 'Goals, users and processes.' },
        { title: 'Design', text: 'Prototype tested with users.' },
        { title: 'Plan', text: 'Scope, phases and fixed price.' },
        { title: 'Build', text: 'Two-week sprints with demos.' },
        { title: 'Launch', text: 'Data migration and training.' },
        { title: 'Evolve', text: 'Support and new features.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'Custom Software Case Studies and Results',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Custom vs off-the-shelf',
      heading: 'Custom Software vs Off-the-Shelf',
      columns: ['', 'Custom software', 'Off-the-shelf'],
      rows: [
        ['Fit', 'Built for your process', 'You adapt to the tool'],
        ['Costs', 'Upfront build, no per-user fees', 'Low start, rising licence fees'],
        ['Ownership', 'You own the code and data', 'Vendor controls the roadmap'],
        ['Advantage', 'Unique to your business', 'Same as your competitors'],
      ],
      note: 'Custom software makes sense when workarounds, licence fees or manual work start costing more than a build.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does Custom Software Cost?',
      intro: 'UK custom software typically ranges from about £10,000 for a focused tool to £100,000+ for larger platforms. Your quote depends on:',
      cards: [
        { icon: 'lucide:puzzle', title: 'Features', text: 'Screens, roles and workflows.' },
        { icon: 'lucide:webhook', title: 'Integrations', text: 'Systems to connect.' },
        { icon: 'lucide:smartphone', title: 'Platforms', text: 'Web, iOS and Android.' },
        { icon: 'lucide:shield-check', title: 'Compliance', text: 'Security and data needs.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'Custom Software Client Reviews and Testimonials',
      reviews: [
        { name: 'Andrew L', role: 'MD, Distribution', text: 'Our custom system replaced 14 spreadsheets and saves the team two days a week.' },
        { name: 'Sana Q', role: 'Founder, HealthTech', text: 'They turned our idea into a live product with paying customers in four months.' },
        { name: 'Pete V', role: 'Operations Director, Facilities', text: 'Every sprint delivered something we could use. No surprises, no overruns.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'Custom Software Services by Industry',
      items: [
        { slug: 'healthcare', text: 'Booking, patient and compliance systems.' },
        { slug: 'finance', text: 'Secure portals, calculators and workflows.' },
        { slug: 'education', text: 'Learning platforms and admin tools.' },
        { slug: 'travel', text: 'Booking engines and supplier integrations.' },
        { slug: 'real-estate', text: 'Property and tenant management systems.' },
        { slug: 'technology-saas', text: 'SaaS products from MVP to scale.' },
      ],
    },
  ],
  faqs: [
    { q: 'When does custom software make sense?', a: 'When off-the-shelf tools force workarounds, when licence fees grow with every user, or when manual processes cost your team hours each week. Custom software also helps when the software itself is your competitive edge.' },
    { q: 'How long does custom software take?', a: 'A focused tool or MVP usually takes 8 to 12 weeks. Larger platforms are delivered in phases over 4 to 9 months, with usable releases along the way.' },
    { q: 'How do you price projects?', a: 'We start with a paid or free discovery phase, then give a fixed price per phase, so you always know the cost before work starts.' },
    { q: 'Who owns the software?', a: 'You do. You own the source code, data and intellectual property once each phase is paid for.' },
    { q: 'Which technologies do you use?', a: 'We choose proven tools for each project, typically Laravel, Node.js, React, Next.js, Flutter and React Native, hosted on AWS or Azure.' },
    { q: 'Is our data secure?', a: 'Yes. We build with encryption, role-based access, audit logs and GDPR compliance, and follow OWASP security practices.' },
    { q: 'Do you support the software after launch?', a: 'Yes. We offer hosting, monitoring, maintenance and ongoing development on monthly plans.' },
  ],
  related: ['web-application-development', 'mobile-app-development', 'api-system-integration', 'crm-erp-development', 'saas-product-development', 'mvp-development'],
};

export default content;
