import type { ServiceContent } from '../types';

// Entity map: digital advertising (online advertising) -> channels: search ads (Google, Microsoft
// Ads), social ads (Meta: Facebook & Instagram, TikTok, LinkedIn, Pinterest), display &
// programmatic (DSPs, banner and native ads), video (YouTube, CTV), retargeting/remarketing,
// audiences (custom, lookalike, in-market), ad formats, CPM, CPC, CTR, CPA, ROAS, Meta Pixel,
// Conversions API, landing pages, A/B testing.

const content: ServiceContent = {
  slug: 'digital-advertising',
  short: 'Digital Advertising',
  metaTitle: 'Digital Advertising Agency UK | Search, Social & Display Ads | GTech Digital',
  metaDescription:
    'UK digital advertising agency running search, social, display, video and retargeting campaigns that turn ad spend into measurable leads and sales.',
  hero: {
    eyebrow: 'Digital Advertising Agency UK',
    title: 'Ads Everywhere Your Customers',
    highlight: 'Spend Time',
    lead:
      'We plan and run digital advertising across Google, Meta, TikTok, LinkedIn, YouTube and display networks, reaching the right people with the right message at the right cost.',
    motion: '/services/digital.webp',
    points: ['Free ad account review', 'All channels, one team', 'Clear cost-per-result reporting'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-digital-advertising',
      nav: 'What is it',
      eyebrow: 'The basics',
      heading: 'What Is Digital Advertising?',
      paras: [
        'Digital advertising covers every paid ad you run online, from Google search ads to Instagram Reels and banner ads. Each channel reaches people at a different moment, so the best results come from choosing the right mix for your goals.',
      ],
      bullets: [
        'Search ads: capture people actively looking for what you sell',
        'Social and video ads: reach new audiences by interest and behaviour',
        'Display and retargeting: stay visible and bring visitors back to buy',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      eyebrow: 'Results in numbers',
      heading: 'Advertising Measured in Results',
      text: 'The numbers behind the campaigns we run for UK businesses.',
      stats: [
        { value: '6', label: 'Ad platforms managed' },
        { value: '-34%', label: 'Average cost per lead' },
        { value: '5.2x', label: 'Average ROAS' },
        { value: '1,900+', label: 'Ads tested each year' },
      ],
    },
    {
      type: 'media',
      id: 'search-ads',
      nav: 'Search ads',
      eyebrow: 'Search advertising',
      heading: 'Be There When They Search',
      image: '/pages/digital-advertising/search.webp',
      alt: 'Sponsored search ad for an accountant with click-through and lead figures',
      paras: ['Google and Microsoft search ads put you in front of buyers at the exact moment they look for your product or service.'],
      bullets: ['Google Ads and Microsoft Ads', 'Keyword and audience targeting', 'Ad copy and extensions', 'Call and form lead tracking'],
    },
    {
      type: 'media',
      id: 'social-ads',
      nav: 'Social ads',
      eyebrow: 'Social advertising',
      heading: 'Reach New Customers on Social',
      image: '/pages/digital-advertising/social.webp',
      alt: 'Social advertising results across Facebook, Instagram, TikTok, LinkedIn, Pinterest and YouTube',
      flip: true,
      tone: 'grey',
      paras: ['Social ads find people by interests, job titles and behaviour, then turn scrolling into clicks with scroll-stopping creative.'],
      bullets: ['Facebook and Instagram (Meta) ads', 'TikTok and Pinterest ads', 'LinkedIn ads for B2B', 'Lead forms and catalogue ads'],
    },
    {
      type: 'media',
      id: 'display-video',
      nav: 'Display & video',
      eyebrow: 'Display & video',
      heading: 'Build Awareness at Scale',
      image: '/pages/digital-advertising/display.webp',
      alt: 'Video ad with views, click-through, conversions and cost per sale',
      paras: ['Display, native and video ads build recognition with large, well-targeted audiences, so more people choose you when they are ready to buy.'],
      bullets: ['Google Display and Demand Gen', 'YouTube and connected TV', 'Programmatic and native ads', 'Brand-safe placements'],
    },
    {
      type: 'media',
      id: 'retargeting',
      nav: 'Retargeting',
      eyebrow: 'Retargeting',
      heading: 'Bring Back the Visitors Who Left',
      image: '/pages/digital-advertising/retargeting.webp',
      alt: 'Retargeting funnel from site visitors to returning customers and conversions',
      flip: true,
      tone: 'grey',
      paras: ['Most visitors leave without buying. Retargeting reminds them with relevant offers across Google and social, often at your lowest cost per sale.'],
      bullets: ['Website and app visitor audiences', 'Dynamic product retargeting', 'Abandoned basket campaigns', 'Frequency caps to avoid ad fatigue'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      eyebrow: 'Our advertising service',
      heading: 'Everything Included',
      cards: [
        { icon: 'lucide:search', title: 'Channel Strategy', text: 'The right mix of channels for your goals.' },
        { icon: 'lucide:users', title: 'Audience Targeting', text: 'Custom, lookalike and in-market audiences.' },
        { icon: 'lucide:pen-line', title: 'Ad Copy', text: 'Headlines and hooks written to convert.' },
        { icon: 'lucide:image', title: 'Creative Design', text: 'Static, carousel and video ad creative.' },
        { icon: 'lucide:layout-template', title: 'Landing Pages', text: 'Pages that match the ad and convert.' },
        { icon: 'lucide:settings-2', title: 'Tracking Setup', text: 'Pixels, Conversions API and GA4.' },
        { icon: 'lucide:flask-conical', title: 'A/B Testing', text: 'Constant testing of ads and audiences.' },
        { icon: 'lucide:chart-column-increasing', title: 'Reporting', text: 'Cost per result across every channel.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      eyebrow: 'How we work',
      heading: 'Our Advertising Process',
      steps: [
        { title: 'Discover', text: 'Goals, margins, audience and past results.' },
        { title: 'Plan', text: 'Channels, budget split and targets.' },
        { title: 'Create', text: 'Ads, creative and landing pages.' },
        { title: 'Launch', text: 'Campaigns live with tracking verified.' },
        { title: 'Test', text: 'New ads and audiences tested every week.' },
        { title: 'Scale', text: 'Budget moved to what performs best.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      eyebrow: 'Advertising case studies',
      heading: 'Advertising Results We Have Delivered',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Channels',
      eyebrow: 'Compare',
      heading: 'Which Ad Channel Fits Your Goal?',
      columns: ['', 'Search ads', 'Social ads', 'Display & video'],
      rows: [
        ['Best for', 'Ready-to-buy leads', 'New audiences and products', 'Awareness and retargeting'],
        ['Targeting', 'Keywords and intent', 'Interests, behaviour, job title', 'Audiences and placements'],
        ['Typical cost', 'Higher CPC, high intent', 'Lower CPM, broad reach', 'Lowest CPM, large reach'],
        ['Key metric', 'Cost per lead', 'Cost per result, ROAS', 'Reach, views, assisted sales'],
      ],
      note: 'Most businesses get the best return by combining search for demand with social and display for growth.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      eyebrow: 'Investment',
      heading: 'How Much Does Digital Advertising Cost?',
      intro: 'UK management fees typically range from about £500 to £3,000+ per month, plus your ad spend. Your quote depends on:',
      cards: [
        { icon: 'lucide:layers', title: 'Number of channels', text: 'One platform or a full cross-channel mix.' },
        { icon: 'lucide:wallet', title: 'Ad spend', text: 'Bigger budgets need more campaigns and testing.' },
        { icon: 'lucide:image', title: 'Creative needs', text: 'Whether we produce ad images and video.' },
        { icon: 'lucide:layout-template', title: 'Landing pages', text: 'New pages built for your campaigns.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      eyebrow: 'Client reviews',
      heading: 'What Our Advertising Clients Say',
      reviews: [
        { name: 'Sophie L', role: 'Owner, Fashion Brand', text: 'TikTok and Meta ads took us from local to national, with ROAS above 4x every month.' },
        { name: 'Ahmed R', role: 'Director, Training Provider', text: 'One team handles Google, LinkedIn and retargeting, and the leads are better than ever.' },
        { name: 'Kate J', role: 'Marketing Manager, Leisure', text: 'Their creative testing found an ad angle that doubled our bookings.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      eyebrow: 'Industries we serve',
      heading: 'Digital Advertising for Your Industry',
      items: [
        { slug: 'e-commerce', text: 'Catalogue, Shopping and retargeting ads that drive profitable sales.' },
        { slug: 'education', text: 'Enrolment campaigns targeting students and parents.' },
        { slug: 'travel', text: 'Seasonal campaigns that fill holidays and experiences.' },
        { slug: 'automotive', text: 'Stock, finance and test-drive campaigns for dealers.' },
        { slug: 'hospitality-hotels', text: 'Local and social ads that fill rooms and tables.' },
        { slug: 'technology-saas', text: 'Trial and demo campaigns across search, LinkedIn and YouTube.' },
      ],
    },
  ],
  faqs: [
    { q: 'Which advertising channel is best for my business?', a: 'It depends on your goal and audience. Search ads suit people ready to buy, social ads find new customers by interests, and display and video build awareness. We recommend a mix based on your margins, budget and past results.' },
    { q: 'How much should I spend on digital ads?', a: 'Many UK small businesses start with £1,000 to £5,000 per month across channels. We set a budget from your target cost per lead or ROAS so spend is tied to results.' },
    { q: 'Do you create the ads as well?', a: 'Yes. We write copy and produce static, carousel and video creative, and we test new versions every week.' },
    { q: 'What is retargeting?', a: 'Retargeting shows ads to people who have already visited your website or engaged with your brand, reminding them to come back and buy. It is often the lowest-cost source of sales.' },
    { q: 'How do you track results across channels?', a: 'We set up pixels, the Meta Conversions API, Google tags and GA4 so leads and sales are tracked accurately, then report cost per result for every channel.' },
    { q: 'Do I keep my ad accounts?', a: 'Yes. Your ad accounts, pixels and data always belong to your business.' },
    { q: 'Do you need a contract?', a: 'No. We work on rolling monthly terms.' },
  ],
  related: ['google-ads', 'paid-media', 'facebook-marketing', 'tiktok-marketing', 'linkedin-marketing', 'conversion-rate-optimization'],
};

export default content;
