import type { ServiceContent } from '../types';

// Entity map: digital marketing -> SEO (local, ecommerce, AEO/GEO), PPC (Google Ads, Microsoft
// Ads), paid media, digital advertising, content marketing, link building, online reputation
// management, marketing funnel (awareness, consideration, conversion), channel mix, budget,
// GA4, attribution, cost per acquisition (CPA), ROAS, marketing ROI, conversion rate.

const content: ServiceContent = {
  slug: 'digital-marketing',
  short: 'Digital Marketing',
  metaTitle: 'Digital Marketing Agency UK | SEO, PPC & Content',
  metaDescription:
    'UK digital marketing agency combining SEO, Google Ads, paid media, content and reputation management into one plan that brings more leads and sales for less.',
  hero: {
    keyword: 'Digital Marketing',
    title: 'Digital Marketing That Brings',
    highlight: 'Real Customers',
    lead:
      'GTech Digital is a UK digital marketing agency that combines SEO, Google Ads, paid social, content marketing and online reputation management into one data-led plan that grows leads, sales and return on marketing investment.',
    motion: '/services/dm.webp',
    points: ['Free digital marketing audit', 'One plan across every channel', 'Revenue tracked, not vanity metrics'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-digital-marketing',
      nav: 'What is it',
      heading: 'What Is Digital Marketing and How Does It Work?',
      paras: [
        'Digital marketing is how you reach and win customers online, through search engines, ads, content and reviews. The best results come when channels work together: SEO builds lasting visibility, paid ads bring instant demand and content and reviews build trust.',
      ],
      bullets: [
        'Be found: SEO, local SEO and AI search visibility',
        'Be chosen: Google Ads, paid media and retargeting',
        'Be trusted: content, backlinks and online reviews',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'Digital Marketing Results and Key Statistics',
      text: 'The numbers behind the digital marketing we run for UK businesses.',
      stats: [
        { value: '£12M+', label: 'Client revenue from marketing' },
        { value: '4.8x', label: 'Average marketing ROI' },
        { value: '-38%', label: 'Average cost per acquisition' },
        { value: '+212%', label: 'Average organic traffic growth' },
      ],
    },
    {
      type: 'media',
      id: 'channels',
      nav: 'Channels',
      heading: 'Digital Marketing Channels: SEO, PPC, Social, Email and Content',
      image: '/pages/dm/channels.webp',
      alt: 'Digital marketing channels: SEO, Google Ads, paid social, content, reputation and backlinks with results',
      paras: ['Our specialists cover every major channel, working from one shared plan instead of competing for credit.'],
      bullets: ['SEO, local SEO and ecommerce SEO', 'Google Ads and paid media', 'Content and link building', 'Online reputation management'],
    },
    {
      type: 'media',
      id: 'funnel',
      nav: 'Full funnel',
      heading: 'Full-Funnel Digital Marketing Strategy: Awareness to Conversion',
      image: '/pages/dm/funnel.webp',
      alt: 'Marketing funnel from reach to visits, leads and customers with cost per acquisition and ROI',
      flip: true,
      tone: 'grey',
      paras: ['We plan for every stage of the buying journey, so people discover you, trust you and come back again.'],
      bullets: ['Awareness: search, video and social reach', 'Consideration: content, reviews and retargeting', 'Conversion: landing pages and offers', 'Loyalty: email and remarketing'],
    },
    {
      type: 'media',
      id: 'budget',
      nav: 'Budget',
      heading: 'Digital Marketing Budget and Channel Mix Planning',
      image: '/pages/dm/budget.webp',
      alt: 'Marketing budget split across Google Ads, SEO and content, paid social, retargeting and reputation',
      paras: ['We move budget towards the channels that bring customers at the lowest cost, and away from those that do not.'],
      bullets: ['Channel mix based on your goals', 'Monthly budget reallocation', 'Test-and-scale approach', 'Seasonal planning'],
    },
    {
      type: 'media',
      id: 'reporting',
      nav: 'Reporting',
      heading: 'Marketing Tracking, Attribution and ROI Reporting',
      image: '/pages/dm/reporting.webp',
      alt: 'Revenue from marketing growing with leads, cost per acquisition and conversion rate',
      flip: true,
      tone: 'grey',
      paras: ['We track every lead and sale back to the channel that won it, so you see real return, not just clicks.'],
      bullets: ['GA4 and conversion tracking', 'Call and form tracking', 'CRM revenue reporting', 'Live dashboards'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: 'Our services',
      heading: 'What\'s Included in Our Digital Marketing Services',
      cards: [
        { icon: 'lucide:search', title: 'SEO', text: 'Rank on Google and in AI answers.' },
        { icon: 'lucide:map-pin', title: 'Local SEO', text: 'Top of Google Maps.' },
        { icon: 'lucide:shopping-bag', title: 'Ecommerce SEO', text: 'More organic sales.' },
        { icon: 'simple-icons:googleads', title: 'Google Ads', text: 'Leads and sales on demand.' },
        { icon: 'lucide:circle-dollar-sign', title: 'Paid Media', text: 'Ads across every platform.' },
        { icon: 'lucide:pen-line', title: 'Content Marketing', text: 'Content that ranks and sells.' },
        { icon: 'lucide:link', title: 'Backlinks', text: 'Authority that lifts rankings.' },
        { icon: 'lucide:star', title: 'Reputation', text: 'More five-star reviews.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our Digital Marketing Process, Step by Step',
      steps: [
        { title: 'Audit', text: 'Channels, tracking and competitors.' },
        { title: 'Plan', text: 'Goals, channels and budget.' },
        { title: 'Track', text: 'Conversions set up properly.' },
        { title: 'Launch', text: 'Campaigns and quick wins.' },
        { title: 'Optimise', text: 'Weekly tests and tweaks.' },
        { title: 'Report', text: 'Leads, sales and ROI monthly.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'Digital Marketing Case Studies and Results',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'SEO vs PPC',
      heading: 'SEO vs Google Ads: Which Do You Need?',
      columns: ['', 'SEO', 'Google Ads (PPC)'],
      rows: [
        ['Speed', 'Builds over 3 to 6 months', 'Results from day one'],
        ['Cost per click', 'Free', 'Paid for every click'],
        ['Longevity', 'Keeps working', 'Stops when spend stops'],
        ['Best for', 'Lasting, lower-cost growth', 'Instant leads and testing'],
      ],
      note: 'Most businesses get the best return from both: ads for leads now, SEO for cheaper leads later.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does Digital Marketing Cost?',
      intro: 'UK digital marketing typically ranges from about £750 to £5,000+ per month in management fees, plus any ad spend. Your quote depends on:',
      cards: [
        { icon: 'lucide:layers', title: 'Channels', text: 'How many we manage.' },
        { icon: 'lucide:users', title: 'Competition', text: 'How busy your market is.' },
        { icon: 'lucide:wallet', title: 'Ad spend', text: 'Your monthly media budget.' },
        { icon: 'lucide:pen-line', title: 'Content', text: 'Volume of content needed.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'Digital Marketing Client Reviews and Testimonials',
      reviews: [
        { name: 'Sarah K', role: 'MD, Home Services', text: 'SEO and Google Ads together now bring us over 300 enquiries a month.' },
        { name: 'Daniel R', role: 'Founder, Online Store', text: 'Our cost per sale fell by a third once all channels ran from one plan.' },
        { name: 'Linda F', role: 'Practice Manager, Clinic', text: 'Clear monthly reports that show exactly what we get for our money.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'Digital Marketing Services by Industry',
      items: [
        { slug: 'e-commerce', text: 'SEO, Shopping and paid social that sell.' },
        { slug: 'healthcare', text: 'Patient acquisition for clinics.' },
        { slug: 'real-estate', text: 'Valuation and viewing leads.' },
        { slug: 'finance', text: 'Compliant lead generation.' },
        { slug: 'hospitality-hotels', text: 'Bookings from search and social.' },
        { slug: 'b2b-marketing', text: 'Pipeline from search and LinkedIn.' },
      ],
    },
  ],
  faqs: [
    { q: 'What does a digital marketing agency do?', a: 'A digital marketing agency plans and runs your online marketing, such as SEO, Google Ads, paid social, content and reputation management, and reports on the leads and sales it brings.' },
    { q: 'Which digital marketing channel is best?', a: 'It depends on your goals and market. Search channels (SEO and Google Ads) usually suit businesses people actively search for, while social suits brands that create demand. We recommend a mix after an audit.' },
    { q: 'How long does digital marketing take to work?', a: 'Google Ads can bring leads within days. SEO and content usually show strong results in 3 to 6 months and keep growing after that. We set realistic milestones for each channel so you know what to expect and when.' },
    { q: 'How much should I spend on digital marketing?', a: 'Many UK small businesses spend 5 to 10% of revenue on marketing. We help you start at a level you are comfortable with and scale what works.' },
    { q: 'How do you measure results?', a: 'We track leads, sales, cost per acquisition and return on investment through GA4, call tracking and your CRM. A monthly dashboard shows what each channel earned, so budget moves towards what actually grows revenue.' },
    { q: 'Do you work with small businesses?', a: 'Yes. We work with start-ups, local businesses and larger brands, with plans to suit each budget. Smaller businesses often start with one or two channels, such as local SEO and Google Ads, then scale what works.' },
    { q: 'Do you need a contract?', a: 'No. GTech Digital runs digital marketing on rolling monthly terms, because results should keep clients, not contracts. You keep ownership of your ad accounts, analytics and data.' },
    { q: 'How do SEO and PPC work together?', a: 'SEO and PPC work best as one plan. Google Ads gives fast leads and data about which keywords convert, while SEO builds lasting traffic. We share that data between channels, manage your Google Business Profile and Meta ads, and report on the whole picture.' },
  ],
  related: ['search-engine-optimization', 'google-ads', 'local-seo', 'content-marketing', 'paid-media', 'reputation-management'],
};

export default content;
