import type { ServiceContent } from '../types';

// Entity map: ecommerce development -> online store, Shopify and Shopify Plus, WooCommerce, Adobe
// Commerce (Magento), headless commerce, product catalogue, categories and filters, product pages,
// basket and checkout, payment gateways (Stripe, PayPal, Apple Pay, Klarna), shipping (Royal Mail,
// DPD), UK VAT, stock/ERP/accounting integrations (Xero), email (Klaviyo), conversion rate, AOV.

const content: ServiceContent = {
  slug: 'ecommerce-development',
  short: 'Ecommerce Development',
  metaTitle: 'Ecommerce Website Development UK | Shopify & WooCommerce | GTech Digital',
  metaDescription:
    'UK ecommerce development agency building Shopify, WooCommerce and custom online stores with fast product pages, simple checkout and integrations that save time.',
  hero: {
    keyword: 'Ecommerce Development',
    title: 'Ecommerce Website Development',
    highlight: 'That Sells',
    lead:
      'GTech Digital builds ecommerce websites for UK brands on Shopify, WooCommerce and custom platforms, with fast product pages, simple checkout, secure payments and integrations for stock, shipping and accounting.',
    motion: '/services/ecommerce.webp',
    points: ['Free store review', 'Built for mobile shoppers', 'SEO-ready from launch'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-ecommerce-development',
      nav: 'What is it',
      heading: 'What Is Ecommerce Development and How Does It Work?',
      paras: [
        'Ecommerce development is building the online store that sells your products: the catalogue, product pages, basket, checkout and the systems behind them. A well-built store loads fast, is easy to shop on mobile and runs smoothly with your stock, payments and delivery.',
      ],
      bullets: [
        'Storefront: product, category and search experience',
        'Checkout: fast payments with Apple Pay, Google Pay and Klarna',
        'Operations: stock, shipping, accounting and email integrations',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'Ecommerce Development Results and Key Statistics',
      text: 'The numbers behind the online stores we build for UK brands.',
      stats: [
        { value: '60+', label: 'Online stores launched' },
        { value: '+48%', label: 'Average conversion rate lift' },
        { value: '-24%', label: 'Average basket abandonment' },
        { value: '£12M+', label: 'Annual client online revenue' },
      ],
    },
    {
      type: 'media',
      id: 'storefront',
      nav: 'Storefront',
      heading: 'Ecommerce Store Design, Category and Product Pages',
      image: '/pages/ecommerce/store.webp',
      alt: 'Product page annotated with search, title and price, gallery, reviews, delivery info and add to basket',
      paras: ['Shoppers decide in seconds. We design clear product pages with great images, reviews, delivery details and a strong add to basket.'],
      bullets: ['Category pages with smart filters', 'Product pages built for mobile', 'Fast search and recommendations', 'Reviews and trust signals'],
    },
    {
      type: 'media',
      id: 'platforms',
      nav: 'Platforms',
      heading: 'Shopify, WooCommerce and Custom Ecommerce Platforms',
      image: '/pages/ecommerce/platforms.webp',
      alt: 'Ecommerce platforms compared: Shopify, WooCommerce, Adobe Commerce, custom, B2B portal and multi-store',
      flip: true,
      tone: 'grey',
      paras: ['We build on the platform that fits your range, budget and growth plans, and migrate your products, customers and orders safely.'],
      bullets: ['Shopify and Shopify Plus', 'WooCommerce on WordPress', 'Custom and headless commerce', 'B2B trade portals'],
    },
    {
      type: 'media',
      id: 'checkout',
      nav: 'Checkout',
      heading: 'Ecommerce Checkout Optimisation and Basket Abandonment',
      image: '/pages/ecommerce/checkout.webp',
      alt: 'Checkout funnel from store visits to orders with conversion rate, one-click payments and lower abandonment',
      paras: ['Every extra step loses sales. We simplify checkout, add express payments and recover abandoned baskets automatically.'],
      bullets: ['Apple Pay, Google Pay and PayPal', 'Klarna and Clearpay options', 'Guest checkout and address lookup', 'Abandoned basket emails'],
    },
    {
      type: 'media',
      id: 'integrations',
      nav: 'Integrations',
      heading: 'Ecommerce Payment Gateways, Inventory and Shipping Integrations',
      image: '/pages/ecommerce/integrations.webp',
      alt: 'Store connected to Stripe, PayPal, Xero, Royal Mail and DPD, email marketing and stock systems',
      flip: true,
      tone: 'grey',
      paras: ['We connect your store to payments, accounts, couriers and stock so orders are processed without copying data by hand.'],
      bullets: ['Xero and QuickBooks', 'Royal Mail, DPD and Evri', 'ERP and stock sync', 'Klaviyo email and SMS'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our Ecommerce Development Services',
      cards: [
        { icon: 'lucide:search', title: 'Store Review', text: 'Conversion and speed audit.' },
        { icon: 'lucide:palette', title: 'Store Design', text: 'Brand-led, mobile-first UX.' },
        { icon: 'lucide:shopping-cart', title: 'Store Build', text: 'Shopify, WooCommerce or custom.' },
        { icon: 'lucide:credit-card', title: 'Payments', text: 'Express and buy-now-pay-later.' },
        { icon: 'lucide:truck', title: 'Shipping & VAT', text: 'UK and international rules.' },
        { icon: 'lucide:webhook', title: 'Integrations', text: 'Stock, accounts and couriers.' },
        { icon: 'lucide:database', title: 'Migration', text: 'Products, customers and orders.' },
        { icon: 'lucide:trending-up', title: 'SEO & Growth', text: 'Ready to rank and convert.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our Ecommerce Development Process, Step by Step',
      steps: [
        { title: 'Discover', text: 'Products, customers and goals.' },
        { title: 'Plan', text: 'Platform, structure and features.' },
        { title: 'Design', text: 'Store pages designed and approved.' },
        { title: 'Build', text: 'Store, payments and integrations.' },
        { title: 'Launch', text: 'Migration, redirects and testing.' },
        { title: 'Optimise', text: 'Testing and conversion growth.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'Ecommerce Development Case Studies and Results',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Shopify vs WooCommerce',
      heading: 'Shopify vs WooCommerce',
      columns: ['', 'Shopify', 'WooCommerce'],
      rows: [
        ['Hosting', 'Included, fully managed', 'Your own hosting'],
        ['Monthly costs', 'Plan plus app fees', 'Hosting plus plugins'],
        ['Flexibility', 'High with apps', 'Very high, full code access'],
        ['Best for', 'Fast-growing product brands', 'Content-led stores and custom needs'],
      ],
      note: 'Both work very well. We recommend one after your free store review.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does an Ecommerce Website Cost?',
      intro: 'UK ecommerce websites typically range from about £5,000 to £40,000+, depending on platform and features. Your quote depends on:',
      cards: [
        { icon: 'lucide:package', title: 'Catalogue size', text: 'Products, variants and categories.' },
        { icon: 'lucide:palette', title: 'Design', text: 'Theme-based or fully custom.' },
        { icon: 'lucide:webhook', title: 'Integrations', text: 'Systems to connect.' },
        { icon: 'lucide:database', title: 'Migration', text: 'Data from your old store.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'Ecommerce Development Client Reviews and Testimonials',
      reviews: [
        { name: 'Jess N', role: 'Founder, Fashion Label', text: 'Our new Shopify store converts almost twice as well as the old one.' },
        { name: 'Kevin A', role: 'MD, Wholesale', text: 'The B2B portal lets trade customers order 24/7 and saves our team hours.' },
        { name: 'Mei L', role: 'Owner, Homeware', text: 'Orders now flow straight into Xero and Royal Mail. No more copying data.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'Ecommerce Development Services by Industry',
      items: [
        { slug: 'e-commerce', text: 'Fashion, beauty, homeware and gifts.' },
        { slug: 'b2b-marketing', text: 'Trade portals with account pricing.' },
        { slug: 'healthcare', text: 'Supplements and pharmacy with compliant checkout.' },
        { slug: 'hospitality-hotels', text: 'Online ordering, vouchers and gift cards.' },
        { slug: 'automotive', text: 'Parts catalogues with vehicle lookup.' },
        { slug: 'education', text: 'Course sales and digital downloads.' },
      ],
    },
  ],
  faqs: [
    { q: 'Should I use Shopify or WooCommerce?', a: 'Shopify suits most growing product brands because it is managed and quick to launch. WooCommerce suits stores that need full control or already run on WordPress. We recommend one after reviewing your needs.' },
    { q: 'How long does an ecommerce website take?', a: 'Most stores take 6 to 12 weeks, depending on catalogue size, design and integrations.' },
    { q: 'Can you migrate our existing store?', a: 'Yes. We move products, customers, orders and SEO data and set up redirects so you keep your rankings.' },
    { q: 'Do you handle UK VAT and shipping?', a: 'Yes. We set up VAT, shipping zones and courier integrations for the UK and international orders.' },
    { q: 'Can we sell to trade customers too?', a: 'Yes. We build B2B features such as trade accounts, price lists and quick ordering.' },
    { q: 'Will the store be SEO-friendly?', a: 'Yes. We build clean category structures, product schema and fast pages, and can continue with ecommerce SEO after launch.' },
    { q: 'Do you support stores after launch?', a: 'Yes. We offer maintenance, conversion optimisation and new features on monthly plans.' },
  ],
  related: ['ecommerce-seo', 'website-design', 'wordpress-development', 'website-maintenance', 'google-ads', 'conversion-rate-optimization'],
};

export default content;
