import type { ServiceContent } from '../types';

// Entity map: ecommerce SEO -> category pages, product pages, site architecture, internal linking,
// faceted navigation, canonical tags, pagination, crawl budget, duplicate content, product schema
// (Product, Offer, AggregateRating), Google Merchant Center, free product listings, Google Shopping,
// image SEO, out-of-stock handling, buying guides, AI Overviews and shopping answers, organic revenue.

const content: ServiceContent = {
  slug: 'ecommerce-seo',
  short: 'Ecommerce SEO',
  metaTitle: 'Ecommerce SEO Agency UK | Shopify & WooCommerce SEO',
  metaDescription:
    'UK ecommerce SEO agency growing organic sales with category and product page optimisation, technical SEO, product schema and Google free listings.',
  hero: {
    keyword: 'Ecommerce SEO',
    title: 'Ecommerce SEO That Grows',
    highlight: 'Organic Sales',
    lead:
      'GTech Digital provides ecommerce SEO services for UK online stores, optimising category pages, product pages, technical SEO and Google Shopping feeds so products rank on Google, appear in AI answers and drive organic sales.',
    motion: '/services/ecomseo.webp',
    points: ['Free ecommerce SEO audit', 'Shopify and WooCommerce experts', 'Revenue tracked, not just rankings'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-ecommerce-seo',
      nav: 'What is it',
      heading: 'What Is Ecommerce SEO and How Does It Work?',
      paras: [
        'Ecommerce SEO helps online stores rank for the searches shoppers make before they buy. Stores have unique challenges, such as thousands of products, filters that create duplicate pages and thin product descriptions, so they need a specialist approach.',
      ],
      bullets: [
        'Category SEO: rank for high-value buying searches',
        'Product SEO: unique content, schema and images that win clicks',
        'Technical SEO: crawlable structure, filters and fast pages',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'Ecommerce SEO Results and Key Statistics',
      text: 'The numbers behind the ecommerce SEO we run for UK online stores.',
      stats: [
        { value: '+132%', label: 'Average organic order growth' },
        { value: '£184k', label: 'Average yearly organic revenue added' },
        { value: '2,860', label: 'Average ranking keywords per store' },
        { value: '+64%', label: 'Average free listing clicks' },
      ],
    },
    {
      type: 'media',
      id: 'structure',
      nav: 'Store structure',
      heading: 'Ecommerce Site Architecture and Category Page SEO',
      image: '/pages/ecom-seo/structure.webp',
      alt: 'Store structure from homepage to categories, subcategories, products and guides with SEO elements',
      paras: ['Category pages target the biggest buying searches. We plan your categories around real demand and link them so authority flows to them.'],
      bullets: ['Keyword-led category structure', 'Category copy and FAQs', 'Internal linking and breadcrumbs', 'Buying guides that support categories'],
    },
    {
      type: 'media',
      id: 'products',
      nav: 'Product pages',
      heading: 'Product Page SEO: Descriptions, Schema and Reviews',
      image: '/pages/ecom-seo/products.webp',
      alt: 'Product page annotated with keyword title, price and stock schema, images, description, reviews and related products',
      flip: true,
      tone: 'grey',
      paras: ['Copied manufacturer descriptions rarely rank. We write unique, useful product content and add the schema that shows price, stock and stars in Google.'],
      bullets: ['Unique product titles and descriptions', 'Product, Offer and review schema', 'Image alt text and file names', 'Related products and reviews'],
    },
    {
      type: 'media',
      id: 'technical',
      nav: 'Technical SEO',
      heading: 'Ecommerce Technical SEO: Faceted Navigation, Crawl Budget and Speed',
      image: '/pages/ecom-seo/technical.webp',
      alt: 'Ecommerce technical SEO checklist with faceted navigation, schema, canonicals and out-of-stock handling',
      paras: ['Filters, variants and pagination can create thousands of duplicate pages. We control them so Google crawls the pages that make money.'],
      bullets: ['Faceted navigation and canonicals', 'Pagination and crawl budget', 'Out-of-stock and discontinued products', 'Core Web Vitals on Shopify and WooCommerce'],
    },
    {
      type: 'media',
      id: 'shopping',
      nav: 'Shopping & revenue',
      heading: 'Google Shopping Free Listings, Merchant Center and Organic Revenue',
      image: '/pages/ecom-seo/revenue.webp',
      alt: 'Organic revenue growth with more organic orders, ranking keywords and free listing clicks',
      flip: true,
      tone: 'grey',
      paras: ['Your products can appear free in Google Shopping and AI shopping answers. We optimise your feed and track the revenue SEO brings.'],
      bullets: ['Google Merchant Center feed', 'Free product listings', 'AI Overviews and shopping answers', 'GA4 organic revenue tracking'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our Ecommerce SEO Services',
      cards: [
        { icon: 'lucide:search', title: 'Ecommerce Audit', text: 'Technical, content and links.' },
        { icon: 'lucide:key-round', title: 'Keyword Mapping', text: 'Buying searches to categories.' },
        { icon: 'lucide:layout-grid', title: 'Category SEO', text: 'Copy, structure and links.' },
        { icon: 'lucide:package', title: 'Product SEO', text: 'Unique content and schema.' },
        { icon: 'lucide:settings-2', title: 'Technical SEO', text: 'Filters, canonicals and speed.' },
        { icon: 'lucide:shopping-bag', title: 'Merchant Center', text: 'Feed and free listings.' },
        { icon: 'lucide:link', title: 'Link Building', text: 'PR and links to categories.' },
        { icon: 'lucide:chart-column-increasing', title: 'Revenue Reporting', text: 'Organic orders and sales.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our Ecommerce SEO Process, Step by Step',
      steps: [
        { title: 'Audit', text: 'Store, data and competitors.' },
        { title: 'Map', text: 'Keywords to categories and products.' },
        { title: 'Fix', text: 'Technical and crawl issues.' },
        { title: 'Optimise', text: 'Categories, products and feed.' },
        { title: 'Grow', text: 'Guides, links and digital PR.' },
        { title: 'Report', text: 'Organic revenue every month.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'Ecommerce SEO Case Studies and Results',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'SEO vs Shopping ads',
      heading: 'Ecommerce SEO vs Shopping Ads',
      columns: ['', 'Ecommerce SEO', 'Shopping ads'],
      rows: [
        ['Cost per click', 'Free', 'Paid for every click'],
        ['Speed', 'Builds over months', 'Immediate'],
        ['Longevity', 'Keeps working', 'Stops when budget stops'],
        ['Best for', 'Lower cost of sale over time', 'Launches and peak seasons'],
      ],
      note: 'The strongest stores run both: ads for instant sales and SEO to reduce reliance on paid clicks.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does Ecommerce SEO Cost?',
      intro: 'UK ecommerce SEO typically ranges from about £800 to £5,000+ per month. Your quote depends on:',
      cards: [
        { icon: 'lucide:package', title: 'Catalogue size', text: 'Products and categories.' },
        { icon: 'lucide:users', title: 'Competition', text: 'How crowded your market is.' },
        { icon: 'lucide:pen-line', title: 'Content', text: 'Copy and guides to create.' },
        { icon: 'lucide:link', title: 'Links', text: 'Digital PR and outreach.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'Ecommerce SEO Client Reviews and Testimonials',
      reviews: [
        { name: 'Sophie A', role: 'Founder, Beauty Store', text: 'Organic revenue more than doubled in a year and we rely far less on ads.' },
        { name: 'Daniel F', role: 'Ecommerce Director, Furniture', text: 'They fixed thousands of duplicate filter pages and our categories shot up.' },
        { name: 'Priti M', role: 'Owner, Gift Shop', text: 'Our products now show free in Google Shopping with star ratings.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'Ecommerce SEO Services by Industry',
      items: [
        { slug: 'e-commerce', text: 'Fashion, beauty, homeware and gifts.' },
        { slug: 'b2b-marketing', text: 'Trade and wholesale catalogues.' },
        { slug: 'automotive', text: 'Car parts and accessories by vehicle.' },
        { slug: 'healthcare', text: 'Supplements and health products.' },
        { slug: 'technology-saas', text: 'Electronics and software stores.' },
        { slug: 'travel', text: 'Luggage, outdoor and travel gear.' },
      ],
    },
  ],
  faqs: [
    { q: 'What is the difference between SEO and ecommerce SEO?', a: 'Ecommerce SEO focuses on category and product pages, product schema, Google Shopping and technical issues unique to stores, such as filters, variants and out-of-stock products.' },
    { q: 'Is Shopify good for SEO?', a: 'Yes, with the right setup. Shopify handles the basics well, but needs work on duplicate URLs, structure, speed and content to compete. We fix collection and product URLs and improve themes for Core Web Vitals.' },
    { q: 'Should I optimise category or product pages first?', a: 'Usually categories first. They target bigger buying searches such as "mens running shoes" and help all the products inside them rank. Once categories are strong we move on to individual product pages.' },
    { q: 'What should I do with out-of-stock products?', a: 'Keep temporarily out-of-stock pages live with a clear message, a back-in-stock sign-up and alternatives. Redirect discontinued products with a 301 to the closest match or category so link value is not lost.' },
    { q: 'How long does ecommerce SEO take?', a: 'Technical fixes can show results in weeks. Most stores see strong revenue growth within 4 to 9 months, as category and product pages climb, with the biggest gains usually arriving before peak season.' },
    { q: 'How do you measure success?', a: 'We track organic revenue, orders and conversion rate in GA4, plus rankings for your most valuable categories and products. Monthly reports show which pages earn money, not just which keywords moved.' },
    { q: 'Do you need a contract?', a: 'No. GTech Digital runs ecommerce SEO on rolling monthly terms. We recommend six months because category pages take time to climb, but you are free to stop whenever you like.' },
    { q: 'What is technical SEO for ecommerce?', a: 'Technical SEO for ecommerce means fixing the problems that stop stores ranking: faceted navigation creating duplicate pages, slow product pages, missing product schema, poor crawl paths and broken variants. Fixing these usually unlocks growth that content alone cannot.' },
  ],
  related: ['search-engine-optimization', 'ecommerce-development', 'google-ads', 'seo-backlinks', 'content-marketing', 'local-seo'],
};

export default content;
