import type { ServiceContent } from '../types';

// Entity map: Facebook marketing -> Facebook Page, Meta Business Suite, Ads Manager, lead ads,
// Advantage+ campaigns, custom and lookalike audiences, retargeting, Reels, Groups, Events,
// Messenger, recommendations/reviews, Meta Pixel, Conversions API, aggregated event measurement,
// CPM, CPC, CTR, cost per lead, ROAS, ad frequency, Meta advertising policies.

const content: ServiceContent = {
  slug: 'facebook-marketing',
  short: 'Facebook Marketing',
  metaTitle: 'Facebook Marketing Agency UK | Facebook Ads & Page Management | GTech Digital',
  metaDescription:
    'UK Facebook marketing agency: Facebook ads, lead generation, content and community management with accurate Meta Pixel and Conversions API tracking.',
  hero: {
    keyword: 'Facebook Marketing',
    title: 'Facebook Marketing That Brings',
    highlight: 'Real Customers',
    lead:
      'GTech Digital is a UK Facebook marketing agency that runs Facebook ads, lead generation campaigns and Page management, with Meta Pixel and Conversions API tracking that shows the exact cost of every lead and sale.',
    motion: '/services/facebook.webp',
    points: ['Free Facebook ads audit', 'You own your ad account', 'Clear cost-per-lead reports'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-facebook-marketing',
      nav: 'What is it',
      heading: 'What Is Facebook Marketing and How Does It Work?',
      paras: [
        'With billions of users and some of the most precise ad targeting available, Facebook remains one of the most effective places for UK businesses to find customers, especially adults over 25 and local communities.',
      ],
      bullets: [
        'Facebook ads: lead, sales and awareness campaigns in Meta Ads Manager',
        'Page and content: posts, Reels, events and offers that keep you visible',
        'Community: comments, Messenger and recommendations handled for you',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'Facebook Marketing Results and Key Statistics',
      text: 'The numbers behind the Facebook campaigns we run for UK businesses.',
      stats: [
        { value: '£8.60', label: 'Average cost per lead' },
        { value: '4.3x', label: 'Average ROAS' },
        { value: '640+', label: 'Ad creatives tested a year' },
        { value: '92%', label: 'Average event match quality' },
      ],
    },
    {
      type: 'media',
      id: 'ads',
      nav: 'Facebook ads',
      heading: 'Facebook Ads for Lead Generation and Online Sales',
      image: '/pages/facebook/ads.webp',
      alt: 'Facebook lead ad funnel from people reached to leads with cost per lead',
      paras: ['From instant lead forms to catalogue sales ads, we build campaigns around the action you want and target the people most likely to take it.'],
      bullets: ['Lead ads with CRM integration', 'Advantage+ shopping and catalogue ads', 'Lookalike and interest audiences', 'Retargeting site and video audiences'],
    },
    {
      type: 'media',
      id: 'content',
      nav: 'Page & content',
      heading: 'Facebook Page Management and Content Scheduling',
      image: '/pages/facebook/content.webp',
      alt: 'Facebook content plan with video, albums, events, reviews, offers and group posts',
      flip: true,
      tone: 'grey',
      paras: ['We plan and create posts, Reels and events that keep your Page active, useful and visible in the feed.'],
      bullets: ['Monthly content calendar', 'Reels and short video', 'Events, offers and announcements', 'Facebook Groups strategy'],
    },
    {
      type: 'media',
      id: 'community',
      nav: 'Community',
      heading: 'Facebook Community Management, Comments and Messenger',
      image: '/pages/facebook/community.webp',
      alt: 'Facebook recommendations and customer comments with owner replies',
      paras: ['Fast, friendly replies turn questions into bookings and show new visitors you care about your customers.'],
      bullets: ['Comment and Messenger replies', 'Recommendations and review responses', 'Hide spam, escalate complaints', 'Saved replies and FAQs'],
    },
    {
      type: 'media',
      id: 'tracking',
      nav: 'Tracking',
      heading: 'Meta Pixel, Conversions API and Facebook Ads Tracking',
      image: '/pages/facebook/tracking.webp',
      alt: 'Meta tracking checklist with Pixel, Conversions API and domain verification',
      flip: true,
      tone: 'grey',
      paras: ['Good data makes Facebook’s algorithm work for you. We set up the Meta Pixel and Conversions API so every lead and sale is counted.'],
      bullets: ['Meta Pixel and standard events', 'Conversions API (server-side)', 'Domain verification and event setup', 'GA4 and CRM cross-checks'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our Facebook Marketing Services',
      cards: [
        { icon: 'lucide:search', title: 'Account Audit', text: 'Ads, Page and tracking reviewed.' },
        { icon: 'lucide:users', title: 'Audience Strategy', text: 'Custom, lookalike and interest audiences.' },
        { icon: 'lucide:image', title: 'Ad Creative', text: 'Images, Reels and carousels that stop the scroll.' },
        { icon: 'lucide:pen-line', title: 'Copywriting', text: 'Hooks and offers written to convert.' },
        { icon: 'lucide:calendar-days', title: 'Page Content', text: 'Posts, Reels and events every week.' },
        { icon: 'lucide:message-square', title: 'Community', text: 'Comments and Messenger handled daily.' },
        { icon: 'lucide:settings-2', title: 'Tracking', text: 'Pixel and Conversions API set up properly.' },
        { icon: 'lucide:chart-column-increasing', title: 'Reporting', text: 'Leads, sales and cost per result.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our Facebook Marketing Process, Step by Step',
      steps: [
        { title: 'Audit', text: 'Ads account, Page and tracking reviewed.' },
        { title: 'Plan', text: 'Offers, audiences and budget agreed.' },
        { title: 'Track', text: 'Pixel and Conversions API set up.' },
        { title: 'Create', text: 'Ads and content produced.' },
        { title: 'Launch & test', text: 'New creative tested every week.' },
        { title: 'Scale & report', text: 'Budget into winners, monthly report.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'Facebook Marketing Case Studies and Results',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Campaign types',
      heading: 'Facebook Ad Campaign Types Compared',
      columns: ['', 'Lead ads', 'Sales ads', 'Awareness ads'],
      rows: [
        ['Best for', 'Service businesses', 'Ecommerce and bookings', 'Launches and local reach'],
        ['Action', 'Instant form or call', 'Purchase or booking', 'Video views and reach'],
        ['Key metric', 'Cost per lead', 'ROAS', 'Cost per thousand (CPM)'],
      ],
      note: 'We often combine awareness video with retargeted lead or sales ads for the lowest overall cost.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does Facebook Marketing Cost?',
      intro: 'UK Facebook ads management typically ranges from about £400 to £2,000+ per month, plus ad spend. Your quote depends on:',
      cards: [
        { icon: 'lucide:wallet', title: 'Ad spend', text: 'Your monthly budget on Meta.' },
        { icon: 'lucide:image', title: 'Creative volume', text: 'How many new ads we produce.' },
        { icon: 'lucide:calendar-days', title: 'Organic content', text: 'Whether Page posting is included.' },
        { icon: 'lucide:message-square', title: 'Community', text: 'Volume of comments and messages.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'Facebook Marketing Client Reviews and Testimonials',
      reviews: [
        { name: 'Gary F', role: 'Owner, Home Improvements', text: 'Lead ads now give us 40 to 60 quote requests a month at under £10 each.' },
        { name: 'Priya N', role: 'Manager, Salon', text: 'Every Messenger enquiry gets answered fast and bookings have gone up noticeably.' },
        { name: 'Ollie R', role: 'Founder, Ecommerce', text: 'After they fixed our Conversions API, our ROAS jumped and scaling finally worked.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'Facebook Marketing Services by Industry',
      items: [
        { slug: 'hospitality-hotels', text: 'Local offers and events that fill tables and rooms.' },
        { slug: 'real-estate', text: 'Valuation and viewing leads from local homeowners.' },
        { slug: 'healthcare', text: 'Policy-compliant ads for clinics and treatments.' },
        { slug: 'e-commerce', text: 'Catalogue and Advantage+ campaigns for online stores.' },
        { slug: 'automotive', text: 'Stock and finance offers for local dealers.' },
        { slug: 'education', text: 'Course and open-day campaigns for parents and adult learners.' },
      ],
    },
  ],
  faqs: [
    { q: 'Is Facebook still worth it for businesses?', a: 'Yes. Facebook has one of the largest UK audiences, particularly among adults over 25, and its ad targeting remains among the most effective for local services, ecommerce and lead generation.' },
    { q: 'How much should I spend on Facebook ads?', a: 'Many UK businesses start with £500 to £2,000 per month. We set a budget from your target cost per lead or ROAS and scale it as results prove out.' },
    { q: 'What are Facebook lead ads?', a: 'Lead ads let people submit their details through a pre-filled form without leaving Facebook. They usually produce cheaper leads, and we connect them to your CRM or email so you can follow up fast.' },
    { q: 'What is the Conversions API?', a: 'The Conversions API sends conversion data from your server to Meta, which keeps tracking accurate despite browser and iOS privacy changes. It improves both reporting and ad performance.' },
    { q: 'Do you manage our Facebook Page as well?', a: 'Yes. We can manage posting, Reels, events and community replies alongside your ads.' },
    { q: 'Do I keep ownership of my ad account?', a: 'Yes. Your Business Manager, Page, Pixel and data always belong to your business.' },
    { q: 'Do you need a contract?', a: 'No. We work on rolling monthly terms.' },
  ],
  related: ['instagram-marketing', 'tiktok-marketing', 'paid-media', 'digital-advertising', 'reputation-management', 'linkedin-marketing'],
};

export default content;
