import type { ServiceContent } from '../types';

// Entity map: Google Ads (PPC) -> Search campaigns, Performance Max, Shopping (Merchant Center),
// Display Network, YouTube ads, Demand Gen; keywords & match types, negative keywords, Quality Score,
// ad rank, CPC, CTR, conversion rate, CPA, ROAS, Smart Bidding (Target CPA / Target ROAS),
// conversion tracking (GA4, enhanced conversions, Consent Mode v2, offline conversion import).

const content: ServiceContent = {
  slug: 'google-ads',
  short: 'Google Ads',
  metaTitle: 'Google Ads Agency UK | PPC Management | GTech Digital',
  metaDescription:
    'UK Google Ads agency managing Search, Performance Max, Shopping and YouTube campaigns built around cost per lead and ROAS. Free Google Ads account audit.',
  hero: {
    title: 'Google Ads That Pay Back',
    highlight: 'Every Pound',
    lead:
      'We plan, build and manage Google Ads campaigns that bring in leads and sales at a cost you can grow on, with tracking you can trust and reporting in plain English.',
    motion: '/services/paid.webp',
    points: ['Free account audit', 'No lock-in contracts', 'You own your ad account'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-google-ads',
      nav: 'What is Google Ads',
      heading: 'What Is Google Ads Management?',
      paras: [
        'Google Ads lets your business appear at the top of Google, on YouTube, in Gmail and across millions of websites the moment people search for what you sell. You pay per click, so every pound must be spent on the right searches, with the right message, landing on the right page.',
      ],
      bullets: [
        'Search ads: text ads above Google results for high-intent keywords',
        'Performance Max & Shopping: product and lead campaigns across all Google channels',
        'Display, YouTube & Demand Gen: visual ads that build demand and retarget visitors',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'Google Ads Results in Numbers',
      text: 'The numbers behind the Google Ads accounts we manage for UK businesses.',
      stats: [
        { value: '£2.4M+', label: 'Ad spend managed' },
        { value: '4.9x', label: 'Average ROAS' },
        { value: '-38%', label: 'Average cost per lead' },
        { value: '120+', label: 'Accounts audited' },
      ],
    },
    {
      type: 'media',
      id: 'search',
      nav: 'Search ads',
      heading: 'Google Search Ads',
      image: '/pages/google-ads/search.webp',
      alt: 'Google sponsored search ad with sitelinks and performance figures',
      paras: ['We target the keywords that buyers use, exclude the ones that waste money and write ads that earn a strong Quality Score, which lowers your cost per click.'],
      bullets: ['Keyword research and match-type strategy', 'Negative keyword lists to cut waste', 'Responsive search ads and assets', 'Landing page alignment'],
    },
    {
      type: 'media',
      id: 'pmax',
      nav: 'PMax & Shopping',
      heading: 'Performance Max and Google Shopping Ads',
      image: '/pages/google-ads/pmax.webp',
      alt: 'Performance Max results across Search, Shopping, YouTube, Display, Gmail and Maps',
      flip: true,
      tone: 'grey',
      paras: ['For ecommerce and lead generation, Performance Max reaches buyers across Search, Shopping, YouTube, Display, Gmail and Maps from one campaign. We feed it the right data so it spends wisely.'],
      bullets: ['Merchant Center and product feed optimisation', 'Asset groups by product category or margin', 'Audience signals and first-party data', 'Brand exclusions and search-term insights'],
    },
    {
      type: 'media',
      id: 'display',
      nav: 'Display & YouTube',
      heading: 'Display, YouTube and Remarketing Ads',
      image: '/pages/google-ads/display.webp',
      alt: 'YouTube video ad with views, click-through and conversion figures',
      paras: ['Display, YouTube and Demand Gen campaigns put your brand in front of the right audience before they search, and remind visitors who left without buying.'],
      bullets: ['YouTube in-stream and Shorts ads', 'Responsive display and Demand Gen', 'Remarketing to site visitors and customers', 'Frequency caps and placement exclusions'],
    },
    {
      type: 'media',
      id: 'tracking',
      nav: 'Tracking',
      heading: 'Google Ads Conversion Tracking',
      image: '/pages/google-ads/tracking.webp',
      alt: 'Conversion tracking health checklist with GA4, enhanced conversions and Consent Mode',
      flip: true,
      tone: 'grey',
      paras: ['Smart Bidding is only as good as the data behind it. We set up accurate conversion tracking so Google optimises for real leads and sales, not just clicks.'],
      bullets: ['GA4 and Google Ads conversion setup', 'Enhanced conversions and Consent Mode v2', 'Call tracking and form tracking', 'Offline conversion import from your CRM'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our Google Ads Services',
      cards: [
        { icon: 'lucide:search', title: 'Account Audit', text: 'A full review of wasted spend, structure and tracking.' },
        { icon: 'lucide:target', title: 'Keyword Strategy', text: 'Profitable keywords, match types and negatives.' },
        { icon: 'lucide:pen-line', title: 'Ad Copywriting', text: 'Ads and assets written to win clicks and Quality Score.' },
        { icon: 'lucide:shopping-bag', title: 'Shopping & Feeds', text: 'Merchant Center setup and product feed optimisation.' },
        { icon: 'lucide:sparkles', title: 'Performance Max', text: 'Asset groups, audience signals and brand controls.' },
        { icon: 'lucide:layout-template', title: 'Landing Pages', text: 'Pages designed and tested to convert paid traffic.' },
        { icon: 'lucide:gauge', title: 'Bid Management', text: 'Target CPA and ROAS bidding tuned every week.' },
        { icon: 'lucide:chart-column-increasing', title: 'Reporting', text: 'Spend, leads, CPA and ROAS in one clear report.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our Google Ads Process',
      steps: [
        { title: 'Audit', text: 'We find wasted spend and missed opportunities.' },
        { title: 'Plan', text: 'Targets for cost per lead or ROAS, and the budget to hit them.' },
        { title: 'Track', text: 'Conversion tracking fixed before we spend a penny more.' },
        { title: 'Build', text: 'Campaigns, ads and landing pages built to convert.' },
        { title: 'Optimise', text: 'Weekly bids, search terms, ads and budget tuning.' },
        { title: 'Scale', text: 'More budget into what works, monthly reporting.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'Google Ads Case Studies',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Campaign types',
      heading: 'Google Ads Campaign Types Compared',
      columns: ['', 'Search', 'Performance Max', 'YouTube & Display'],
      rows: [
        ['Best for', 'High-intent leads', 'Ecommerce and scale', 'Awareness and retargeting'],
        ['Where ads show', 'Google results', 'All Google channels', 'YouTube and partner sites'],
        ['Control', 'High: keywords and ads', 'Medium: signals and assets', 'Medium: audiences and placements'],
        ['Key metric', 'Cost per lead', 'ROAS', 'Views, reach, assisted sales'],
      ],
      note: 'Most accounts perform best with Search for demand capture and Performance Max or YouTube for growth.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does Google Ads Management Cost?',
      intro: 'UK management fees typically run from about £300 to £2,000+ per month, or 10 to 20% of ad spend for larger accounts. Your fee depends on:',
      cards: [
        { icon: 'lucide:wallet', title: 'Monthly ad spend', text: 'Larger budgets need more campaigns and testing.' },
        { icon: 'lucide:layers', title: 'Campaign types', text: 'Search only, or Search plus PMax, Shopping and YouTube.' },
        { icon: 'lucide:shopping-bag', title: 'Product range', text: 'Feed size and catalogue complexity for ecommerce.' },
        { icon: 'lucide:layout-template', title: 'Landing pages', text: 'Whether new or improved pages are needed.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'Google Ads Client Reviews',
      reviews: [
        { name: 'Sarah M', role: 'Marketing Manager, Retail', text: 'They rebuilt our Shopping and PMax campaigns and our ROAS went from 2.1x to 5.4x in four months.' },
        { name: 'Daniel R', role: 'Owner, Home Services', text: 'Our cost per lead halved after they fixed the tracking and cut the wasted keywords.' },
        { name: 'Emma W', role: 'Director, Training Company', text: 'Clear weekly updates and real numbers. For the first time we know exactly what our ads return.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'Google Ads for Your Industry',
      items: [
        { slug: 'e-commerce', text: 'Shopping and Performance Max campaigns tuned for profit, not just revenue.' },
        { slug: 'hospitality-hotels', text: 'Direct booking campaigns that beat the commission of booking sites.' },
        { slug: 'healthcare', text: 'Policy-compliant ads for clinics and private healthcare providers.' },
        { slug: 'real-estate', text: 'Valuation and viewing leads for estate and letting agents.' },
        { slug: 'automotive', text: 'Vehicle listing ads and test-drive leads for dealers.' },
        { slug: 'b2b-marketing', text: 'High-value B2B leads with offline conversion tracking from your CRM.' },
      ],
    },
  ],
  faqs: [
    { q: 'How much should I spend on Google Ads?', a: 'It depends on your market and goals. Many UK small businesses start with £1,000 to £3,000 per month in ad spend. We work out a budget from your target cost per lead and expected conversion rate, so you know what to expect before you spend.' },
    { q: 'How quickly will I see results?', a: 'Search ads can bring traffic and leads from the day they go live. Campaigns usually take 4 to 8 weeks to optimise fully as bidding learns and we refine keywords, ads and landing pages.' },
    { q: 'What is a good ROAS for Google Ads?', a: 'It depends on your margins. Many ecommerce businesses need 3x to 5x to be profitable, while high-margin services can grow well below that. We set your target from your actual profit, not an industry average.' },
    { q: 'What is Performance Max?', a: 'Performance Max is a Google Ads campaign type that uses automation to show your ads across Search, Shopping, YouTube, Display, Gmail and Maps from one campaign. It works best with good product data, strong assets and accurate conversion tracking.' },
    { q: 'Do I own my Google Ads account?', a: 'Yes. Your account, data and campaigns always belong to you. We manage it with access you grant and can hand everything over at any time.' },
    { q: 'Why is my Google Ads cost per click so high?', a: 'High CPCs usually come from broad targeting, low Quality Score, competitive keywords or poor landing pages. Improving ad relevance and landing page experience often lowers what you pay per click.' },
    { q: 'Do you need a contract?', a: 'No. We work on rolling monthly terms, because results should keep clients, not contracts.' },
  ],
  related: ['search-engine-optimization', 'paid-media', 'digital-advertising', 'conversion-rate-optimization', 'ecommerce-development', 'content-marketing'],
};

export default content;
