import type { ServiceContent } from '../types';

// Entity map: Instagram marketing -> Instagram profile, Reels, Stories, carousels, Highlights,
// Instagram Shopping (product tags, shop), Instagram ads (Meta Ads Manager), Collab posts,
// influencers and creators, UGC, hashtags and keyword captions (Instagram SEO), saves and shares,
// engagement rate, reach, follower growth, Instagram Insights, DMs and broadcast channels.

const content: ServiceContent = {
  slug: 'instagram-marketing',
  short: 'Instagram Marketing',
  metaTitle: 'Instagram Marketing Agency UK | Reels, Ads & Influencers | GTech Digital',
  metaDescription:
    'UK Instagram marketing agency creating Reels, Stories and ads, managing creators and Instagram Shopping to grow engaged followers and online sales.',
  hero: {
    keyword: 'Instagram Marketing',
    title: 'Instagram Marketing That',
    highlight: 'Grows Sales',
    lead:
      'GTech Digital is a UK Instagram marketing agency that creates Reels, Stories and carousels, runs Instagram ads and Shopping, and manages influencer campaigns that grow engaged followers and online sales.',
    motion: '/services/instagram.webp',
    points: ['Free profile audit', 'Reels made for you', 'Monthly growth report'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-instagram-marketing',
      nav: 'What is it',
      heading: 'What Is Instagram Marketing and How Does It Work?',
      paras: [
        'Instagram is where people discover brands, check them out before buying and shop straight from posts. Winning there takes consistent, visual, short-form content and a clear path from follower to customer.',
      ],
      bullets: [
        'Content: Reels, carousels and Stories built for reach and saves',
        'Growth: creators, Collab posts and ads that bring new followers',
        'Sales: Instagram Shopping, DMs and shoppable ads that convert',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'Instagram Marketing Results and Key Statistics',
      text: 'The numbers behind the Instagram accounts we grow for UK brands.',
      stats: [
        { value: '+18k', label: 'Average followers gained a year' },
        { value: '7.2%', label: 'Average engagement rate' },
        { value: '4.6x', label: 'Average Instagram ad ROAS' },
        { value: '1,100+', label: 'Reels produced' },
      ],
    },
    {
      type: 'media',
      id: 'reels',
      nav: 'Reels & content',
      heading: 'Instagram Reels, Stories and Carousel Content',
      image: '/pages/instagram/reels.webp',
      alt: 'Instagram Reel with views, click-through and conversion figures',
      paras: ['Reels reach people who do not follow you yet. We plan, script and edit short videos with strong hooks, plus carousels and Stories that keep followers engaged.'],
      bullets: ['Reels scripting, filming and editing', 'Carousels and branded graphics', 'Stories, polls and Highlights', 'Captions with search keywords'],
    },
    {
      type: 'media',
      id: 'ads',
      nav: 'Ads & Shopping',
      heading: 'Instagram Ads and Instagram Shopping',
      image: '/pages/instagram/ads.webp',
      alt: 'Instagram shop revenue growing with ROAS, click-through and orders',
      flip: true,
      tone: 'grey',
      paras: ['We tag products, set up your shop and run Reels, Story and catalogue ads so browsing becomes buying.'],
      bullets: ['Instagram Shopping and product tags', 'Reels and Story ads', 'Catalogue and retargeting ads', 'DM automation for enquiries'],
    },
    {
      type: 'media',
      id: 'creators',
      nav: 'Creators',
      heading: 'Instagram Influencer Marketing and UGC Campaigns',
      image: '/pages/instagram/creators.webp',
      alt: 'Brand connected to lifestyle, food, fitness, fashion, home and local creators',
      paras: ['Authentic creator content builds trust faster than brand posts. We find, brief and manage creators who genuinely fit your audience.'],
      bullets: ['Creator search and vetting', 'Briefs, contracts and approvals', 'Collab posts and UGC for ads', 'ASA-compliant #ad disclosures'],
    },
    {
      type: 'media',
      id: 'growth',
      nav: 'Growth',
      heading: 'Instagram Analytics, Engagement and Follower Growth',
      image: '/pages/instagram/growth.webp',
      alt: 'Instagram follower growth with engagement rate, saves and shares',
      flip: true,
      tone: 'grey',
      paras: ['We track what drives reach, saves and sales, then double down on it every month.'],
      bullets: ['Instagram Insights and GA4 tracking', 'Best time and format testing', 'Competitor benchmarking', 'Monthly growth report'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our Instagram Marketing Services',
      cards: [
        { icon: 'lucide:search', title: 'Profile Audit', text: 'Bio, grid, Highlights and performance reviewed.' },
        { icon: 'lucide:video', title: 'Reels Production', text: 'Scripts, filming guidance and editing.' },
        { icon: 'lucide:images', title: 'Carousels & Graphics', text: 'Branded designs people save and share.' },
        { icon: 'lucide:calendar-days', title: 'Content Calendar', text: 'A month of posts planned ahead.' },
        { icon: 'lucide:shopping-bag', title: 'Instagram Shopping', text: 'Shop setup and product tagging.' },
        { icon: 'lucide:users', title: 'Creators & UGC', text: 'Influencer campaigns managed end to end.' },
        { icon: 'lucide:message-square', title: 'Community & DMs', text: 'Comments and messages answered.' },
        { icon: 'lucide:chart-column-increasing', title: 'Reporting', text: 'Followers, engagement and sales.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our Instagram Marketing Process, Step by Step',
      steps: [
        { title: 'Audit', text: 'Profile, content and competitors reviewed.' },
        { title: 'Strategy', text: 'Content pillars, style and goals.' },
        { title: 'Create', text: 'Reels, carousels and Stories produced.' },
        { title: 'Publish', text: 'Posted at the best times for your audience.' },
        { title: 'Amplify', text: 'Creators and ads extend your reach.' },
        { title: 'Report', text: 'Monthly insights and next steps.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'Instagram Marketing Case Studies and Results',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Formats',
      heading: 'Instagram Reels vs Carousels vs Stories',
      columns: ['', 'Reels', 'Carousels', 'Stories'],
      rows: [
        ['Best for', 'Reaching new people', 'Saves and education', 'Daily connection and offers'],
        ['Lifespan', 'Weeks of discovery', 'Days, resurfaced by saves', '24 hours (or Highlights)'],
        ['Key metric', 'Reach and shares', 'Saves', 'Replies and link taps'],
      ],
      note: 'A healthy mix is roughly half Reels, a third carousels and daily Stories.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does Instagram Marketing Cost?',
      intro: 'UK Instagram management typically ranges from about £500 to £3,000+ per month, plus ads or creator fees. Your quote depends on:',
      cards: [
        { icon: 'lucide:video', title: 'Reels volume', text: 'How many videos per month.' },
        { icon: 'lucide:camera', title: 'Production', text: 'Shoots, editing and design needs.' },
        { icon: 'lucide:users', title: 'Creators', text: 'Influencer and UGC campaigns.' },
        { icon: 'lucide:wallet', title: 'Ad spend', text: 'Budget for Instagram ads.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'Instagram Marketing Client Reviews and Testimonials',
      reviews: [
        { name: 'Chloe M', role: 'Founder, Skincare Brand', text: 'Our Reels regularly reach 100k people and Instagram is now our top sales channel.' },
        { name: 'Sam T', role: 'Owner, Restaurant', text: 'They film, edit and post everything. Weekend bookings from Instagram have doubled.' },
        { name: 'Ella K', role: 'Marketing Lead, Fashion', text: 'Their creator campaigns brought us content and customers we could never have reached alone.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'Instagram Marketing Services by Industry',
      items: [
        { slug: 'e-commerce', text: 'Shoppable Reels and creators that sell products.' },
        { slug: 'hospitality-hotels', text: 'Food, venue and room content that drives bookings.' },
        { slug: 'healthcare', text: 'Aesthetics and wellness content that builds trust.' },
        { slug: 'travel', text: 'Destination Reels that inspire trips.' },
        { slug: 'real-estate', text: 'Property tours and area guides that win instructions.' },
        { slug: 'education', text: 'Campus life and course content for students.' },
      ],
    },
  ],
  faqs: [
    { q: 'How do I grow on Instagram in 2026?', a: 'Post Reels consistently with a strong hook in the first second, use carousels to earn saves, write captions with the keywords people search for, and engage with your community. Creator partnerships and ads speed up growth.' },
    { q: 'How often should we post on Instagram?', a: 'Most brands do well with 3 to 5 feed posts a week, at least half of them Reels, plus Stories most days.' },
    { q: 'Do you film the Reels?', a: 'We script and edit Reels, and can either guide your team to film on a phone or organise professional and creator shoots.' },
    { q: 'Do influencer posts need to be labelled?', a: 'Yes. UK advertising rules require paid or gifted content to be clearly labelled, for example with #ad. We manage disclosures for every campaign.' },
    { q: 'Can we sell directly on Instagram?', a: 'Yes. With Instagram Shopping you can tag products in posts and Reels so people can browse and buy through your shop.' },
    { q: 'How do you measure Instagram results?', a: 'We track reach, engagement, saves, followers and, through tracking links and GA4, the traffic, leads and sales Instagram drives.' },
    { q: 'Do you need a contract?', a: 'No. We work on rolling monthly terms.' },
  ],
  related: ['facebook-marketing', 'tiktok-marketing', 'pinterest-marketing', 'content-marketing', 'paid-media', 'branding'],
};

export default content;
