import type { ServiceContent } from '../types';

// Entity map: Laravel development -> Laravel 11, Eloquent ORM, Blade, Livewire, Inertia with Vue or
// React, Filament admin panels, Laravel Sanctum and Passport (API auth), queues and Horizon,
// scheduler, events, Scout search, Cashier (Stripe billing), Forge and Vapor deployment, Pest and
// PHPUnit testing, Larastan, multi-tenancy, SaaS, REST APIs, Redis, MySQL, CI/CD.

const content: ServiceContent = {
  slug: 'laravel-development',
  short: 'Laravel Development',
  metaTitle: 'Laravel Development Company UK | Web Apps, APIs & SaaS | GTech Digital',
  metaDescription:
    'UK Laravel development company building secure web applications, admin panels, APIs and SaaS platforms with Laravel 11, Livewire and Filament.',
  hero: {
    eyebrow: 'Laravel Development Company UK',
    title: 'Laravel Applications That',
    highlight: 'Scale With You',
    lead:
      'We build secure, well-tested Laravel web apps, portals and APIs that automate your work and grow with your business, from first release to thousands of users.',
    motion: '/services/laravel.webp',
    points: ['Free technical consultation', 'Fixed-scope sprints', 'Tested, documented code'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-laravel-development',
      nav: 'What is it',
      eyebrow: 'The basics',
      heading: 'What Is Laravel Development?',
      paras: [
        'Laravel is the most popular PHP framework for building web applications. It comes with secure authentication, queues, APIs and testing built in, so we spend your budget on features that matter instead of reinventing the basics.',
      ],
      bullets: [
        'Web apps: portals, dashboards and booking systems',
        'APIs: secure back ends for mobile apps and integrations',
        'SaaS: multi-tenant platforms with subscription billing',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      eyebrow: 'Results in numbers',
      heading: 'Laravel Built for the Long Run',
      text: 'The numbers behind the Laravel applications we build and support.',
      stats: [
        { value: '50+', label: 'Laravel apps delivered' },
        { value: '95ms', label: 'Average median response' },
        { value: '88%', label: 'Average test coverage' },
        { value: '11h', label: 'Admin time saved per week' },
      ],
    },
    {
      type: 'media',
      id: 'applications',
      nav: 'Web apps',
      eyebrow: 'Web applications',
      heading: 'Apps That Automate Your Work',
      image: '/pages/laravel/apps.webp',
      alt: 'Laravel application layers: interface, Laravel core, background jobs, data and deployment',
      paras: ['We turn spreadsheets and manual steps into fast, secure web apps your team and customers enjoy using.'],
      bullets: ['Customer and partner portals', 'Livewire and Inertia interfaces', 'Queues, events and scheduling', 'Role-based access control'],
    },
    {
      type: 'media',
      id: 'apis',
      nav: 'APIs',
      eyebrow: 'APIs',
      heading: 'Secure APIs for Apps and Partners',
      image: '/pages/laravel/api.webp',
      alt: 'Laravel API controller code with endpoints, median response and OAuth 2 security',
      flip: true,
      tone: 'grey',
      paras: ['We build documented REST APIs that power mobile apps, partner integrations and your own front end.'],
      bullets: ['Sanctum and Passport authentication', 'Versioned, documented endpoints', 'Rate limiting and validation', 'Webhooks and third-party APIs'],
    },
    {
      type: 'media',
      id: 'admin',
      nav: 'Admin panels',
      eyebrow: 'Admin & back office',
      heading: 'Back Offices That Save Hours',
      image: '/pages/laravel/admin.webp',
      alt: 'Orders processed chart with one admin panel, staff users and admin time saved',
      paras: ['We build Filament admin panels that let staff manage orders, customers and content in one clear place.'],
      bullets: ['Filament admin panels', 'Reports and CSV exports', 'Approval workflows', 'Audit logs for every change'],
    },
    {
      type: 'media',
      id: 'quality',
      nav: 'Quality',
      eyebrow: 'Quality & DevOps',
      heading: 'Tested Code, Safe Releases',
      image: '/pages/laravel/quality.webp',
      alt: 'Laravel quality checklist with Pest tests, Larastan, CI pipeline and staging',
      flip: true,
      tone: 'grey',
      paras: ['Every feature ships with automated tests and goes through a CI pipeline and staging before it reaches your users.'],
      bullets: ['Pest and PHPUnit tests', 'Larastan static analysis', 'CI/CD on every commit', 'Forge or Vapor hosting'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      eyebrow: 'Our Laravel service',
      heading: 'Everything Included',
      cards: [
        { icon: 'lucide:search', title: 'Discovery', text: 'Requirements and technical plan.' },
        { icon: 'lucide:pen-tool', title: 'UX Design', text: 'Screens designed before code.' },
        { icon: 'lucide:app-window', title: 'Web App Build', text: 'Livewire or Inertia front ends.' },
        { icon: 'lucide:webhook', title: 'API Development', text: 'Secure, documented APIs.' },
        { icon: 'lucide:layout-dashboard', title: 'Admin Panels', text: 'Filament back offices.' },
        { icon: 'lucide:credit-card', title: 'Billing', text: 'Stripe subscriptions via Cashier.' },
        { icon: 'lucide:flask-conical', title: 'Testing', text: 'Pest tests and code review.' },
        { icon: 'lucide:server', title: 'Hosting & Support', text: 'Deployment and monitoring.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      eyebrow: 'How we work',
      heading: 'Our Laravel Process',
      steps: [
        { title: 'Discover', text: 'Goals, users and workflows.' },
        { title: 'Design', text: 'Wireframes and data model.' },
        { title: 'Sprint', text: 'Two-week builds with demos.' },
        { title: 'Test', text: 'Automated and user acceptance.' },
        { title: 'Launch', text: 'Zero-downtime deployment.' },
        { title: 'Evolve', text: 'New features and support.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      eyebrow: 'Laravel case studies',
      heading: 'Laravel Projects We Have Delivered',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Laravel vs others',
      eyebrow: 'Compare',
      heading: 'Laravel vs Off-the-Shelf Software',
      columns: ['', 'Custom Laravel app', 'Off-the-shelf SaaS'],
      rows: [
        ['Fit to your process', 'Exact', 'You adapt to the tool'],
        ['Cost over time', 'No per-user fees', 'Monthly fees per user'],
        ['Ownership', 'You own the code and data', 'Vendor owns the platform'],
        ['Time to start', 'Weeks to months', 'Days'],
      ],
      note: 'Custom software makes sense when off-the-shelf tools force workarounds or costly per-user fees.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      eyebrow: 'Investment',
      heading: 'How Much Does Laravel Development Cost?',
      intro: 'UK Laravel projects typically range from about £8,000 for an MVP to £60,000+ for larger platforms. Your quote depends on:',
      cards: [
        { icon: 'lucide:puzzle', title: 'Features', text: 'Screens, roles and workflows.' },
        { icon: 'lucide:webhook', title: 'Integrations', text: 'Systems and APIs to connect.' },
        { icon: 'lucide:users', title: 'Scale', text: 'Users, data and performance.' },
        { icon: 'lucide:shield-check', title: 'Security', text: 'Compliance and audit needs.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      eyebrow: 'Client reviews',
      heading: 'What Our Laravel Clients Say',
      reviews: [
        { name: 'Ben R', role: 'COO, Recruitment', text: 'Our Laravel portal replaced five spreadsheets and saves the team hours every week.' },
        { name: 'Nadia K', role: 'Founder, SaaS Start-up', text: 'They took us from idea to paying customers in under four months.' },
        { name: 'Chris D', role: 'CTO, Logistics', text: 'Excellent code quality. Our in-house team picked it up with no trouble.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      eyebrow: 'Industries we serve',
      heading: 'Laravel Development for Your Industry',
      items: [
        { slug: 'technology-saas', text: 'Multi-tenant SaaS with subscription billing.' },
        { slug: 'finance', text: 'Secure client portals and calculators.' },
        { slug: 'healthcare', text: 'Booking, records and patient portals.' },
        { slug: 'education', text: 'Course, enrolment and learning platforms.' },
        { slug: 'real-estate', text: 'Property management and tenant portals.' },
        { slug: 'travel', text: 'Booking engines and supplier integrations.' },
      ],
    },
  ],
  faqs: [
    { q: 'Why choose Laravel for a web application?', a: 'Laravel gives a secure, well-tested foundation with authentication, queues, APIs and testing built in. That means faster development and code any PHP developer can maintain.' },
    { q: 'Is Laravel good for SaaS?', a: 'Yes. Laravel handles multi-tenancy, subscription billing with Stripe, background jobs and APIs very well, which is why many UK SaaS products use it.' },
    { q: 'Can Laravel handle high traffic?', a: 'Yes. With caching, queues and the right hosting, Laravel applications serve thousands of users and millions of requests.' },
    { q: 'Can you take over an existing Laravel project?', a: 'Yes. We review the code, upgrade Laravel and PHP versions if needed and then continue development.' },
    { q: 'Do you build the front end too?', a: 'Yes. We use Livewire, Inertia with Vue or React, or a separate Next.js front end depending on the project.' },
    { q: 'How do you price Laravel projects?', a: 'We estimate each phase from a clear scope, usually as fixed-price sprints, so you know the cost before work starts.' },
    { q: 'Who owns the code?', a: 'You do. We hand over the full source code and documentation.' },
  ],
  related: ['php-development', 'web-application-development', 'saas-product-development', 'api-system-integration', 'mvp-development', 'website-maintenance'],
};

export default content;
