import type { ServiceContent } from '../types';

// Entity map: LinkedIn marketing -> Company Page, Showcase Pages, personal profiles, thought
// leadership, document posts, newsletters, LinkedIn Live, employee advocacy, LinkedIn Ads
// (Campaign Manager), Sponsored Content, Lead Gen Forms, Conversation/Message Ads, Thought
// Leader Ads, matched audiences, account-based marketing (ABM), job title and company targeting,
// Insight Tag, Conversions API, CRM sync, pipeline, cost per lead, B2B sales cycle.

const content: ServiceContent = {
  slug: 'linkedin-marketing',
  short: 'LinkedIn Marketing',
  metaTitle: 'LinkedIn Marketing Agency UK | B2B LinkedIn Ads & Content | GTech Digital',
  metaDescription:
    'UK LinkedIn marketing agency for B2B: thought leadership content, employee advocacy and LinkedIn Ads with Lead Gen Forms that fill your sales pipeline.',
  hero: {
    eyebrow: 'LinkedIn Marketing Agency UK',
    title: 'LinkedIn Marketing That Fills Your',
    highlight: 'Sales Pipeline',
    lead:
      'We help B2B companies reach the decision-makers that matter, with thought leadership that builds trust and LinkedIn Ads that turn it into qualified sales meetings.',
    motion: '/services/linkedin.webp',
    points: ['Free LinkedIn audit', 'Targeting by job title and company', 'Leads synced to your CRM'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-linkedin-marketing',
      nav: 'What is it',
      eyebrow: 'The basics',
      heading: 'What Is LinkedIn Marketing?',
      paras: [
        'LinkedIn is where business buyers research, network and make decisions. It lets you target by job title, seniority, company and industry, which makes it the most precise B2B marketing channel available.',
      ],
      bullets: [
        'Content: thought leadership from your company and your people',
        'Advertising: Sponsored Content, Lead Gen Forms and Thought Leader Ads',
        'ABM: campaigns aimed at the exact accounts you want to win',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      eyebrow: 'Results in numbers',
      heading: 'B2B Leads, Not Just Likes',
      text: 'The numbers behind the LinkedIn campaigns we run for UK B2B companies.',
      stats: [
        { value: '£39', label: 'Average cost per B2B lead' },
        { value: '£12M+', label: 'Pipeline influenced' },
        { value: '8x', label: 'Reach via employee posts' },
        { value: '100%', label: 'Leads synced to CRM' },
      ],
    },
    {
      type: 'media',
      id: 'content',
      nav: 'Thought leadership',
      eyebrow: 'Thought leadership',
      heading: 'Content That Makes You the Obvious Choice',
      image: '/pages/linkedin/content.webp',
      alt: 'LinkedIn content plan with articles, documents, data, video, live and newsletters',
      paras: ['We turn your expertise into posts, documents, newsletters and video that decision-makers read, share and remember.'],
      bullets: ['Company Page strategy and posting', 'Document and carousel posts', 'LinkedIn newsletters and articles', 'Video and LinkedIn Live'],
    },
    {
      type: 'media',
      id: 'ads',
      nav: 'LinkedIn ads',
      eyebrow: 'LinkedIn ads',
      heading: 'Ads That Reach the Exact Buyers You Want',
      image: '/pages/linkedin/ads.webp',
      alt: 'LinkedIn lead gen funnel from decision-makers reached to sales meetings',
      flip: true,
      tone: 'grey',
      paras: ['LinkedIn Ads are expensive per click, so precision matters. We target the right roles and accounts and use Lead Gen Forms to cut friction.'],
      bullets: ['Sponsored Content and Thought Leader Ads', 'Lead Gen Forms and Message Ads', 'Job title, seniority and company targeting', 'Account-based marketing lists'],
    },
    {
      type: 'media',
      id: 'advocacy',
      nav: 'Employee advocacy',
      eyebrow: 'Employee advocacy',
      heading: 'Your People Are Your Best Channel',
      image: '/pages/linkedin/advocacy.webp',
      alt: 'Company page reach multiplied through posts from the CEO, sales and experts',
      paras: ['Posts from real people reach far more than company posts. We help leaders and experts build their profiles with content written in their voice.'],
      bullets: ['Founder and leadership profiles', 'Ghost-written posts in your voice', 'Employee advocacy programmes', 'Profile optimisation for sales teams'],
    },
    {
      type: 'media',
      id: 'tracking',
      nav: 'Tracking',
      eyebrow: 'Lead tracking',
      heading: 'From Click to Closed Deal',
      image: '/pages/linkedin/tracking.webp',
      alt: 'B2B lead tracking checklist with Insight Tag, CRM sync and offline deal stages',
      flip: true,
      tone: 'grey',
      paras: ['B2B sales take time. We connect LinkedIn to your CRM so you can see which campaigns create meetings, pipeline and revenue.'],
      bullets: ['LinkedIn Insight Tag and Conversions API', 'Lead Gen Forms synced to HubSpot or Salesforce', 'Offline deal-stage tracking', 'Pipeline and revenue reporting'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      eyebrow: 'Our LinkedIn service',
      heading: 'Everything Included',
      cards: [
        { icon: 'lucide:search', title: 'LinkedIn Audit', text: 'Page, profiles, ads and competitors.' },
        { icon: 'lucide:target', title: 'ICP & Targeting', text: 'Your ideal customers defined precisely.' },
        { icon: 'lucide:pen-line', title: 'Thought Leadership', text: 'Posts and articles in your voice.' },
        { icon: 'lucide:user', title: 'Profile Building', text: 'Founders and experts on LinkedIn.' },
        { icon: 'lucide:megaphone', title: 'LinkedIn Ads', text: 'Sponsored Content, Lead Gen and Message Ads.' },
        { icon: 'lucide:building-2', title: 'ABM Campaigns', text: 'Ads aimed at named target accounts.' },
        { icon: 'lucide:settings-2', title: 'CRM Integration', text: 'Leads and deals tracked end to end.' },
        { icon: 'lucide:chart-column-increasing', title: 'Reporting', text: 'Leads, meetings and pipeline.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      eyebrow: 'How we work',
      heading: 'Our LinkedIn Process',
      steps: [
        { title: 'Define', text: 'Ideal customer profile and target accounts.' },
        { title: 'Audit', text: 'Page, profiles and past campaigns.' },
        { title: 'Content', text: 'Thought leadership plan and drafts.' },
        { title: 'Ads', text: 'Campaigns built with clean CRM tracking.' },
        { title: 'Nurture', text: 'Retargeting and follow-up sequences.' },
        { title: 'Report', text: 'Leads, meetings and pipeline monthly.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      eyebrow: 'LinkedIn case studies',
      heading: 'LinkedIn Results We Have Delivered',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Ad formats',
      eyebrow: 'Compare',
      heading: 'Which LinkedIn Ad Format Fits?',
      columns: ['', 'Lead Gen Forms', 'Thought Leader Ads', 'Message Ads'],
      rows: [
        ['Best for', 'Content downloads and demos', 'Trust and awareness', 'Event invites and direct offers'],
        ['Shown as', 'Sponsored post with form', 'Boosted employee post', 'Message in the inbox'],
        ['Key metric', 'Cost per lead', 'Engagement and reach', 'Open and reply rate'],
      ],
      note: 'Thought Leader Ads warm up your audience so Lead Gen Forms convert at a lower cost.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      eyebrow: 'Investment',
      heading: 'How Much Does LinkedIn Marketing Cost?',
      intro: 'UK LinkedIn management typically ranges from about £750 to £3,500+ per month, plus ad spend. Your quote depends on:',
      cards: [
        { icon: 'lucide:pen-line', title: 'Content volume', text: 'Company and personal posts per week.' },
        { icon: 'lucide:user', title: 'Profiles', text: 'How many leaders we write for.' },
        { icon: 'lucide:wallet', title: 'Ad spend', text: 'Budget for LinkedIn campaigns.' },
        { icon: 'lucide:settings-2', title: 'Integration', text: 'CRM and ABM setup needs.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      eyebrow: 'Client reviews',
      heading: 'What Our LinkedIn Clients Say',
      reviews: [
        { name: 'David K', role: 'MD, IT Services', text: 'LinkedIn now books us around 15 qualified sales meetings a month, all tracked in HubSpot.' },
        { name: 'Fiona R', role: 'Founder, Consultancy', text: 'My ghost-written posts regularly reach 50,000 people and clients mention them on calls.' },
        { name: 'Tariq A', role: 'Head of Growth, SaaS', text: 'Their ABM campaigns got us into accounts we had been chasing for years.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      eyebrow: 'Industries we serve',
      heading: 'LinkedIn Marketing for Your Industry',
      items: [
        { slug: 'b2b-marketing', text: 'Pipeline-focused LinkedIn programmes for B2B firms.' },
        { slug: 'technology-saas', text: 'Demo and trial campaigns aimed at buying committees.' },
        { slug: 'finance', text: 'Compliant thought leadership for financial firms.' },
        { slug: 'education', text: 'Executive education and corporate training campaigns.' },
        { slug: 'healthcare', text: 'Reaching NHS and private healthcare decision-makers.' },
        { slug: 'real-estate', text: 'Commercial property and investor audiences.' },
      ],
    },
  ],
  faqs: [
    { q: 'Is LinkedIn advertising worth the cost?', a: 'For B2B, usually yes. Clicks cost more than on other platforms, but the precise targeting means leads are often far more valuable. We measure success on meetings and pipeline, not just cost per click.' },
    { q: 'How much should we spend on LinkedIn Ads?', a: 'Many UK B2B companies start with £1,500 to £5,000 per month. Smaller budgets work best when focused on a tight audience and one clear offer.' },
    { q: 'Can you write posts for our CEO?', a: 'Yes. We interview your leaders, write posts in their voice and publish after their approval. It is one of the most effective ways to build trust on LinkedIn.' },
    { q: 'What are LinkedIn Lead Gen Forms?', a: 'Lead Gen Forms are pre-filled forms inside LinkedIn ads. They reduce friction and usually lower cost per lead. We sync them to your CRM so sales can follow up quickly.' },
    { q: 'What is account-based marketing on LinkedIn?', a: 'ABM targets ads at a list of named companies you want to win, and often at specific roles within them, so your budget focuses on your highest-value prospects.' },
    { q: 'How do you track LinkedIn ROI?', a: 'We use the Insight Tag, Conversions API and CRM integration to track leads through to meetings, opportunities and closed revenue.' },
    { q: 'Do you need a contract?', a: 'No. We work on rolling monthly terms.' },
  ],
  related: ['content-marketing', 'paid-media', 'marketing-advisory', 'facebook-marketing', 'search-engine-optimization', 'crm-erp-development'],
};

export default content;
