import type { ServiceContent } from '../types';

// Entity map: local SEO -> Google Business Profile (categories, services, posts, photos, Q&A),
// Google Maps, local pack (map pack), proximity, relevance and prominence, NAP consistency,
// local citations (Apple Business Connect, Bing Places, Yell), Google reviews, location pages,
// service area pages, LocalBusiness schema, "near me" searches, calls and direction requests,
// local links, AI Overviews and local answers.

const content: ServiceContent = {
  slug: 'local-seo',
  short: 'Local SEO',
  metaTitle: 'Local SEO Agency UK | Google Maps & Business Profile SEO | GTech Digital',
  metaDescription:
    'UK local SEO agency helping businesses rank in the Google map pack and local search with Google Business Profile optimisation, citations, reviews and location pages.',
  hero: {
    eyebrow: 'Local SEO Agency UK',
    title: 'Get Found First When Locals',
    highlight: 'Search Near Me',
    lead:
      'We put your business at the top of Google Maps and local search, so nearby customers call, visit and book you instead of your competitors.',
    motion: '/services/localseo.webp',
    points: ['Free local SEO audit', 'Google Business Profile optimised', 'Calls and directions tracked'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-local-seo',
      nav: 'What is it',
      eyebrow: 'The basics',
      heading: 'What Is Local SEO?',
      paras: [
        'Local SEO helps your business appear when people nearby search for what you offer, such as "plumber near me" or "dentist in Leeds". Google ranks local results on relevance, distance and prominence, and the top three map results win most of the calls.',
      ],
      bullets: [
        'Google Business Profile: the listing that shows in Maps and the map pack',
        'Local signals: citations, reviews and local links that build trust',
        'Location pages: website pages that rank for each town you serve',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      eyebrow: 'Results in numbers',
      heading: 'More Calls From Your Local Area',
      text: 'The numbers behind the local SEO we run for UK businesses.',
      stats: [
        { value: '48', label: 'Average map pack keywords won' },
        { value: '+156%', label: 'Average growth in calls from Google' },
        { value: '1,840', label: 'Average monthly direction requests' },
        { value: '4.9', label: 'Average client Google rating' },
      ],
    },
    {
      type: 'media',
      id: 'map-pack',
      nav: 'Map pack',
      eyebrow: 'Google Maps rankings',
      heading: 'Win a Place in the Map Pack',
      image: '/pages/local-seo/mappack.webp',
      alt: 'Google map pack with your business ranked first above two competitors',
      paras: ['The three businesses shown on the map get most local clicks. We improve every signal Google uses to choose them.'],
      bullets: ['Local keyword and competitor research', 'Map rank tracking by postcode', 'Local relevance and prominence signals', 'AI Overviews and local answers'],
    },
    {
      type: 'media',
      id: 'google-business-profile',
      nav: 'Business Profile',
      eyebrow: 'Google Business Profile',
      heading: 'A Profile That Gets Chosen',
      image: '/pages/local-seo/gbp.webp',
      alt: 'Google Business Profile checklist with categories, services, posts, photos and Q&A',
      flip: true,
      tone: 'grey',
      paras: ['Your Google Business Profile is often the first thing customers see. We complete and manage it every week.'],
      bullets: ['Categories, services and service areas', 'Weekly posts and offers', 'Photos and opening hours', 'Q&A and messaging'],
    },
    {
      type: 'media',
      id: 'citations',
      nav: 'Citations',
      eyebrow: 'Citations & local links',
      heading: 'Consistent Details Everywhere',
      image: '/pages/local-seo/citations.webp',
      alt: 'Business name, address and phone matched across Google, Apple Maps, Bing, Yell and Trustpilot',
      paras: ['Google trusts businesses whose name, address and phone (NAP) match across the web. We fix old listings and build new ones.'],
      bullets: ['NAP audit and clean-up', 'Apple Business Connect and Bing Places', 'UK directories and trade bodies', 'Local sponsorship and press links'],
    },
    {
      type: 'media',
      id: 'reviews',
      nav: 'Reviews',
      eyebrow: 'Reviews & location pages',
      heading: 'Reviews and Pages That Win Locals',
      image: '/pages/local-seo/reviews.webp',
      alt: 'Google reviews with 4.9 rating and owner replies',
      flip: true,
      tone: 'grey',
      paras: ['More good reviews boost rankings and trust. We help you get them and build location pages for every area you serve.'],
      bullets: ['Review request system', 'Replies to every review', 'Location and service area pages', 'LocalBusiness schema'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      eyebrow: 'Our local SEO service',
      heading: 'Everything Included',
      cards: [
        { icon: 'lucide:search', title: 'Local SEO Audit', text: 'Profile, site and competitors.' },
        { icon: 'lucide:map-pin', title: 'Business Profile', text: 'Optimised and managed weekly.' },
        { icon: 'lucide:key-round', title: 'Local Keywords', text: '"Near me" and town searches.' },
        { icon: 'lucide:file-text', title: 'Location Pages', text: 'A page for every area served.' },
        { icon: 'lucide:list-checks', title: 'Citations', text: 'NAP fixed and listings built.' },
        { icon: 'lucide:star', title: 'Reviews', text: 'More reviews, every one answered.' },
        { icon: 'lucide:link', title: 'Local Links', text: 'Press, partners and sponsors.' },
        { icon: 'lucide:chart-column-increasing', title: 'Reporting', text: 'Rankings, calls and directions.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      eyebrow: 'How we work',
      heading: 'Our Local SEO Process',
      steps: [
        { title: 'Audit', text: 'Rankings across your area.' },
        { title: 'Fix', text: 'Profile and NAP issues first.' },
        { title: 'Optimise', text: 'Website and location pages.' },
        { title: 'Build', text: 'Citations, links and reviews.' },
        { title: 'Engage', text: 'Weekly posts and replies.' },
        { title: 'Report', text: 'Calls, directions and leads.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      eyebrow: 'Local SEO case studies',
      heading: 'Local SEO Results We Have Delivered',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Local vs national',
      eyebrow: 'Compare',
      heading: 'Local SEO vs National SEO',
      columns: ['', 'Local SEO', 'National SEO'],
      rows: [
        ['Goal', 'Win customers near you', 'Win customers across the UK'],
        ['Main results', 'Map pack and local listings', 'Organic results and AI answers'],
        ['Key signals', 'Profile, reviews, citations', 'Content, links, technical SEO'],
        ['Best for', 'Shops, trades, clinics, firms', 'Online and nationwide services'],
      ],
      note: 'Many businesses need both: local SEO for nearby customers and national SEO for wider reach.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      eyebrow: 'Investment',
      heading: 'How Much Does Local SEO Cost?',
      intro: 'UK local SEO typically ranges from about £300 to £1,500+ per month. Your quote depends on:',
      cards: [
        { icon: 'lucide:map-pin', title: 'Locations', text: 'Number of branches or areas.' },
        { icon: 'lucide:users', title: 'Competition', text: 'How busy your local market is.' },
        { icon: 'lucide:file-text', title: 'Pages', text: 'Location pages to create.' },
        { icon: 'lucide:star', title: 'Reviews', text: 'Review volume and management.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews-clients',
      nav: 'Client reviews',
      eyebrow: 'Client reviews',
      heading: 'What Our Local SEO Clients Say',
      reviews: [
        { name: 'Steve P', role: 'Owner, Plumbing Firm', text: 'We are now top three on Google Maps across our area and the phone does not stop.' },
        { name: 'Anita G', role: 'Practice Manager, Dental Clinic', text: 'New patient calls from Google have more than doubled in six months.' },
        { name: 'Rob H', role: 'Director, Estate Agent', text: 'Each branch now ranks in its own town, with reviews to match.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      eyebrow: 'Industries we serve',
      heading: 'Local SEO for Your Industry',
      items: [
        { slug: 'healthcare', text: 'Clinics, dentists and pharmacies found nearby.' },
        { slug: 'hospitality-hotels', text: 'Restaurants and hotels top of Maps.' },
        { slug: 'real-estate', text: 'Estate and letting agents in every branch area.' },
        { slug: 'automotive', text: 'Garages and dealers that win local searches.' },
        { slug: 'finance', text: 'Accountants and advisers trusted locally.' },
        { slug: 'education', text: 'Schools, tutors and colleges found by parents.' },
      ],
    },
  ],
  faqs: [
    { q: 'How do I rank higher on Google Maps?', a: 'Complete and update your Google Business Profile, use the right categories, keep your name, address and phone consistent online, earn regular reviews and build local relevance with your website and links.' },
    { q: 'How long does local SEO take?', a: 'Many businesses see map ranking gains within 4 to 8 weeks. Competitive areas usually take 3 to 6 months.' },
    { q: 'Can I rank in towns where I do not have an office?', a: 'In the organic results, yes, with strong service area pages. The map pack strongly favours businesses close to the searcher, so it is harder there.' },
    { q: 'Do reviews really affect local rankings?', a: 'Yes. The number, quality and freshness of reviews influence both your map ranking and whether people choose you.' },
    { q: 'Can you manage several locations?', a: 'Yes. We manage multi-location brands with a profile, location page and reporting for each branch.' },
    { q: 'How do you measure local SEO results?', a: 'We track map rankings by postcode, calls, direction requests, website clicks and enquiries from your Google Business Profile.' },
    { q: 'Do you need a contract?', a: 'No. We work on rolling monthly terms.' },
  ],
  related: ['search-engine-optimization', 'reputation-management', 'seo-backlinks', 'google-ads', 'content-marketing', 'website-design'],
};

export default content;
