import type { ServiceContent } from '../types';

// Entity map: marketing advisory -> fractional CMO, marketing strategy, growth plan, ideal customer
// profile (ICP), go-to-market, channel strategy, marketing budget allocation, customer acquisition
// cost (CAC), lifetime value (LTV), ROI and ROAS, KPIs and dashboards, attribution, agency
// management, marketing team structure and hiring, board reporting, quarterly planning.

const content: ServiceContent = {
  slug: 'marketing-advisory',
  short: 'Marketing Advisory',
  metaTitle: 'Marketing Advisory & Fractional CMO UK | Growth Strategy | GTech Digital',
  metaDescription:
    'UK marketing advisory and fractional CMO services: senior guidance on strategy, channels, budgets and KPIs to grow faster without a full-time hire.',
  hero: {
    keyword: 'Marketing Advisory',
    title: 'Marketing Advisory and',
    highlight: 'Fractional CMO Services',
    lead:
      'GTech Digital provides marketing advisory and fractional CMO services for UK businesses, giving senior leadership on marketing strategy, channel mix, budgets and KPIs without the cost of a full-time marketing director.',
    motion: '/services/advisory.webp',
    points: ['Free strategy session', 'Fractional CMO from 2 days a month', 'Clear plan and KPIs'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-marketing-advisory',
      nav: 'What is it',
      heading: 'What Is Marketing Advisory and How Does It Work?',
      paras: [
        'Marketing advisory gives you senior marketing expertise on a part-time basis, often called a fractional CMO. It suits growing businesses that need a clear strategy and someone to lead marketing, but are not ready for a full-time director.',
      ],
      bullets: [
        'Strategy: who to target, what to say and where to show up',
        'Budget: how much to spend and on which channels',
        'Leadership: guiding your team and agencies to hit targets',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'Marketing Advisory Results and Key Statistics',
      text: 'The numbers behind the businesses we advise.',
      stats: [
        { value: '-45%', label: 'Average cost per acquisition' },
        { value: '+62%', label: 'Average growth in qualified leads' },
        { value: '5.2x', label: 'Average marketing ROI' },
        { value: '40+', label: 'Businesses advised' },
      ],
    },
    {
      type: 'media',
      id: 'growth-plan',
      nav: 'Growth plan',
      heading: '12-Month Marketing Growth Plan and Roadmap',
      image: '/pages/advisory/plan.webp',
      alt: 'Twelve-month growth plan with goals, audience, channels, budget and measurement',
      paras: ['We turn business goals into a practical marketing plan with priorities, owners and targets for every quarter.'],
      bullets: ['Goals and revenue targets', 'Ideal customer profile', 'Go-to-market and messaging', 'Quarterly priorities'],
    },
    {
      type: 'media',
      id: 'budget',
      nav: 'Budget',
      heading: 'Marketing Budget Allocation by Channel and ROI',
      image: '/pages/advisory/budget.webp',
      alt: 'Recommended marketing budget split across SEO, Google Ads, paid social, email and testing',
      flip: true,
      tone: 'grey',
      paras: ['We review where every pound goes, cut what does not work and shift budget into the channels that bring customers.'],
      bullets: ['Channel and budget audit', 'Budget allocation model', 'Test-and-scale framework', 'CAC and LTV targets'],
    },
    {
      type: 'media',
      id: 'kpis',
      nav: 'KPIs',
      heading: 'Marketing KPIs, Dashboards and Performance Reporting',
      image: '/pages/advisory/kpis.webp',
      alt: 'Cost per acquisition falling from £84 to £46 with more qualified leads and higher ROI',
      paras: ['We set up the dashboards and tracking that show what marketing really delivers, from first click to revenue.'],
      bullets: ['KPI framework', 'GA4 and CRM dashboards', 'Attribution and ROI', 'Board-ready reporting'],
    },
    {
      type: 'media',
      id: 'leadership',
      nav: 'Leadership',
      heading: 'Fractional CMO and Outsourced Marketing Leadership',
      image: '/pages/advisory/team.webp',
      alt: 'Monthly advisory checklist with strategy sessions, agency review, budget checks and reporting',
      flip: true,
      tone: 'grey',
      paras: ['We work with your team every month, manage agencies and freelancers, and help you hire the right people when the time comes.'],
      bullets: ['Monthly strategy sessions', 'Agency and supplier management', 'Team coaching', 'Hiring and briefs'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our Marketing Advisory Services',
      cards: [
        { icon: 'lucide:search', title: 'Marketing Audit', text: 'What works and what does not.' },
        { icon: 'lucide:target', title: 'Customer Profile', text: 'Who to win first.' },
        { icon: 'lucide:map', title: 'Growth Plan', text: '12-month roadmap.' },
        { icon: 'lucide:wallet', title: 'Budget Model', text: 'Spend by channel.' },
        { icon: 'lucide:chart-column-increasing', title: 'KPI Dashboards', text: 'Live performance data.' },
        { icon: 'lucide:users', title: 'Agency Management', text: 'Partners held to account.' },
        { icon: 'lucide:graduation-cap', title: 'Team Coaching', text: 'Skills and processes.' },
        { icon: 'lucide:presentation', title: 'Board Reporting', text: 'Clear monthly updates.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our Marketing Advisory Process, Step by Step',
      steps: [
        { title: 'Audit', text: 'Marketing, data and team.' },
        { title: 'Plan', text: 'Goals, channels and budget.' },
        { title: 'Measure', text: 'KPIs and dashboards set up.' },
        { title: 'Lead', text: 'Monthly sessions and decisions.' },
        { title: 'Test', text: 'New ideas tried and scaled.' },
        { title: 'Review', text: 'Quarterly plan updates.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'Marketing Advisory Case Studies and Results',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Fractional vs full-time',
      heading: 'Fractional CMO vs Full-Time Marketing Director',
      columns: ['', 'Fractional CMO', 'Full-time director'],
      rows: [
        ['Cost', 'Part of a salary', '£80,000 to £150,000+ a year'],
        ['Start time', 'Within weeks', 'Months to recruit'],
        ['Flexibility', 'Scale days up or down', 'Fixed commitment'],
        ['Best for', 'Growing businesses', 'Large marketing teams'],
      ],
      note: 'Many clients use advisory until they are ready to hire, and we help recruit their first marketing lead.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does Marketing Advisory Cost?',
      intro: 'UK marketing advisory typically ranges from about £1,200 to £6,000+ per month. Your quote depends on:',
      cards: [
        { icon: 'lucide:clock', title: 'Days per month', text: 'From two days upwards.' },
        { icon: 'lucide:users', title: 'Team size', text: 'People and agencies to lead.' },
        { icon: 'lucide:chart-column-increasing', title: 'Reporting', text: 'Dashboards and data setup.' },
        { icon: 'lucide:layers', title: 'Channels', text: 'How many channels in play.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'Marketing Advisory Client Reviews and Testimonials',
      reviews: [
        { name: 'Mark S', role: 'CEO, Professional Services', text: 'We stopped guessing. Budget now goes where the leads actually come from.' },
        { name: 'Priya L', role: 'Founder, D2C Brand', text: 'Like having a marketing director for a fraction of the cost.' },
        { name: 'Tom A', role: 'MD, Manufacturing', text: 'Our board finally gets marketing reports that make sense.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'Marketing Advisory Services by Industry',
      items: [
        { slug: 'technology-saas', text: 'Go-to-market and growth for SaaS.' },
        { slug: 'b2b-marketing', text: 'Pipeline-focused B2B strategy.' },
        { slug: 'e-commerce', text: 'Profitable growth for online brands.' },
        { slug: 'finance', text: 'Compliant growth plans for financial firms.' },
        { slug: 'healthcare', text: 'Patient acquisition strategy for clinics.' },
        { slug: 'education', text: 'Enrolment strategy for providers.' },
      ],
    },
  ],
  faqs: [
    { q: 'What is a fractional CMO?', a: 'A fractional CMO is a senior marketing leader who works with you part-time, usually a few days a month, setting strategy and leading marketing without a full-time salary.' },
    { q: 'When does a business need marketing advisory?', a: 'Common signs are spending on marketing without clear results, having no marketing plan, managing several agencies without direction or preparing to grow or raise investment.' },
    { q: 'How much time will you spend with us?', a: 'Most clients choose two to six days a month, including strategy sessions, team check-ins and reporting.' },
    { q: 'Will you manage our agencies?', a: 'Yes. We set briefs and targets for your agencies and freelancers and hold them to account.' },
    { q: 'Do you also deliver the marketing?', a: 'We can. Our specialist teams handle SEO, ads, social and web, or we work with your existing partners.' },
    { q: 'How do you measure success?', a: 'Against agreed business KPIs such as qualified leads, cost per acquisition, revenue and marketing ROI.' },
    { q: 'Do you need a contract?', a: 'No. Advisory runs on rolling monthly terms.' },
  ],
  related: ['branding', 'conversion-rate-optimization', 'digital-advertising', 'search-engine-optimization', 'content-marketing', 'linkedin-marketing'],
};

export default content;
