import type { ServiceContent } from '../types';

// Entity map: mobile app development -> iOS (Swift), Android (Kotlin), cross-platform (Flutter,
// React Native), progressive web apps, App Store and Google Play, TestFlight, push notifications,
// in-app payments (Apple Pay, Google Pay), offline mode, Face ID, GPS, app store optimisation (ASO),
// crash reporting, retention, ratings, back-end API, UK GDPR and privacy labels.

const content: ServiceContent = {
  slug: 'mobile-app-development',
  short: 'Mobile App Development',
  metaTitle: 'Mobile App Development Company UK | iOS & Android Apps | GTech Digital',
  metaDescription:
    'UK mobile app development company building iOS, Android and cross-platform apps with Flutter and React Native, from design and build to App Store launch.',
  hero: {
    keyword: 'Mobile App Development',
    title: 'Mobile App Development for',
    highlight: 'iOS and Android',
    lead:
      'GTech Digital is a UK mobile app development company that designs, builds and launches iOS and Android apps with Flutter, React Native or native code, from user experience design to App Store and Google Play release.',
    motion: '/services/mobileapp.webp',
    points: ['Free app consultation', 'iOS and Android from one codebase', 'App Store launch handled'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-mobile-app-development',
      nav: 'What is it',
      heading: 'What Is Mobile App Development and How Does It Work?',
      paras: [
        'Mobile app development is designing, building and launching apps for iPhone and Android. Today most apps are built cross-platform with Flutter or React Native, giving you both platforms from one codebase at a lower cost.',
      ],
      bullets: [
        'Customer apps: bookings, ordering, loyalty and accounts',
        'Business apps: field teams, inspections and stock',
        'Product apps: the app is the product you sell',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'Mobile App Development Results and Key Statistics',
      text: 'The numbers behind the mobile apps we build and support.',
      stats: [
        { value: '40+', label: 'Apps launched' },
        { value: '4.8', label: 'Average App Store rating' },
        { value: '46%', label: 'Average 30-day retention' },
        { value: '99.9%', label: 'Crash-free sessions' },
      ],
    },
    {
      type: 'media',
      id: 'design',
      nav: 'App design',
      heading: 'Mobile App UX and UI Design: Wireframes to Prototypes',
      image: '/pages/mobile/app.webp',
      alt: 'Mobile app with bookings, push notifications, payments and rewards, plus downloads, rating and retention',
      paras: ['We design simple screens around the few things users do most, so your app feels natural from the first tap.'],
      bullets: ['User journeys and wireframes', 'iOS and Android design patterns', 'Clickable prototypes', 'Accessibility built in'],
    },
    {
      type: 'media',
      id: 'platforms',
      nav: 'Platforms',
      heading: 'iOS, Android and Cross-Platform App Development With Flutter and React Native',
      image: '/pages/mobile/platforms.webp',
      alt: 'Mobile platforms: iOS, Android, Flutter, React Native, progressive web app and back end',
      flip: true,
      tone: 'grey',
      paras: ['Cross-platform apps cost less to build and maintain. We go fully native only when your app needs it.'],
      bullets: ['Flutter and React Native', 'Native Swift and Kotlin', 'Progressive web apps', 'Secure back-end APIs'],
    },
    {
      type: 'media',
      id: 'features',
      nav: 'Features',
      heading: 'Mobile App Features: Payments, Push Notifications and APIs',
      image: '/pages/mobile/features.webp',
      alt: 'App features: push notifications, maps, payments, offline mode, Face ID and messaging',
      paras: ['From push notifications to in-app payments, we build the features that bring users back and make it easy to buy.'],
      bullets: ['Push notifications', 'Apple Pay and Google Pay', 'Maps, GPS and offline mode', 'Face ID and secure sign-in'],
    },
    {
      type: 'media',
      id: 'launch',
      nav: 'Launch',
      heading: 'App Store Launch, ASO and User Growth',
      image: '/pages/mobile/launch.webp',
      alt: 'App launch checklist with store listings, beta testing, analytics, privacy and app store optimisation',
      flip: true,
      tone: 'grey',
      paras: ['We handle beta testing, store approval and launch, then use analytics and reviews to keep improving the app.'],
      bullets: ['App Store and Google Play submission', 'Beta testing with real users', 'Crash reporting and analytics', 'App store optimisation (ASO)'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our Mobile App Development Services',
      cards: [
        { icon: 'lucide:search', title: 'Discovery', text: 'Goals, users and features.' },
        { icon: 'lucide:pen-tool', title: 'App Design', text: 'Prototype tested with users.' },
        { icon: 'lucide:smartphone', title: 'iOS & Android', text: 'Cross-platform or native.' },
        { icon: 'lucide:server', title: 'Back End & API', text: 'Secure, scalable servers.' },
        { icon: 'lucide:credit-card', title: 'Payments', text: 'In-app and subscriptions.' },
        { icon: 'lucide:bell', title: 'Notifications', text: 'Push and in-app messages.' },
        { icon: 'lucide:rocket', title: 'Store Launch', text: 'Submission and approval.' },
        { icon: 'lucide:life-buoy', title: 'Support', text: 'Updates and new features.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our Mobile App Development Process, Step by Step',
      steps: [
        { title: 'Discover', text: 'Users, goals and features.' },
        { title: 'Design', text: 'Prototype tested with users.' },
        { title: 'Build', text: 'Sprints with test builds.' },
        { title: 'Beta', text: 'TestFlight and real users.' },
        { title: 'Launch', text: 'App Store and Google Play.' },
        { title: 'Grow', text: 'Analytics, updates and ASO.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'Mobile App Development Case Studies and Results',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Native vs cross-platform',
      heading: 'Native vs Cross-Platform Apps',
      columns: ['', 'Cross-platform (Flutter, React Native)', 'Native (Swift, Kotlin)'],
      rows: [
        ['Codebases', 'One for iOS and Android', 'Two separate apps'],
        ['Cost', 'Lower', 'Higher'],
        ['Performance', 'Excellent for most apps', 'Best for heavy graphics'],
        ['Best for', 'Most business and consumer apps', 'Games, AR and complex hardware'],
      ],
      note: 'Around nine in ten of the apps we build use a cross-platform framework.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does a Mobile App Cost?',
      intro: 'UK mobile apps typically range from about £15,000 to £90,000+, depending on features and platforms. Your quote depends on:',
      cards: [
        { icon: 'lucide:layout-dashboard', title: 'Screens', text: 'Number and complexity.' },
        { icon: 'lucide:server', title: 'Back end', text: 'APIs, admin and data.' },
        { icon: 'lucide:smartphone', title: 'Platforms', text: 'Cross-platform or native.' },
        { icon: 'lucide:puzzle', title: 'Features', text: 'Payments, maps and offline.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'Mobile App Development Client Reviews and Testimonials',
      reviews: [
        { name: 'Lucy M', role: 'Owner, Fitness Studio', text: 'Members book classes in the app and repeat visits are up a third.' },
        { name: 'Hamza I', role: 'Founder, Food Delivery', text: 'Launched on both stores in 12 weeks with a 4.8 rating from day one.' },
        { name: 'Graham T', role: 'Operations Manager, Construction', text: 'Site inspections now take minutes on a phone, even with no signal.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'Mobile App Development Services by Industry',
      items: [
        { slug: 'hospitality-hotels', text: 'Ordering, booking and loyalty apps.' },
        { slug: 'healthcare', text: 'Appointment and wellbeing apps.' },
        { slug: 'e-commerce', text: 'Shopping apps with push offers.' },
        { slug: 'education', text: 'Learning and student apps.' },
        { slug: 'travel', text: 'Trip, booking and guide apps.' },
        { slug: 'automotive', text: 'Service booking and fleet apps.' },
      ],
    },
  ],
  faqs: [
    { q: 'Should I build a native or cross-platform app?', a: 'For most business and consumer apps, cross-platform with Flutter or React Native is faster and cheaper with excellent performance. Native suits games, AR and apps needing deep hardware access.' },
    { q: 'How long does it take to build an app?', a: 'A first version usually takes 10 to 16 weeks from design to store launch.' },
    { q: 'Do you publish the app to the App Store?', a: 'Yes. We prepare listings, privacy labels and screenshots and handle App Store and Google Play submission.' },
    { q: 'Do I need a website as well as an app?', a: 'Usually yes. A website helps people find you on Google, while the app serves your regular customers.' },
    { q: 'Can the app take payments?', a: 'Yes. We integrate Apple Pay, Google Pay, card payments and in-app subscriptions.' },
    { q: 'How much does it cost to maintain an app?', a: 'Plan for around 15 to 20% of the build cost per year for updates, new OS versions and hosting.' },
    { q: 'Who owns the app?', a: 'You do. The app, code and store accounts belong to your business.' },
  ],
  related: ['web-application-development', 'mvp-development', 'saas-product-development', 'api-system-integration', 'website-design', 'branding'],
};

export default content;
