import type { ServiceContent } from '../types';

// Entity map: MVP development -> minimum viable product, product discovery, problem-solution fit,
// product-market fit, prototype (Figma), core feature set, scope (MoSCoW), lean startup, build-
// measure-learn, beta users, waitlist, landing page, analytics, user feedback, iteration, investor
// demo, pre-seed/seed funding, no-code vs custom code, time to market, scalable foundations.

const content: ServiceContent = {
  slug: 'mvp-development',
  short: 'MVP Development',
  metaTitle: 'MVP Development Company UK | Launch Your Startup Fast',
  metaDescription:
    'UK MVP development company helping founders turn ideas into launched products in 8 to 12 weeks, with discovery, design, build and real-user validation.',
  hero: {
    keyword: 'MVP Development',
    title: 'MVP Development: Launch in',
    highlight: 'Weeks, Not Months',
    lead:
      'GTech Digital provides MVP development for UK founders and teams, turning an idea into a working minimum viable product in 8 to 12 weeks, ready to test with real users, gather feedback and show traction to investors.',
    motion: '/services/mvp.webp',
    points: ['Free idea workshop', 'Launch in 8 to 12 weeks', 'Built to grow beyond v1'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-mvp',
      nav: 'What is it',
      heading: 'What Is an MVP and How Does It Work?',
      paras: [
        'A minimum viable product (MVP) is the simplest version of your product that solves the core problem for real users. It lets you test demand, collect feedback and show traction to investors before investing in a full build.',
      ],
      bullets: [
        'Focused: one core problem, solved well',
        'Fast: launched in weeks so you start learning sooner',
        'Solid: built on code that can grow into the full product',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'MVP Development Results and Key Statistics',
      text: 'The numbers behind the MVPs we build for UK founders and teams.',
      stats: [
        { value: '10 weeks', label: 'Average idea to launch' },
        { value: '35+', label: 'MVPs launched' },
        { value: '£6M+', label: 'Funding raised by clients' },
        { value: '52%', label: 'Average weekly active users' },
      ],
    },
    {
      type: 'media',
      id: 'scope',
      nav: 'Scope',
      heading: 'MVP Discovery, Scoping and Feature Prioritisation',
      image: '/pages/mvp/scope.webp',
      alt: 'MVP scope checklist with sign-up, core workflow, payments, analytics and admin, nice-to-haves parked',
      paras: ['We help you find the one workflow that proves your idea, and park everything else for later.'],
      bullets: ['Idea and problem workshop', 'User and competitor research', 'Must-have feature list', 'Clickable Figma prototype'],
    },
    {
      type: 'media',
      id: 'timeline',
      nav: 'Timeline',
      heading: 'MVP Development Timeline: From Idea to Launch in Weeks',
      image: '/pages/mvp/sprints.webp',
      alt: 'MVP timeline from discovery and prototype to build, testing, beta and launch over ten weeks',
      flip: true,
      tone: 'grey',
      paras: ['Short sprints and weekly demos keep you in control and let you change direction as you learn.'],
      bullets: ['Weekly demos', 'Fixed-price phases', 'Modern, scalable stack', 'Beta testing with real users'],
    },
    {
      type: 'media',
      id: 'launch',
      nav: 'Launch',
      heading: 'MVP Launch, Analytics and First Users',
      image: '/pages/mvp/launch.webp',
      alt: 'MVP app with sign-up, core feature, subscriptions and feedback, plus beta users and funding raised',
      paras: ['Your MVP launches with sign-up, payments, analytics and feedback built in, so you learn from day one.'],
      bullets: ['Web or mobile MVP', 'Payments or waitlist', 'Admin panel', 'Investor-ready demo'],
    },
    {
      type: 'media',
      id: 'validate',
      nav: 'Validate',
      heading: 'MVP Validation, User Feedback and Product Iteration',
      image: '/pages/mvp/validate.webp',
      alt: 'Beta validation funnel from landing page visits to paying customers',
      flip: true,
      tone: 'grey',
      paras: ['We track how people use your product and help you decide what to improve, add or drop for version two.'],
      bullets: ['Product analytics', 'User interviews and feedback', 'Retention and conversion tracking', 'Roadmap for version two'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our MVP Development Services',
      cards: [
        { icon: 'lucide:lightbulb', title: 'Idea Workshop', text: 'Problem, users and value.' },
        { icon: 'lucide:list-checks', title: 'Scoping', text: 'Must-haves only.' },
        { icon: 'lucide:pen-tool', title: 'Prototype', text: 'Clickable Figma design.' },
        { icon: 'lucide:code-xml', title: 'Development', text: 'Web or mobile MVP.' },
        { icon: 'lucide:credit-card', title: 'Payments', text: 'Subscriptions or checkout.' },
        { icon: 'lucide:chart-column-increasing', title: 'Analytics', text: 'Usage and retention.' },
        { icon: 'lucide:users', title: 'Beta Programme', text: 'Real users, real feedback.' },
        { icon: 'lucide:rocket', title: 'Launch Support', text: 'Go-live and next steps.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our MVP Development Process, Step by Step',
      steps: [
        { title: 'Workshop', text: 'Problem and users.' },
        { title: 'Prototype', text: 'Clickable design tested.' },
        { title: 'Scope', text: 'Fixed price and timeline.' },
        { title: 'Build', text: 'Weekly sprints and demos.' },
        { title: 'Launch', text: 'Beta and go-live.' },
        { title: 'Learn', text: 'Data, feedback and v2.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'MVP Development Case Studies and Results',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'No-code vs custom',
      heading: 'No-Code MVP vs Custom-Coded MVP',
      columns: ['', 'No-code (Bubble, Glide)', 'Custom code'],
      rows: [
        ['Speed', 'Very fast', 'Fast'],
        ['Cost', 'Lowest', 'Moderate'],
        ['Scalability', 'Limited', 'Grows into the full product'],
        ['Investor view', 'Fine for testing', 'Owned, scalable IP'],
      ],
      note: 'We advise honestly. For some ideas, a no-code test first is the smartest move.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does an MVP Cost?',
      intro: 'UK MVPs typically range from about £8,000 to £40,000, depending on scope and platform. Your quote depends on:',
      cards: [
        { icon: 'lucide:puzzle', title: 'Core features', text: 'The must-have workflow.' },
        { icon: 'lucide:smartphone', title: 'Platform', text: 'Web, mobile or both.' },
        { icon: 'lucide:webhook', title: 'Integrations', text: 'Payments and third parties.' },
        { icon: 'lucide:pen-tool', title: 'Design', text: 'Prototype and UI depth.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'MVP Development Client Reviews and Testimonials',
      reviews: [
        { name: 'Natalie C', role: 'Founder, Marketplace Start-up', text: 'We launched in ten weeks and raised our pre-seed round on the back of it.' },
        { name: 'Arjun P', role: 'Co-founder, B2B Tool', text: 'They talked us out of half our features. Best advice we got.' },
        { name: 'Molly F', role: 'Innovation Lead, Insurer', text: 'Our internal idea went from slide deck to live pilot in one quarter.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'MVP Development Services by Industry',
      items: [
        { slug: 'technology-saas', text: 'B2B and B2C software start-ups.' },
        { slug: 'finance', text: 'FinTech pilots and calculators.' },
        { slug: 'healthcare', text: 'HealthTech apps and booking tools.' },
        { slug: 'real-estate', text: 'PropTech marketplaces and portals.' },
        { slug: 'education', text: 'EdTech and learning apps.' },
        { slug: 'e-commerce', text: 'Marketplaces and subscription boxes.' },
      ],
    },
  ],
  faqs: [
    { q: 'How long does it take to build an MVP?', a: 'Most MVPs take 8 to 12 weeks from workshop to launch, depending on scope and platform. We fix the scope in week one, release a testable version early and keep weekly demos so you can steer the build.' },
    { q: 'How much should an MVP include?', a: 'Only what proves your core idea: usually sign-up, the main workflow, a way to pay or join, and analytics. Everything else waits until you have feedback.' },
    { q: 'Can the MVP grow into the full product?', a: 'Yes. We build on a solid, scalable foundation so you extend the product rather than rebuild it. Code quality, testing and architecture are set up properly from the start, even though the first release is deliberately small.' },
    { q: 'Should we build web or mobile first?', a: 'Usually web first, because it is faster to build and update. Go mobile first if your idea depends on phone features like location or the camera.' },
    { q: 'Can you help us pitch to investors?', a: 'We provide a polished demo, product metrics and technical answers for due diligence. Many founders use our MVP launch data, such as sign-ups and retention, to show traction in investor pitches.' },
    { q: 'Who owns the code and IP?', a: 'You do, in full, which is important for investors. We assign all intellectual property to your company in the contract and keep the code in your own repository from the first commit.' },
    { q: 'Do you sign NDAs?', a: 'Yes. We are happy to sign an NDA before you share your idea, and we keep all product plans and user data confidential. Many startup founders ask for this on the first call, and we agree straight away.' },
    { q: 'How do you handle product validation and user testing?', a: 'Product validation starts before we build: we test the problem with real customers, then use rapid prototyping to put clickable screens in front of users. After launch, user testing and analytics show whether you have product-market fit or need to change direction.' },
  ],
  related: ['saas-product-development', 'web-application-development', 'mobile-app-development', 'website-design', 'branding', 'marketing-advisory'],
};

export default content;
