import type { ServiceContent } from '../types';

// Entity map: paid media -> media planning and buying, budget allocation, channel mix (Google Ads,
// Meta, LinkedIn, TikTok, YouTube, programmatic), funnel stages (awareness, consideration,
// conversion), creative testing, audience strategy, bidding, incrementality, attribution models
// (data-driven, last click), marketing mix, blended ROAS / MER, CAC, LTV, server-side tracking.

const content: ServiceContent = {
  slug: 'paid-media',
  short: 'Paid Media',
  metaTitle: 'Paid Media Agency UK | Media Planning & Buying | GTech Digital',
  metaDescription:
    'UK paid media agency planning and buying across Google, Meta, LinkedIn, TikTok and YouTube. Budget allocation, creative testing and attribution that grow profit.',
  hero: {
    title: 'Paid Media Management',
    highlight: 'That Scales Profit',
    lead:
      'We plan, buy and optimise paid media across every major platform, putting your budget where it earns the most and proving the return with honest attribution.',
    motion: '/services/paidmedia.webp',
    points: ['Free media plan review', 'Budget tied to profit', 'One cross-channel report'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-paid-media',
      nav: 'What is it',
      heading: 'What Is Paid Media?',
      paras: [
        'Paid media is the strategy and buying behind all your advertising. Rather than running each platform on its own, we treat your budget as one investment and move it to the channels, audiences and creative that bring the most profit.',
      ],
      bullets: [
        'Planning: the right channel mix and budget for your goals',
        'Buying and optimisation: bids, audiences and creative tuned daily',
        'Measurement: attribution that shows what really drives sales',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'Paid Media Results in Numbers',
      text: 'The numbers behind the paid media we manage for UK businesses.',
      stats: [
        { value: '£4M+', label: 'Media budget managed' },
        { value: '5.6x', label: 'Average blended ROAS' },
        { value: '-32%', label: 'Average cost per acquisition' },
        { value: '100%', label: 'Spend tracked to results' },
      ],
    },
    {
      type: 'media',
      id: 'planning',
      nav: 'Media planning',
      heading: 'Media Planning and Budget Allocation',
      image: '/pages/paid-media/planning.webp',
      alt: 'Media plan budget split across Google, Meta, YouTube, LinkedIn and TikTok with blended ROAS',
      paras: ['We build a media plan from your margins, customer value and targets, then split budget across channels and funnel stages for the best overall return.'],
      bullets: ['Channel mix and budget allocation', 'Awareness, consideration and conversion stages', 'Targets for CPA, ROAS and MER', 'Seasonal and promotional planning'],
    },
    {
      type: 'media',
      id: 'channels',
      nav: 'Channels',
      heading: 'Paid Media Buying Across Platforms',
      image: '/pages/paid-media/channels.webp',
      alt: 'Cross-channel performance for Google Ads, Meta, LinkedIn, TikTok, YouTube and programmatic',
      flip: true,
      tone: 'grey',
      paras: ['Our specialists run Google Ads, Meta, LinkedIn, TikTok, YouTube and programmatic campaigns, each set up for how that platform works best.'],
      bullets: ['Google Search, Shopping and PMax', 'Meta, TikTok and Pinterest', 'LinkedIn for B2B', 'YouTube, CTV and programmatic'],
    },
    {
      type: 'media',
      id: 'creative',
      nav: 'Creative testing',
      heading: 'Ad Creative Testing',
      image: '/pages/paid-media/creative.webp',
      alt: 'Creative testing grid comparing ad variants and the winning angle',
      paras: ['Creative is now the biggest lever in paid media. We test new angles, formats and hooks every week and scale the winners.'],
      bullets: ['Ad concepts and angles', 'Static, video and UGC formats', 'Structured A/B and multivariate tests', 'Creative fatigue monitoring'],
    },
    {
      type: 'media',
      id: 'attribution',
      nav: 'Attribution',
      heading: 'Paid Media Attribution and Tracking',
      image: '/pages/paid-media/attribution.webp',
      alt: 'Revenue from paid media growing with lower cost per acquisition and blended ROAS',
      flip: true,
      tone: 'grey',
      paras: ['Platforms each claim credit for the same sale. We combine accurate tracking with blended metrics so you can see the true return on your spend.'],
      bullets: ['Server-side and Conversions API tracking', 'GA4 and data-driven attribution', 'Blended ROAS and MER reporting', 'Incrementality and holdout tests'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our Paid Media Services',
      cards: [
        { icon: 'lucide:map', title: 'Media Plan', text: 'Channels, budget and targets set from your margins.' },
        { icon: 'lucide:wallet', title: 'Budget Allocation', text: 'Spend moved weekly to the best performers.' },
        { icon: 'lucide:layers', title: 'Multi-Platform Buying', text: 'Google, Meta, LinkedIn, TikTok and YouTube.' },
        { icon: 'lucide:users', title: 'Audience Strategy', text: 'Prospecting, retargeting and customer lists.' },
        { icon: 'lucide:image', title: 'Creative Testing', text: 'New ad angles tested every week.' },
        { icon: 'lucide:settings-2', title: 'Tracking', text: 'Server-side tracking and clean data.' },
        { icon: 'lucide:gauge', title: 'Bidding', text: 'CPA and ROAS bid strategies managed daily.' },
        { icon: 'lucide:chart-column-increasing', title: 'Reporting', text: 'One blended report across every channel.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our Paid Media Process',
      steps: [
        { title: 'Audit', text: 'Accounts, tracking and past performance reviewed.' },
        { title: 'Model', text: 'Targets set from margins and customer value.' },
        { title: 'Plan', text: 'Channel mix, budget and creative plan.' },
        { title: 'Launch', text: 'Campaigns built with clean tracking.' },
        { title: 'Optimise', text: 'Daily bids, weekly creative and budget shifts.' },
        { title: 'Scale', text: 'Monthly reviews and budget growth into winners.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'Paid Media Case Studies',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Funnel',
      heading: 'Paid Media Channels Across the Funnel',
      columns: ['', 'Awareness', 'Consideration', 'Conversion'],
      rows: [
        ['Goal', 'Reach new audiences', 'Build interest and trust', 'Turn intent into sales'],
        ['Typical channels', 'YouTube, TikTok, CTV', 'Meta, LinkedIn, Display', 'Search, Shopping, retargeting'],
        ['Creative', 'Video and brand stories', 'Proof, reviews, demos', 'Offers and urgency'],
        ['Key metric', 'Reach and CPM', 'Engaged visits and leads', 'CPA and ROAS'],
      ],
      note: 'Funding every stage keeps your conversion campaigns supplied with new, interested buyers.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does Paid Media Management Cost?',
      intro: 'UK paid media management typically costs 10 to 20% of ad spend, often with a minimum of around £750 per month. Your fee depends on:',
      cards: [
        { icon: 'lucide:wallet', title: 'Media budget', text: 'Total monthly spend across platforms.' },
        { icon: 'lucide:layers', title: 'Channels', text: 'How many platforms we run.' },
        { icon: 'lucide:image', title: 'Creative volume', text: 'New ads needed for testing each month.' },
        { icon: 'lucide:settings-2', title: 'Tracking needs', text: 'Server-side tracking and attribution setup.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'Paid Media Client Reviews',
      reviews: [
        { name: 'Tom B', role: 'CEO, DTC Brand', text: 'They rebalanced our budget across Google, Meta and TikTok and blended ROAS went from 2.8x to 5.1x.' },
        { name: 'Nina S', role: 'Head of Growth, SaaS', text: 'For the first time we trust our attribution, and we cut cost per trial by a third.' },
        { name: 'Paul H', role: 'Marketing Director, Retail', text: 'Weekly creative tests keep finding new winners. Scaling spend no longer kills our returns.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'Paid Media for Your Industry',
      items: [
        { slug: 'e-commerce', text: 'Profit-led media plans for online stores and DTC brands.' },
        { slug: 'technology-saas', text: 'Trial and demo growth with CAC and LTV targets.' },
        { slug: 'finance', text: 'Compliant campaigns for regulated financial products.' },
        { slug: 'travel', text: 'Seasonal budgets that follow demand and booking windows.' },
        { slug: 'education', text: 'Enrolment campaigns timed to intake periods.' },
        { slug: 'b2b-marketing', text: 'LinkedIn and search campaigns for high-value pipelines.' },
      ],
    },
  ],
  faqs: [
    { q: 'What is the difference between paid media and digital advertising?', a: 'Digital advertising is the ads themselves. Paid media is the strategy, planning and buying behind them: deciding how much to spend on each channel and moving budget to what drives the most profit.' },
    { q: 'How do you decide where to spend our budget?', a: 'We start from your margins and customer value, set targets for cost per acquisition or ROAS, then test channels and shift budget weekly towards those that hit the targets.' },
    { q: 'What is blended ROAS?', a: 'Blended ROAS is your total revenue divided by total ad spend across all channels. It avoids double counting when several platforms claim the same sale and gives a truer picture of overall return.' },
    { q: 'How much should we spend on paid media?', a: 'It depends on your goals and economics. We model the budget needed to hit your targets and recommend a starting spend you can scale as results prove out.' },
    { q: 'Do you produce the ad creative?', a: 'Yes. We produce static, video and UGC-style creative and test new versions every week.' },
    { q: 'How do you handle tracking after iOS privacy changes?', a: 'We use server-side tracking, the Meta Conversions API, enhanced conversions and GA4 so you keep accurate data, then report blended metrics alongside platform numbers.' },
    { q: 'Do you need a contract?', a: 'No. We work on rolling monthly terms.' },
  ],
  related: ['google-ads', 'digital-advertising', 'facebook-marketing', 'tiktok-marketing', 'conversion-rate-optimization', 'marketing-advisory'],
};

export default content;
