import type { ServiceContent } from '../types';

// Entity map: PHP development -> PHP 8.3, object-oriented PHP, Composer, PSR standards, frameworks
// (Laravel, Symfony), MySQL/PostgreSQL, Redis, REST and GraphQL APIs, webhooks, OAuth 2,
// legacy code modernisation (PHP 5/7 upgrades), automated testing (PHPUnit, Pest), static analysis
// (PHPStan), Docker, CI/CD, OPcache, query optimisation, Linux hosting, security patches.

const content: ServiceContent = {
  slug: 'php-development',
  short: 'PHP Development',
  metaTitle: 'PHP Development Company UK | Custom PHP Apps & APIs | GTech Digital',
  metaDescription:
    'UK PHP development company building custom web applications, APIs and integrations, and upgrading legacy PHP to modern, secure PHP 8.',
  hero: {
    keyword: 'PHP Development',
    title: 'PHP Development for',
    highlight: 'Custom Web Applications',
    lead:
      'GTech Digital is a UK PHP development company that builds custom web applications and APIs with modern PHP 8, Laravel and Symfony, and upgrades legacy PHP systems to be faster, more secure and easier to maintain.',
    motion: '/services/php.webp',
    points: ['Free code review', 'Modern PHP 8 standards', 'Tested, documented code'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-php-development',
      nav: 'What is it',
      heading: 'What Is PHP Development and How Does It Work?',
      paras: [
        'PHP is the server-side language behind much of the web, including WordPress and Laravel. Custom PHP development means building the web applications, portals and APIs that run your processes, using modern PHP 8 and proven frameworks.',
      ],
      bullets: [
        'Applications: portals, dashboards and internal tools',
        'APIs: connect your website, apps and third-party systems',
        'Modernisation: upgrade and secure legacy PHP code',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'PHP Development Results and Key Statistics',
      text: 'The numbers behind the PHP systems we build and modernise.',
      stats: [
        { value: '4x', label: 'Average speed gain after upgrade' },
        { value: '180ms', label: 'Average API response time' },
        { value: '86%', label: 'Average test coverage' },
        { value: '60+', label: 'Legacy systems upgraded' },
      ],
    },
    {
      type: 'media',
      id: 'applications',
      nav: 'Applications',
      heading: 'Custom PHP Web Application Development',
      image: '/pages/php/apps.webp',
      alt: 'Custom PHP application stack from front end and application logic to APIs, data and hosting',
      paras: ['We build the portals, booking systems and admin tools your team needs, with clean architecture that is easy to extend.'],
      bullets: ['Customer and staff portals', 'Booking and quoting systems', 'Admin dashboards and reports', 'Laravel or Symfony frameworks'],
    },
    {
      type: 'media',
      id: 'apis',
      nav: 'APIs',
      heading: 'PHP API Development and Third-Party Integrations',
      image: '/pages/php/apis.webp',
      alt: 'PHP platform connected by API to Stripe, Xero, HubSpot, courier, email and ERP systems',
      flip: true,
      tone: 'grey',
      paras: ['We build secure REST APIs and integrations so data flows between your website, CRM, accounts and suppliers automatically.'],
      bullets: ['REST and GraphQL APIs', 'Payment and accounting integrations', 'Webhooks and scheduled sync', 'OAuth 2 and API security'],
    },
    {
      type: 'media',
      id: 'modernisation',
      nav: 'Modernisation',
      heading: 'Legacy PHP Modernisation, Upgrades and Refactoring',
      image: '/pages/php/modernise.webp',
      alt: 'Legacy PHP upgrade checklist with PHP 8.3, security patches, tests and Composer',
      paras: ['Old PHP versions are slow and no longer get security fixes. We upgrade step by step, adding tests so nothing breaks along the way.'],
      bullets: ['PHP 5 and 7 to PHP 8.3 upgrades', 'Security patches and refactoring', 'Automated tests added first', 'Composer and dependency clean-up'],
    },
    {
      type: 'media',
      id: 'performance',
      nav: 'Performance',
      heading: 'PHP Performance Optimisation and Automated Testing',
      image: '/pages/php/performance.webp',
      alt: 'PHP service code with response time, faster queries and uptime',
      flip: true,
      tone: 'grey',
      paras: ['We profile slow pages, fix database queries and add caching, then keep quality high with tests and automated deployment.'],
      bullets: ['Query and index optimisation', 'Redis caching and OPcache', 'PHPUnit, Pest and PHPStan', 'Docker and CI/CD pipelines'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our PHP Development Services',
      cards: [
        { icon: 'lucide:search', title: 'Code Review', text: 'Quality, security and speed checked.' },
        { icon: 'lucide:app-window', title: 'Web Applications', text: 'Portals and internal tools.' },
        { icon: 'lucide:webhook', title: 'API Development', text: 'Secure REST and GraphQL APIs.' },
        { icon: 'lucide:refresh-cw', title: 'PHP Upgrades', text: 'Legacy code moved to PHP 8.' },
        { icon: 'lucide:database', title: 'Database Work', text: 'MySQL design and optimisation.' },
        { icon: 'lucide:shield-check', title: 'Security', text: 'Patches, hardening and audits.' },
        { icon: 'lucide:flask-conical', title: 'Testing', text: 'Automated tests you can trust.' },
        { icon: 'lucide:life-buoy', title: 'Support', text: 'Ongoing fixes and features.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our PHP Development Process, Step by Step',
      steps: [
        { title: 'Review', text: 'Requirements or existing code.' },
        { title: 'Plan', text: 'Architecture, scope and estimate.' },
        { title: 'Build', text: 'Two-week sprints with demos.' },
        { title: 'Test', text: 'Automated and user testing.' },
        { title: 'Deploy', text: 'Zero-downtime release.' },
        { title: 'Support', text: 'Monitoring and improvements.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'PHP Development Case Studies and Results',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Upgrade or rebuild',
      heading: 'Upgrade or Rebuild Your PHP System?',
      columns: ['', 'Upgrade', 'Rebuild'],
      rows: [
        ['Best when', 'Core logic still works', 'Code is unmaintainable'],
        ['Cost', 'Lower', 'Higher'],
        ['Risk', 'Low, done in stages', 'Medium, needs careful migration'],
        ['Timeline', 'Weeks', 'Months'],
      ],
      note: 'A code review tells you which option saves the most over the next five years.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does PHP Development Cost?',
      intro: 'UK custom PHP projects typically range from about £5,000 to £50,000+, or from £450 per day for ongoing work. Your quote depends on:',
      cards: [
        { icon: 'lucide:puzzle', title: 'Features', text: 'Scope and complexity of the system.' },
        { icon: 'lucide:webhook', title: 'Integrations', text: 'Number of systems to connect.' },
        { icon: 'lucide:file-code', title: 'Existing code', text: 'Condition of legacy code.' },
        { icon: 'lucide:shield-check', title: 'Compliance', text: 'Security and data needs.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'PHP Development Client Reviews and Testimonials',
      reviews: [
        { name: 'Nick E', role: 'Operations Director, Logistics', text: 'They upgraded our 10-year-old PHP system without a single day of downtime.' },
        { name: 'Sara L', role: 'Founder, Booking Platform', text: 'Our API now handles four times the traffic and pages load in a fraction of the time.' },
        { name: 'Ian M', role: 'IT Manager, Manufacturer', text: 'Clean, documented code and clear communication from start to finish.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'PHP Development Services by Industry',
      items: [
        { slug: 'finance', text: 'Secure portals and calculators.' },
        { slug: 'healthcare', text: 'Patient booking and records tools.' },
        { slug: 'travel', text: 'Booking engines and supplier APIs.' },
        { slug: 'education', text: 'Learning portals and enrolment systems.' },
        { slug: 'automotive', text: 'Stock feeds and dealer systems.' },
        { slug: 'e-commerce', text: 'Order, stock and fulfilment integrations.' },
      ],
    },
  ],
  faqs: [
    { q: 'Is PHP still a good choice in 2026?', a: 'Yes. Modern PHP 8 is fast, secure and actively developed, and it powers a large share of the web, including WordPress and Laravel.' },
    { q: 'Can you work on our existing PHP code?', a: 'Yes. We start with a code review, then fix, extend or upgrade your system depending on its condition.' },
    { q: 'Why should we upgrade an old PHP version?', a: 'Old PHP versions no longer receive security fixes and are much slower. Upgrading reduces risk, improves speed and makes hosting easier.' },
    { q: 'Do you use frameworks?', a: 'Usually, yes. Laravel or Symfony give a secure, well-tested foundation and make your system easier for any developer to maintain.' },
    { q: 'Will we get the source code?', a: 'Yes. You own the code, which we keep in your version control with documentation.' },
    { q: 'Do you sign NDAs?', a: 'Yes. We are happy to sign an NDA before reviewing your system.' },
    { q: 'Do you offer ongoing support?', a: 'Yes. We offer monthly support plans covering fixes, updates and new features.' },
  ],
  related: ['laravel-development', 'web-application-development', 'api-system-integration', 'wordpress-development', 'website-maintenance', 'crm-erp-development'],
};

export default content;
