import type { ServiceContent } from '../types';

// Entity map: Pinterest marketing -> Pinterest business account, Pins (standard, video, Idea Pins),
// boards, Pinterest SEO (keywords in pin titles, descriptions, board names; alt text), Rich Pins,
// product catalogues, Shopping Pins, Pinterest Ads (consideration, conversion, shopping campaigns),
// Pinterest Tag and Conversions API, verified merchant programme, saves, outbound clicks,
// seasonal planning (planners search months ahead), Pinterest Trends.

const content: ServiceContent = {
  slug: 'pinterest-marketing',
  short: 'Pinterest Marketing',
  metaTitle: 'Pinterest Marketing Agency UK | Pinterest SEO & Ads | GTech Digital',
  metaDescription:
    'UK Pinterest marketing agency: Pinterest SEO, pin design, shopping catalogues and Pinterest Ads that drive long-lasting traffic and online sales.',
  hero: {
    keyword: 'Pinterest Marketing',
    title: 'Pinterest Marketing for',
    highlight: 'Traffic and Sales',
    lead:
      'GTech Digital is a UK Pinterest marketing agency that designs pins, optimises boards for Pinterest SEO and runs shopping ads, helping brands reach people planning purchases and drive website traffic that lasts for months.',
    motion: '/services/pinterest.webp',
    points: ['Free Pinterest audit', 'Pins designed for you', 'Traffic and sales tracked'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-pinterest-marketing',
      nav: 'What is it',
      heading: 'What Is Pinterest Marketing and How Does It Work?',
      paras: [
        'Pinterest is a visual search engine where people plan purchases, from homes and recipes to weddings and gifts. Unlike other social posts, pins can keep bringing traffic for months, and Pinterest users often have clear intent to buy.',
      ],
      bullets: [
        'Pinterest SEO: pins and boards found through keyword search',
        'Content: pins, video pins and Idea Pins designed to be saved',
        'Shopping: product catalogues and ads that send buyers to your site',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'Pinterest Marketing Results and Key Statistics',
      text: 'The numbers behind the Pinterest accounts we manage for UK brands.',
      stats: [
        { value: '420k', label: 'Average monthly views' },
        { value: '5.0x', label: 'Average shopping ad ROAS' },
        { value: '+186%', label: 'Average outbound clicks growth' },
        { value: '6 months', label: 'Typical pin lifespan' },
      ],
    },
    {
      type: 'media',
      id: 'boards',
      nav: 'Pins & boards',
      heading: 'Pin Design, Idea Pins and Board Strategy',
      image: '/pages/pinterest/boards.webp',
      alt: 'Pin and board plan with idea, product, video and seasonal pins',
      paras: ['We design vertical pins with clear text overlays and build boards around the topics your buyers plan for.'],
      bullets: ['Pin design in 2:3 format', 'Video and Idea Pins', 'Board structure by topic and season', 'Fresh pins published every week'],
    },
    {
      type: 'media',
      id: 'pinterest-seo',
      nav: 'Pinterest SEO',
      heading: 'Pinterest SEO: Keywords, Boards and Rich Pins',
      image: '/pages/pinterest/seo.webp',
      alt: 'Pin annotated with keyword title, description, board keywords, alt text and product link',
      flip: true,
      tone: 'grey',
      paras: ['Pinterest works like a search engine. We research the keywords your buyers use and add them to pin titles, descriptions and boards.'],
      bullets: ['Pinterest keyword research', 'Optimised titles and descriptions', 'Keyword-rich board names', 'Rich Pins and alt text'],
    },
    {
      type: 'media',
      id: 'ads',
      nav: 'Pinterest ads',
      heading: 'Pinterest Ads and Promoted Pins',
      image: '/pages/pinterest/ads.webp',
      alt: 'Pinterest shopping revenue with ROAS, saves and outbound click-through',
      paras: ['Pinterest Ads appear in search and home feeds while people are still deciding. We target by keyword, interest and audience to win the sale early.'],
      bullets: ['Shopping and catalogue campaigns', 'Consideration and conversion campaigns', 'Keyword and interest targeting', 'Seasonal campaigns planned ahead'],
    },
    {
      type: 'media',
      id: 'catalogue',
      nav: 'Catalogue',
      heading: 'Pinterest Catalogues, Shopping Pins and Conversion Tracking',
      image: '/pages/pinterest/catalogue.webp',
      alt: 'Pinterest catalogue and tracking checklist with tag, feed and verified merchant',
      flip: true,
      tone: 'grey',
      paras: ['We connect your product catalogue so every product becomes a shoppable pin, and set up tracking to measure the sales Pinterest drives.'],
      bullets: ['Product catalogue feed setup', 'Pinterest Tag and Conversions API', 'Verified merchant programme', 'GA4 sales tracking'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our Pinterest Marketing Services',
      cards: [
        { icon: 'lucide:search', title: 'Pinterest Audit', text: 'Account, boards and competitors reviewed.' },
        { icon: 'lucide:key-round', title: 'Keyword Research', text: 'The searches your buyers make on Pinterest.' },
        { icon: 'lucide:image', title: 'Pin Design', text: 'Fresh, on-brand pins every week.' },
        { icon: 'lucide:video', title: 'Video & Idea Pins', text: 'Short video pins that get saved.' },
        { icon: 'lucide:layout-template', title: 'Board Strategy', text: 'Boards organised by topic and season.' },
        { icon: 'lucide:shopping-bag', title: 'Shopping Catalogue', text: 'Products turned into shoppable pins.' },
        { icon: 'lucide:megaphone', title: 'Pinterest Ads', text: 'Shopping and conversion campaigns.' },
        { icon: 'lucide:chart-column-increasing', title: 'Reporting', text: 'Views, saves, clicks and sales.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our Pinterest Marketing Process, Step by Step',
      steps: [
        { title: 'Audit', text: 'Account, content and competitors.' },
        { title: 'Research', text: 'Keywords and seasonal trends.' },
        { title: 'Set up', text: 'Boards, Rich Pins, catalogue and tag.' },
        { title: 'Design', text: 'Pins created and scheduled weekly.' },
        { title: 'Promote', text: 'Shopping and conversion ads.' },
        { title: 'Report', text: 'Traffic, saves and sales monthly.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'Pinterest Marketing Case Studies and Results',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Pinterest vs others',
      heading: 'Pinterest vs Instagram for Your Brand',
      columns: ['', 'Pinterest', 'Instagram'],
      rows: [
        ['How people use it', 'Search and plan future purchases', 'Follow, scroll and engage'],
        ['Content lifespan', 'Months', 'Days'],
        ['Best for', 'Website traffic and sales', 'Community and brand awareness'],
        ['Key metric', 'Saves and outbound clicks', 'Reach and engagement'],
      ],
      note: 'Many retail and lifestyle brands use both: Instagram for community, Pinterest for traffic and sales.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does Pinterest Marketing Cost?',
      intro: 'UK Pinterest management typically ranges from about £400 to £2,000+ per month, plus ad spend. Your quote depends on:',
      cards: [
        { icon: 'lucide:image', title: 'Pin volume', text: 'New pins designed each week.' },
        { icon: 'lucide:video', title: 'Video pins', text: 'Whether video content is included.' },
        { icon: 'lucide:shopping-bag', title: 'Catalogue size', text: 'Number of products to manage.' },
        { icon: 'lucide:wallet', title: 'Ad spend', text: 'Budget for Pinterest Ads.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'Pinterest Marketing Client Reviews and Testimonials',
      reviews: [
        { name: 'Amy W', role: 'Owner, Homeware Store', text: 'Pinterest is now our second biggest traffic source and those pins keep working for months.' },
        { name: 'Rebecca J', role: 'Food Blogger', text: 'Their Pinterest SEO tripled our recipe traffic within half a year.' },
        { name: 'Joe M', role: 'Founder, Wedding Supplies', text: 'Seasonal shopping ads launched early and caught brides months before the big day.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'Pinterest Marketing Services by Industry',
      items: [
        { slug: 'e-commerce', text: 'Shopping catalogues for home, fashion and gifts.' },
        { slug: 'hospitality-hotels', text: 'Venue, recipe and event inspiration that books visits.' },
        { slug: 'travel', text: 'Destination boards that inspire future trips.' },
        { slug: 'real-estate', text: 'Interior and home ideas for buyers and renovators.' },
        { slug: 'education', text: 'Study tips and resources that build an audience.' },
        { slug: 'healthcare', text: 'Wellness and lifestyle content people save.' },
      ],
    },
  ],
  faqs: [
    { q: 'Is Pinterest good for business?', a: 'Pinterest works especially well for home, food, fashion, beauty, travel, weddings and gifts. Users come to plan purchases, so pins often drive high-intent traffic to your website.' },
    { q: 'How long do Pinterest pins last?', a: 'Much longer than social posts. A well-optimised pin can keep getting views and clicks for months, sometimes years, because people find it through search.' },
    { q: 'What is Pinterest SEO?', a: 'Pinterest SEO means using the keywords people search for in your pin titles, descriptions and board names so Pinterest shows your pins in search results and related feeds.' },
    { q: 'How often should we pin?', a: 'Fresh pins matter more than repins. We usually recommend several new pins a week, published consistently.' },
    { q: 'When should we start seasonal campaigns?', a: 'Early. People plan on Pinterest weeks or months ahead, so Christmas, summer and wedding content should go live well before the season.' },
    { q: 'Can we sell products on Pinterest?', a: 'Yes. By connecting your product catalogue, your products become shoppable pins, and shopping ads can promote them to people searching for similar items.' },
    { q: 'Do you need a contract?', a: 'No. We work on rolling monthly terms.' },
  ],
  related: ['instagram-marketing', 'facebook-marketing', 'ecommerce-development', 'content-marketing', 'search-engine-optimization', 'paid-media'],
};

export default content;
