import type { ServiceContent } from '../types';

// Entity map: online reputation management (ORM) -> reviews (Google reviews, Trustpilot,
// Facebook, TripAdvisor, industry sites), star rating, review volume and recency, review responses,
// branded search results (SERP), Knowledge Panel, review schema, sentiment, brand mentions,
// AI answers about a brand (ChatGPT, Google AI Overviews), crisis response, Google review policy.

const content: ServiceContent = {
  slug: 'reputation-management',
  short: 'Reputation Management',
  metaTitle: 'Online Reputation Management UK | Reviews & Brand Search',
  metaDescription:
    'Online reputation management for UK businesses: more genuine 5-star reviews, faster responses, cleaner branded search results and better AI answers.',
  hero: {
    keyword: 'Online Reputation Management',
    title: 'Reputation Management That',
    highlight: 'Builds Trust',
    lead:
      'GTech Digital provides online reputation management for UK businesses, generating genuine reviews, responding to customer feedback, improving branded search results and shaping how AI assistants describe your brand.',
    motion: '/services/reputation.webp',
    points: ['Free reputation audit', 'Policy-compliant reviews', 'Monthly sentiment report'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-orm',
      nav: 'What is ORM',
      heading: 'What Is Online Reputation Management and How Does It Work?',
      paras: [
        'Before most people buy, book or call, they read your reviews and search your name. Online reputation management (ORM) shapes what they find, so your real quality shows up where decisions are made.',
      ],
      bullets: [
        'Reviews: more genuine 5-star reviews on Google, Trustpilot and industry sites',
        'Responses: every review answered quickly and professionally',
        'Search & AI: positive branded results and accurate AI answers about your business',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'Reputation Management Results and Key Statistics',
      text: 'The numbers behind our reputation work for UK businesses.',
      stats: [
        { value: '4.8★', label: 'Average client rating' },
        { value: '18,000+', label: 'Reviews generated' },
        { value: '<2h', label: 'Average response time' },
        { value: '9/10', label: 'Positive page-one results' },
      ],
    },
    {
      type: 'media',
      id: 'reviews-generation',
      nav: 'Review generation',
      heading: 'Review Generation on Google, Trustpilot and Industry Sites',
      image: '/pages/reputation/reviews.webp',
      alt: 'Google review summary with 4.9 stars and recent customer reviews with owner replies',
      paras: ['Happy customers rarely leave reviews unless you ask at the right moment. We automate polite, policy-compliant requests by email, SMS and QR code.'],
      bullets: ['Automated review requests after purchase or visit', 'Google, Trustpilot and industry platforms', 'No incentives or gating, fully compliant', 'Review widgets and schema on your website'],
    },
    {
      type: 'media',
      id: 'monitoring',
      nav: 'Monitoring',
      heading: 'Review Monitoring, Response and Negative Review Handling',
      image: '/pages/reputation/monitoring.webp',
      alt: 'Star rating rising over twelve months with response time and reviews answered',
      flip: true,
      tone: 'grey',
      paras: ['We monitor reviews and mentions across the web and reply on your behalf in your tone of voice, turning unhappy customers into fair ones.'],
      bullets: ['Real-time alerts for new reviews', 'Replies to positive and negative reviews', 'Escalation for serious complaints', 'Reporting fake or policy-breaking reviews'],
    },
    {
      type: 'media',
      id: 'branded-search',
      nav: 'Branded search',
      heading: 'Branded Search Results and Online Reputation Repair',
      image: '/pages/reputation/serp.webp',
      alt: 'Branded search results made up of positive owned and earned pages',
      paras: ['Searches for your brand should show your best pages. We strengthen the results you control so outdated or unfair pages drop out of sight.'],
      bullets: ['Optimised website, profiles and Knowledge Panel', 'Positive press and case studies', 'Social and directory profiles that rank', 'Removal requests where policy allows'],
    },
    {
      type: 'media',
      id: 'ai-reputation',
      nav: 'AI reputation',
      heading: 'AI Search Reputation: ChatGPT, Gemini and AI Overviews',
      image: '/pages/reputation/ai.webp',
      alt: 'AI assistant and Google AI Overview describing a brand and citing its website',
      flip: true,
      tone: 'grey',
      paras: ['ChatGPT and Google AI Overviews summarise what the web says about you. We make sure accurate, positive and well-sourced information is what they find.'],
      bullets: ['AI answer audits for your brand', 'Accurate facts across trusted sources', 'Consistent entity and review signals', 'Ongoing monitoring of AI mentions'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our Reputation Management Services',
      cards: [
        { icon: 'lucide:search', title: 'Reputation Audit', text: 'Ratings, reviews, branded search and AI answers reviewed.' },
        { icon: 'lucide:star', title: 'Review Generation', text: 'Automated, compliant review requests that work.' },
        { icon: 'lucide:message-square', title: 'Review Responses', text: 'Professional replies in your brand voice.' },
        { icon: 'lucide:bell', title: 'Monitoring', text: 'Alerts for reviews and mentions across the web.' },
        { icon: 'lucide:shield-alert', title: 'Crisis Support', text: 'Fast, calm handling of negative publicity.' },
        { icon: 'lucide:globe', title: 'Branded Search', text: 'Positive owned and earned results on page one.' },
        { icon: 'lucide:sparkles', title: 'AI Reputation', text: 'Accurate brand information for AI tools.' },
        { icon: 'lucide:chart-column-increasing', title: 'Reporting', text: 'Rating, volume, sentiment and response times.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our Reputation Management Process, Step by Step',
      steps: [
        { title: 'Audit', text: 'We review ratings, search results and AI answers.' },
        { title: 'Fix the basics', text: 'Profiles claimed, details corrected, review links set up.' },
        { title: 'Ask', text: 'Automated review requests to every happy customer.' },
        { title: 'Respond', text: 'Every review answered quickly and fairly.' },
        { title: 'Strengthen', text: 'Positive content and profiles built for branded search.' },
        { title: 'Report', text: 'Monthly rating, sentiment and visibility updates.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'Reputation Management Case Studies and Results',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Platforms',
      heading: 'Online Review Platforms Compared',
      columns: ['', 'Google', 'Trustpilot', 'Industry sites'],
      rows: [
        ['Best for', 'Local search and map pack', 'Ecommerce and national brands', 'Sector trust, e.g. TripAdvisor, Checkatrade'],
        ['Seen by', 'Anyone searching your name', 'Online shoppers and Google', 'Buyers comparing specialists'],
        ['Impact', 'Local rankings and clicks', 'Ad and shopping star ratings', 'Shortlists and referrals'],
        ['We manage', 'Requests, replies, Q&A', 'Invitations, replies, widgets', 'Profiles, requests, replies'],
      ],
      note: 'We focus first on the platforms your customers actually check before they buy.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does Reputation Management Cost?',
      intro: 'UK reputation management typically ranges from about £300 to £2,500+ per month. Your quote depends on:',
      cards: [
        { icon: 'lucide:map-pin', title: 'Locations', text: 'One site or many branches and profiles.' },
        { icon: 'lucide:star', title: 'Review volume', text: 'How many reviews need requesting and replying.' },
        { icon: 'lucide:layers', title: 'Platforms', text: 'Google only, or several review sites.' },
        { icon: 'lucide:shield-alert', title: 'Starting point', text: 'Routine growth or recovery from a crisis.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'Reputation Management Client Reviews and Testimonials',
      reviews: [
        { name: 'Olivia B', role: 'Owner, Dental Practice', text: 'We went from 42 to over 400 Google reviews and now rank first in the map pack for our area.' },
        { name: 'Marcus J', role: 'Director, Restaurant Group', text: 'Every review across five sites gets a thoughtful reply within hours. Our average rating went from 4.1 to 4.7.' },
        { name: 'Helen P', role: 'Founder, Consultancy', text: 'An old negative article used to sit on page one. Now our branded search is entirely positive.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'Reputation Management Services by Industry',
      items: [
        { slug: 'hospitality-hotels', text: 'TripAdvisor, Google and booking-site reviews that fill tables and rooms.' },
        { slug: 'healthcare', text: 'Sensitive, compliant responses that protect patient trust.' },
        { slug: 'e-commerce', text: 'Trustpilot and product reviews that lift conversion and ad CTR.' },
        { slug: 'automotive', text: 'Dealer and garage reviews that win local searches.' },
        { slug: 'real-estate', text: 'Agent reviews that win more instructions and valuations.' },
        { slug: 'finance', text: 'Reputation care for regulated firms where trust is everything.' },
      ],
    },
  ],
  faqs: [
    { q: 'Can you remove negative reviews?', a: 'We can only report reviews that break a platform’s policies, such as fake, abusive or conflict-of-interest reviews, and we do that for you. Genuine negative reviews cannot be removed, but a professional reply and a steady flow of positive reviews reduce their impact.' },
    { q: 'Is asking for reviews allowed?', a: 'Yes, as long as you ask all customers fairly and do not offer incentives or only ask happy customers (known as review gating). Our process follows Google and Trustpilot guidelines.' },
    { q: 'How quickly can my star rating improve?', a: 'Most businesses see new reviews within the first week of automated requests. A noticeable rise in average rating usually takes 2 to 3 months, depending on how many customers you serve.' },
    { q: 'How do you improve what ChatGPT says about my business?', a: 'AI tools draw on information across the web. We correct inaccurate facts, strengthen consistent information on trusted sources and build positive coverage, then monitor how AI tools describe your brand.' },
    { q: 'Can you push down a negative news article?', a: 'We strengthen and create positive pages that compete for your branded search results, which usually moves unwanted pages lower. Where legal or policy grounds exist, we also help with removal requests.' },
    { q: 'Do you reply to reviews in our name?', a: 'Yes, in your tone of voice and following guidelines you approve. Our review management service replies to positive and neutral reviews directly, and flags sensitive complaints to you first so nothing is sent without your sign-off.' },
    { q: 'Do I need a long contract?', a: 'No. GTech Digital runs online reputation management on rolling monthly terms. Most clients stay because their star rating, review volume and brand search results keep improving, not because they are locked in.' },
    { q: 'What is a brand SERP and why does it matter?', a: 'Your brand SERP is what appears when someone searches your company name on Google. It shapes first impressions and trust, so we protect your brand reputation by strengthening official profiles, positive reviews and press that outrank unhelpful pages.' },
  ],
  related: ['search-engine-optimization', 'facebook-marketing', 'content-marketing', 'branding', 'google-ads', 'seo-backlinks'],
};

export default content;
