import type { ServiceContent } from '../types';

// Entity map: SaaS product development -> software as a service, multi-tenant architecture,
// subscription billing (Stripe Billing), plans and trials, onboarding, activation, MRR/ARR, churn,
// net revenue retention, product analytics, feature flags, SSO and teams, public API, cloud (AWS),
// auto-scaling, uptime and SLAs, SOC 2 readiness, GDPR, product roadmap, product-led growth.

const content: ServiceContent = {
  slug: 'saas-product-development',
  short: 'SaaS Product Development',
  metaTitle: 'SaaS Development Company UK | Build & Scale Your SaaS Product | GTech Digital',
  metaDescription:
    'UK SaaS development company designing and building multi-tenant SaaS products with subscription billing, onboarding and analytics, from first release to scale.',
  hero: {
    keyword: 'SaaS Product Development',
    title: 'SaaS Product Development',
    highlight: 'Built to Scale',
    lead:
      'GTech Digital is a UK SaaS development company that designs and builds subscription software with multi-tenant architecture, Stripe billing, user onboarding and analytics, from first release to thousands of paying customers.',
    motion: '/services/saas.webp',
    points: ['Free product workshop', 'Billing and onboarding built in', 'Architecture that scales'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-saas-development',
      nav: 'What is it',
      heading: 'What Is SaaS Product Development and How Does It Work?',
      paras: [
        'SaaS (software as a service) is software customers subscribe to and use online. Building SaaS means more than features: it needs multi-tenant architecture, billing, onboarding, analytics and reliability so you can grow recurring revenue with confidence.',
      ],
      bullets: [
        'Product: features, UX and onboarding that drive activation',
        'Platform: multi-tenancy, billing, APIs and security',
        'Growth: analytics, experiments and a scalable cloud',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'SaaS Product Development Results and Key Statistics',
      text: 'The numbers behind the SaaS products we build and grow.',
      stats: [
        { value: '25+', label: 'SaaS products launched' },
        { value: '99.95%', label: 'Average platform uptime' },
        { value: '9.8%', label: 'Average trial-to-paid rate' },
        { value: '118%', label: 'Average net revenue retention' },
      ],
    },
    {
      type: 'media',
      id: 'architecture',
      nav: 'Architecture',
      heading: 'SaaS Architecture, Multi-Tenancy and Cloud Hosting',
      image: '/pages/saas/stack.webp',
      alt: 'SaaS architecture layers: product app, multi-tenancy, billing, platform APIs and cloud',
      paras: ['Getting the foundations right avoids costly rebuilds later. We design for many customers, teams and plans from the start.'],
      bullets: ['Multi-tenant data isolation', 'Teams, roles and SSO', 'Public API and webhooks', 'Feature flags and safe releases'],
    },
    {
      type: 'media',
      id: 'billing',
      nav: 'Billing',
      heading: 'SaaS Subscription Billing With Stripe and Recurring Payments',
      image: '/pages/saas/mrr.webp',
      alt: 'Monthly recurring revenue growing with paying customers, monthly churn and uptime',
      flip: true,
      tone: 'grey',
      paras: ['We set up plans, trials, upgrades and invoices with Stripe, so customers can sign up and pay without your team stepping in.'],
      bullets: ['Stripe Billing and plans', 'Free trials and upgrades', 'UK VAT and invoices', 'MRR, churn and revenue reporting'],
    },
    {
      type: 'media',
      id: 'onboarding',
      nav: 'Onboarding',
      heading: 'SaaS User Onboarding, Activation and Retention',
      image: '/pages/saas/growth.webp',
      alt: 'Trial-to-paid funnel from sign-ups to activated and paid customers with time to value',
      paras: ['Most churn happens in the first week. We design onboarding that gets users to their first win fast, then measure every step.'],
      bullets: ['Guided onboarding flows', 'Product analytics and events', 'In-app messages and emails', 'A/B tests on key steps'],
    },
    {
      type: 'media',
      id: 'scale',
      nav: 'Scale',
      heading: 'SaaS Scalability, Security and Compliance',
      image: '/pages/saas/scale.webp',
      alt: 'SaaS scale gauges for uptime, API speed and error rate with security and backup checks',
      flip: true,
      tone: 'grey',
      paras: ['Your platform scales automatically, stays secure and is ready for enterprise security questionnaires.'],
      bullets: ['Auto-scaling cloud on AWS', 'Monitoring and status page', 'SOC 2-ready controls', 'GDPR and data processing'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our SaaS Product Development Services',
      cards: [
        { icon: 'lucide:lightbulb', title: 'Product Workshop', text: 'Users, value and roadmap.' },
        { icon: 'lucide:pen-tool', title: 'UX & UI Design', text: 'Clean, intuitive product.' },
        { icon: 'lucide:layers', title: 'Multi-Tenancy', text: 'Secure customer isolation.' },
        { icon: 'lucide:credit-card', title: 'Billing', text: 'Plans, trials and invoices.' },
        { icon: 'lucide:user-plus', title: 'Onboarding', text: 'Fast time to value.' },
        { icon: 'lucide:webhook', title: 'Public API', text: 'Integrations for customers.' },
        { icon: 'lucide:chart-column-increasing', title: 'Analytics', text: 'MRR, churn and usage.' },
        { icon: 'lucide:cloud', title: 'Cloud & DevOps', text: 'Scaling and monitoring.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our SaaS Product Development Process, Step by Step',
      steps: [
        { title: 'Workshop', text: 'Customers, value and pricing.' },
        { title: 'Prototype', text: 'Tested with target users.' },
        { title: 'Build', text: 'Core product and platform.' },
        { title: 'Beta', text: 'Early customers onboarded.' },
        { title: 'Launch', text: 'Billing live and marketing.' },
        { title: 'Scale', text: 'Roadmap, growth and uptime.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'SaaS Product Development Case Studies and Results',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Agency vs in-house',
      heading: 'SaaS Agency vs Hiring In-House',
      columns: ['', 'GTech Digital', 'In-house team'],
      rows: [
        ['Time to start', 'Within weeks', 'Months of hiring'],
        ['Skills', 'Design, dev, DevOps and QA', 'Depends on who you hire'],
        ['Cost', 'Flexible, by phase', 'Fixed salaries and overheads'],
        ['Hand-over', 'Code and docs to your team', 'Not applicable'],
      ],
      note: 'Many founders start with us and build an in-house team later. We help with the hand-over.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does SaaS Development Cost?',
      intro: 'UK SaaS products typically cost from about £30,000 for a first release to £150,000+ for a mature platform. Your quote depends on:',
      cards: [
        { icon: 'lucide:puzzle', title: 'Features', text: 'Scope of the first release.' },
        { icon: 'lucide:credit-card', title: 'Billing', text: 'Plans and usage pricing.' },
        { icon: 'lucide:webhook', title: 'Integrations', text: 'APIs and third parties.' },
        { icon: 'lucide:shield-check', title: 'Compliance', text: 'Enterprise security needs.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'SaaS Product Development Client Reviews and Testimonials',
      reviews: [
        { name: 'Elliot W', role: 'Founder, PropTech SaaS', text: 'We went from beta to 1,000 paying customers on the platform they built.' },
        { name: 'Hannah V', role: 'CEO, HR Software', text: 'Their onboarding redesign doubled our trial-to-paid rate.' },
        { name: 'Ravi S', role: 'CTO, Compliance SaaS', text: 'We passed our first enterprise security review without any rework.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'SaaS Product Development Services by Industry',
      items: [
        { slug: 'technology-saas', text: 'B2B SaaS from first release to scale.' },
        { slug: 'real-estate', text: 'PropTech for agents and landlords.' },
        { slug: 'finance', text: 'FinTech tools with secure data.' },
        { slug: 'healthcare', text: 'HealthTech and practice software.' },
        { slug: 'education', text: 'EdTech platforms and learning tools.' },
        { slug: 'hospitality-hotels', text: 'Booking and ordering platforms.' },
      ],
    },
  ],
  faqs: [
    { q: 'How long does it take to build a SaaS product?', a: 'A first sellable version usually takes 3 to 6 months. Many founders start with a smaller MVP in 8 to 12 weeks to validate demand first.' },
    { q: 'What is multi-tenant architecture?', a: 'It means one platform serves many customers, with each customer’s data kept securely separate. It keeps hosting costs low and updates simple.' },
    { q: 'Which technology do you use for SaaS?', a: 'Typically Next.js or React with Laravel or Node.js, PostgreSQL and AWS, chosen for speed, security and an easy hiring market.' },
    { q: 'Can you handle subscriptions and VAT?', a: 'Yes. We use Stripe Billing for plans, trials, upgrades, invoices and UK VAT.' },
    { q: 'Will we own the code and IP?', a: 'Yes. You own all the code, designs and intellectual property, which matters for investors.' },
    { q: 'Can you help after launch?', a: 'Yes. We provide ongoing development, DevOps and support, and can help you hire and hand over to an in-house team.' },
    { q: 'Do you sign NDAs?', a: 'Yes. We are happy to sign an NDA before you share your idea.' },
  ],
  related: ['mvp-development', 'web-application-development', 'api-system-integration', 'laravel-development', 'mobile-app-development', 'marketing-advisory'],
};

export default content;
