import type { ServiceContent } from '../types';

// Entity map: website optimisation for search engines (SEO), answer engines (AEO) and
// generative engines (GEO). Entities: Google Search, Bing, Google AI Overviews, ChatGPT,
// Perplexity, Gemini, Copilot, featured snippets, People Also Ask, voice search, on-page SEO
// (title tags, meta descriptions, headings, internal links, schema.org), off-page SEO
// (backlinks, digital PR, brand mentions, citations), technical SEO (crawling, indexing,
// Core Web Vitals: LCP <= 2.5s, INP <= 200ms, CLS <= 0.1), E-E-A-T, Google Search Console, GA4.

const content: ServiceContent = {
  slug: 'search-engine-optimization',
  short: 'SEO',
  metaTitle: 'SEO, AEO & GEO Agency UK | Search & AI Optimisation | GTech Digital',
  metaDescription:
    'UK SEO agency optimising websites for Google, answer engines and AI search (AEO & GEO). On-page, off-page and technical SEO that turns visibility into leads.',
  hero: {
    title: 'SEO, AEO and GEO for Google and',
    highlight: 'AI Search',
    lead:
      'We optimise your website for search engines, answer engines and generative AI, so customers find you on Google, in featured snippets and in tools like ChatGPT and Google AI Overviews.',
    motion: '/services/seo.webp',
    points: ['Free website audit', 'No lock-in contracts', 'Plain-English monthly reports'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-seo',
      nav: 'SEO, AEO & GEO',
      heading: 'What Are SEO, AEO and GEO?',
      paras: [
        'Search has changed. Customers still use Google, but many now get answers straight from featured snippets, voice assistants and AI tools. Your website needs to be optimised for all three.',
      ],
      bullets: [
        'SEO (search engine optimisation): ranking your pages in Google and Bing results',
        'AEO (answer engine optimisation): becoming the direct answer in snippets, People Also Ask and voice search',
        'GEO (generative engine optimisation): being cited by ChatGPT, Perplexity, Gemini and Google AI Overviews',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'SEO Results in Numbers',
      text: 'The numbers behind our SEO, AEO and GEO work for UK businesses.',
      stats: [
        { value: '1,200+', label: 'Keywords on page one' },
        { value: '85+', label: 'Websites optimised' },
        { value: '3.4x', label: 'Average organic traffic growth' },
        { value: '10+', label: 'Years in search' },
      ],
    },
    {
      type: 'media',
      id: 'on-page',
      nav: 'On-page SEO',
      heading: 'On-Page SEO',
      image: '/pages/seo/onpage.webp',
      alt: 'Web page annotated with title tag, meta description, headings and schema markup',
      paras: ['We optimise every important page so Google and AI tools understand exactly what it offers, and visitors know what to do next.'],
      bullets: ['Title tags and meta descriptions', 'Headings, copy and search intent', 'Internal linking and site structure', 'Schema markup for rich results'],
    },
    {
      type: 'media',
      id: 'off-page',
      nav: 'Off-page SEO',
      heading: 'Off-Page SEO and Link Building',
      image: '/pages/seo/offpage.webp',
      alt: 'Backlinks from publications and industry sites pointing to a website',
      flip: true,
      tone: 'grey',
      paras: ['Links and mentions from respected websites tell Google, and AI models, that your business is credible. We earn them the right way.'],
      bullets: ['Digital PR and expert commentary', 'Relevant UK and industry backlinks', 'Brand mentions and local citations', 'Backlink audits and clean-up'],
    },
    {
      type: 'media',
      id: 'technical',
      nav: 'Technical SEO',
      heading: 'Technical SEO',
      image: '/pages/seo/technical.webp',
      alt: 'Core Web Vitals scores and technical audit checklist',
      paras: ['If search engines cannot crawl your site, nothing else works. We fix the foundations and hit Google’s Core Web Vitals targets: LCP under 2.5s, INP under 200ms and CLS under 0.1.'],
      bullets: ['Crawling and indexation fixes', 'Page speed and Core Web Vitals', 'XML sitemaps, robots.txt and redirects', 'Mobile and JavaScript rendering'],
    },
    {
      type: 'media',
      id: 'aeo-geo',
      nav: 'AEO & GEO',
      heading: 'AEO and GEO: AI Search Optimisation',
      image: '/pages/seo/aeo-geo.webp',
      alt: 'AI assistant answer and Google AI Overview citing a business website',
      flip: true,
      tone: 'grey',
      paras: ['We structure your content so answer engines and AI models can quote it, and build the trust signals that make them choose your brand as a source.'],
      bullets: ['Question-led content and clear answers', 'FAQ, HowTo and Organization schema', 'Entity and brand consistency across the web', 'Tracking citations in AI Overviews and ChatGPT'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our SEO Services',
      cards: [
        { icon: 'lucide:search', title: 'Keyword & Intent Research', text: 'The searches and questions your buyers use, mapped to the right pages.' },
        { icon: 'lucide:file-text', title: 'On-Page Optimisation', text: 'Titles, headings, copy, internal links and schema on every key page.' },
        { icon: 'lucide:settings-2', title: 'Technical SEO', text: 'Crawlability, indexation, speed and Core Web Vitals.' },
        { icon: 'lucide:pen-line', title: 'Content Writing', text: 'Service pages and guides that build topical authority and E-E-A-T.' },
        { icon: 'lucide:link', title: 'Link Building & PR', text: 'White-hat backlinks and mentions from real UK websites.' },
        { icon: 'lucide:sparkles', title: 'AEO & GEO', text: 'Content and schema that get you cited in snippets and AI answers.' },
        { icon: 'lucide:map-pin', title: 'Local SEO', text: 'Google Business Profile, citations and reviews for the map pack.' },
        { icon: 'lucide:chart-column-increasing', title: 'Reporting', text: 'Rankings, AI citations, traffic and leads in one monthly report.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our SEO Process',
      steps: [
        { title: 'Audit', text: 'We review your site, rankings, AI visibility and competitors.' },
        { title: 'Strategy', text: 'A keyword and question map with clear targets for leads.' },
        { title: 'Fix', text: 'Technical issues resolved, fastest wins first.' },
        { title: 'Optimise', text: 'Pages and content rewritten for SEO, AEO and GEO.' },
        { title: 'Build authority', text: 'Links, PR and citations that grow trust.' },
        { title: 'Report & improve', text: 'Monthly results and next steps, in plain English.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'SEO Case Studies',
    },
    {
      type: 'table',
      id: 'seo-aeo-geo',
      nav: 'SEO vs AEO vs GEO',
      heading: 'SEO vs AEO vs GEO',
      columns: ['', 'SEO', 'AEO', 'GEO'],
      rows: [
        ['Goal', 'Rank in search results', 'Be the direct answer', 'Be cited by AI tools'],
        ['Where you appear', 'Google and Bing results', 'Snippets, People Also Ask, voice', 'AI Overviews, ChatGPT, Perplexity'],
        ['Key signals', 'Relevance, links, technical health', 'Clear answers, structure, schema', 'Authority, entities, mentions'],
        ['How we measure', 'Rankings, traffic, leads', 'Snippets won, PAA presence', 'AI citations and brand mentions'],
      ],
      note: 'We optimise for all three together, because the same strong website wins in each.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does SEO Cost in the UK?',
      intro: 'Most UK SEO retainers range from about £500 to £5,000+ per month. Your fixed quote depends on:',
      cards: [
        { icon: 'lucide:target', title: 'Competition', text: 'How strong the sites you need to outrank are.' },
        { icon: 'lucide:layout-template', title: 'Website size', text: 'Ten pages or ten thousand products.' },
        { icon: 'lucide:map-pin', title: 'Location scope', text: 'One town, several cities or the whole UK.' },
        { icon: 'lucide:pen-line', title: 'Content volume', text: 'New pages and articles needed each month.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'SEO Client Reviews',
      reviews: [
        { name: 'Derek L', role: 'Ecommerce Director', text: 'Their technical audit found problems three agencies had missed. Organic is now our biggest revenue channel.' },
        { name: 'Priya S', role: 'Clinic Owner, Manchester', text: 'We appear in the map pack for every treatment we offer, and we can see exactly how many bookings come from Google.' },
        { name: 'Tom H', role: 'Managing Partner, Law Firm', text: 'Our guides are now quoted in Google AI Overviews, and organic enquiries have more than doubled.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'SEO for Your Industry',
      items: [
        { slug: 'e-commerce', text: 'Category and product SEO that grows non-branded revenue.' },
        { slug: 'hospitality-hotels', text: '"Near me" visibility and commission-free direct bookings.' },
        { slug: 'healthcare', text: 'Expert, trustworthy content for sensitive health searches.' },
        { slug: 'real-estate', text: 'Area and property pages that capture local buyers.' },
        { slug: 'finance', text: 'Compliant, authoritative content for regulated firms.' },
        { slug: 'b2b-marketing', text: 'Thought leadership that reaches decision-makers early.' },
      ],
    },
  ],
  faqs: [
    { q: 'What is the difference between SEO, AEO and GEO?', a: 'SEO gets your pages ranking in Google and Bing. AEO (answer engine optimisation) makes your content the direct answer in featured snippets, People Also Ask and voice search. GEO (generative engine optimisation) helps AI tools such as ChatGPT, Perplexity and Google AI Overviews cite your brand. We optimise for all three.' },
    { q: 'How long does SEO take to work?', a: 'Technical and on-page improvements are often picked up within 1 to 3 months, with meaningful growth in traffic and leads typically after 3 to 6 months. Competitive national keywords can take longer.' },
    { q: 'How much does SEO cost in the UK?', a: 'Most UK SEO retainers range from about £500 per month for focused local campaigns to £5,000 or more for national and ecommerce campaigns. We give a fixed quote after a free audit.' },
    { q: 'How do you get a business cited in ChatGPT or AI Overviews?', a: 'AI tools favour clear, well-structured, expert content from brands that are mentioned consistently across trusted websites. We improve your content structure and schema, strengthen entity signals and earn mentions, then track your citations each month.' },
    { q: 'Can you guarantee first place on Google?', a: 'No honest agency can guarantee a ranking, because Google controls its algorithm. We commit to a clear strategy, measurable targets and transparent reporting.' },
    { q: 'Do I need to sign a long contract?', a: 'No. We work on rolling monthly terms after setup, although we recommend six months to give SEO a fair chance to deliver.' },
    { q: 'Will SEO work with my current website?', a: 'Usually, yes. We work with WordPress, Shopify, WooCommerce, Webflow, Wix and custom sites. If your platform is holding you back, we will explain the options.' },
  ],
  related: ['local-seo', 'ecommerce-seo', 'google-ads', 'content-marketing', 'seo-backlinks', 'reputation-management'],
};

export default content;
