import type { ServiceContent } from '../types';

// Entity map: link building / backlinks -> referring domains, domain authority (third-party
// metrics such as Ahrefs DR, Moz DA, Semrush AS), anchor text, dofollow/nofollow/sponsored,
// relevance, topical authority, digital PR, HARO-style expert commentary, linkable assets,
// guest contributions, unlinked brand mentions, broken link building, local citations (NAP),
// toxic links, disavow file, Google spam policies (link schemes), brand mentions for AI/GEO.

const content: ServiceContent = {
  slug: 'seo-backlinks',
  short: 'Link Building',
  metaTitle: 'Link Building Agency UK | White-Hat SEO Backlinks',
  metaDescription:
    'White-hat link building and digital PR for UK businesses. Relevant, editorial backlinks that lift rankings, authority and AI visibility. Free backlink audit.',
  hero: {
    keyword: 'Link Building',
    title: 'Link Building That Builds',
    highlight: 'Real Authority',
    lead:
      'GTech Digital provides white-hat link building services in the UK, earning quality backlinks through digital PR, niche outreach and local citations that raise domain authority and help websites rank higher on Google.',
    motion: '/services/backlinks.webp',
    points: ['Free backlink audit', '100% white-hat', 'Every link reported'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-link-building',
      nav: 'What is it',
      heading: 'What Is Link Building and How Does It Work?',
      paras: [
        'A backlink is a link from another website to yours. Google treats relevant links from trusted sites as votes of confidence, and AI tools use mentions across the web to decide which brands to recommend. Link building is the process of earning those votes.',
      ],
      bullets: [
        'Relevance: links from sites in your industry or location',
        'Authority: links from established, trusted publications',
        'Safety: editorial links that follow Google’s spam policies',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'Link Building Results and Key Statistics',
      text: 'The numbers behind our link building for UK businesses.',
      stats: [
        { value: '4,800+', label: 'Links earned' },
        { value: '+14', label: 'Average authority gain' },
        { value: '0', label: 'Penalties, ever' },
        { value: '320+', label: 'Press features' },
      ],
    },
    {
      type: 'media',
      id: 'digital-pr',
      nav: 'Digital PR',
      heading: 'Digital PR Link Building and Media Coverage',
      image: '/pages/backlinks/pr.webp',
      alt: 'Website earning links from national press, podcasts, trade magazines and associations',
      paras: ['We create stories, data and expert commentary that journalists want to cover, earning high-authority links and brand mentions at the same time.'],
      bullets: ['Data-led and reactive PR campaigns', 'Expert commentary for journalists', 'National, regional and trade press', 'Podcast and interview placements'],
    },
    {
      type: 'media',
      id: 'outreach',
      nav: 'Outreach',
      heading: 'Niche Edits, Guest Posts and Outreach Link Building',
      image: '/pages/backlinks/outreach.webp',
      alt: 'Outreach funnel from prospects to relevant sites, replies and links earned',
      flip: true,
      tone: 'grey',
      paras: ['We find relevant blogs, associations and partners in your sector and earn links through useful content, collaborations and fixing broken links.'],
      bullets: ['Industry and partner outreach', 'Linkable guides and tools', 'Unlinked brand mention reclamation', 'Broken link building'],
    },
    {
      type: 'media',
      id: 'local-citations',
      nav: 'Local citations',
      heading: 'Local Citation Building and Business Directory Links',
      image: '/pages/backlinks/local.webp',
      alt: 'Local citation checklist with high NAP consistency across directories',
      paras: ['For local businesses, consistent name, address and phone (NAP) listings on trusted directories strengthen map pack rankings and customer trust.'],
      bullets: ['Google, Bing and Apple listings', 'UK and industry directories', 'NAP clean-up and duplicates removed', 'Local sponsorships and community links'],
    },
    {
      type: 'media',
      id: 'audit',
      nav: 'Link audit',
      heading: 'Backlink Audit, Toxic Link Removal and Disavow',
      image: '/pages/backlinks/audit.webp',
      alt: 'Growth in healthy referring domains with toxic links removed',
      flip: true,
      tone: 'grey',
      paras: ['Spammy or paid links can hold rankings back. We audit your profile, remove what we can and protect you from risk.'],
      bullets: ['Full backlink and anchor text audit', 'Toxic link identification', 'Removal requests and disavow files', 'Competitor link gap analysis'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our Link Building Services',
      cards: [
        { icon: 'lucide:search', title: 'Backlink Audit', text: 'Your profile, risks and gaps versus competitors.' },
        { icon: 'lucide:target', title: 'Link Strategy', text: 'Target pages, anchor text and site types.' },
        { icon: 'lucide:newspaper', title: 'Digital PR', text: 'Stories and commentary that earn press links.' },
        { icon: 'lucide:mail', title: 'Outreach', text: 'Personal outreach to relevant site owners.' },
        { icon: 'lucide:file-text', title: 'Linkable Assets', text: 'Guides, data and tools worth linking to.' },
        { icon: 'lucide:map-pin', title: 'Local Citations', text: 'Accurate listings on UK directories.' },
        { icon: 'lucide:shield-check', title: 'Risk Protection', text: 'Toxic link clean-up and disavow.' },
        { icon: 'lucide:chart-column-increasing', title: 'Reporting', text: 'Every link, its source and its impact.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our Link Building Process, Step by Step',
      steps: [
        { title: 'Audit', text: 'We review your links and competitors.' },
        { title: 'Strategy', text: 'Target pages and link types agreed.' },
        { title: 'Assets', text: 'Content and stories worth linking to.' },
        { title: 'Outreach', text: 'Personal pitches to relevant sites and press.' },
        { title: 'Secure', text: 'Links checked for quality and placement.' },
        { title: 'Report', text: 'Every link listed with authority and impact.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'Link Building Case Studies and Results',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Link types',
      heading: 'Safe Link Building vs Risky Links',
      columns: ['', 'Editorial (what we build)', 'Paid or spammy links'],
      rows: [
        ['How they are earned', 'Real coverage and outreach', 'Bought, swapped or automated'],
        ['Relevance', 'Your industry or location', 'Random, unrelated sites'],
        ['Google’s view', 'Follows Search Essentials', 'Breaks spam policies'],
        ['Long-term value', 'Lasting rankings and trust', 'Risk of penalties and drops'],
      ],
      note: 'We never buy links or use private blog networks. Every link is earned and reported.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does Link Building Cost?',
      intro: 'UK link building typically ranges from about £500 to £5,000+ per month. Your quote depends on:',
      cards: [
        { icon: 'lucide:target', title: 'Competition', text: 'How many quality links your competitors have.' },
        { icon: 'lucide:link', title: 'Volume', text: 'How many links you need each month.' },
        { icon: 'lucide:newspaper', title: 'PR campaigns', text: 'Whether data-led PR is included.' },
        { icon: 'lucide:map-pin', title: 'Scope', text: 'Local, national or international targets.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'Link Building Client Reviews and Testimonials',
      reviews: [
        { name: 'Chris N', role: 'Founder, Fintech', text: 'Their data campaign landed us in three national newspapers and our key pages jumped to page one.' },
        { name: 'Amelia F', role: 'Marketing Lead, Retail', text: 'Every link is relevant and reported. No dodgy directories, just real sites our customers read.' },
        { name: 'Raj P', role: 'Owner, Law Firm', text: 'They cleaned up years of bad links and our rankings recovered within months.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'Link Building Services by Industry',
      items: [
        { slug: 'e-commerce', text: 'Product and gift-guide features that link to category pages.' },
        { slug: 'finance', text: 'Expert commentary in trusted finance and business press.' },
        { slug: 'technology-saas', text: 'Data studies and tool listings that earn tech coverage.' },
        { slug: 'travel', text: 'Destination stories and guides that travel writers link to.' },
        { slug: 'real-estate', text: 'Local market data that regional press love to cover.' },
        { slug: 'b2b-marketing', text: 'Trade publications and association links for authority.' },
      ],
    },
  ],
  faqs: [
    { q: 'Are backlinks still important for SEO?', a: 'Yes. Relevant links from trusted websites remain one of the strongest signals Google uses to rank pages, and mentions across the web also influence which brands AI tools recommend.' },
    { q: 'How many backlinks do I need?', a: 'It depends on your competitors. We compare your link profile to the sites ranking above you and plan the number and type of links needed to close the gap.' },
    { q: 'Do you buy links?', a: 'No. Buying links breaks Google’s spam policies and puts your rankings at risk. Every link we build is earned through PR, outreach and genuinely useful content.' },
    { q: 'How long until links improve rankings?', a: 'Google usually takes a few weeks to discover and credit new links. Most clients see ranking movement within 2 to 4 months of a consistent campaign.' },
    { q: 'What is a toxic backlink?', a: 'A toxic backlink comes from a spammy, unrelated or manipulative site. Too many can hurt rankings. We identify them, request removal and use a disavow file where appropriate.' },
    { q: 'Will I see every link you build?', a: 'Yes. Your monthly report lists every link we build with the website, its Domain Rating, the page it points to and the anchor text used, so you can see exactly where your SEO backlinks come from.' },
    { q: 'Do you need a contract?', a: 'No. GTech Digital builds links on rolling monthly terms. We recommend at least six months, because link building takes time to influence rankings, but you are never locked in.' },
    { q: 'How do you judge the quality of a link?', a: 'We look at relevance, real organic traffic, editorial standards and metrics such as Domain Rating and domain authority. We avoid link farms and paid guest posting networks that break Google Search Essentials, because one relevant, trusted link beats dozens of weak ones.' },
  ],
  related: ['search-engine-optimization', 'content-marketing', 'reputation-management', 'digital-advertising', 'website-design', 'google-ads'],
};

export default content;
