import type { ServiceContent } from '../types';

// Entity map: social media marketing (SMM) -> platforms (Facebook, Instagram, LinkedIn, TikTok,
// Pinterest, YouTube), organic content (posts, Reels, Stories, carousels, Lives), paid social,
// community management, influencer and UGC, social commerce, social listening, engagement rate,
// reach, impressions, follower growth, social SEO (search inside TikTok/Instagram), Meta Business Suite.

const content: ServiceContent = {
  slug: 'social-media-marketing',
  short: 'Social Media',
  metaTitle: 'Social Media Marketing Agency UK | Organic & Paid Social | GTech Digital',
  metaDescription:
    'UK social media marketing agency for Facebook, Instagram, LinkedIn, TikTok and Pinterest. Strategy, content, paid social and community management that grows sales.',
  hero: {
    keyword: 'Social Media Marketing',
    title: 'Social Media Marketing That',
    highlight: 'Grows Your Business',
    lead:
      'GTech Digital is a UK social media marketing agency that plans content, manages communities and runs paid social campaigns across Facebook, Instagram, LinkedIn, TikTok and Pinterest to grow audiences and sales.',
    motion: '/services/social.webp',
    points: ['Free social media audit', 'Content made for each platform', 'Monthly growth report'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-smm',
      nav: 'What is it',
      heading: 'What Is Social Media Marketing and How Does It Work?',
      paras: [
        'Social media marketing uses platforms like Instagram, TikTok and LinkedIn to reach, engage and convert your audience. More people now search on social platforms too, so a strong presence helps you get discovered as well as remembered.',
      ],
      bullets: [
        'Organic social: posts, Reels, Stories and community that build loyalty',
        'Paid social: targeted ads that reach new customers and drive sales',
        'Social search: content optimised to be found inside TikTok, Instagram and Pinterest',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'Social Media Results and Key Statistics',
      text: 'The numbers behind the social media we manage for UK businesses.',
      stats: [
        { value: '6', label: 'Platforms managed' },
        { value: '2,400+', label: 'Posts published a year' },
        { value: '+128%', label: 'Average engaged follower growth' },
        { value: '4.4x', label: 'Average paid social ROAS' },
      ],
    },
    {
      type: 'media',
      id: 'strategy',
      nav: 'Strategy',
      heading: 'Social Media Strategy, Audience Research and Content Planning',
      image: '/pages/social/strategy.webp',
      alt: 'Brand connected to Facebook, Instagram, LinkedIn, TikTok, Pinterest and YouTube',
      paras: ['You do not need to be everywhere. We find where your customers spend time and build a plan for each platform with clear goals.'],
      bullets: ['Audience and competitor research', 'Platform selection and goals', 'Brand voice and content pillars', 'Posting frequency and KPIs'],
    },
    {
      type: 'media',
      id: 'content',
      nav: 'Content',
      heading: 'Social Media Content Creation: Video, Reels and Graphics',
      image: '/pages/social/content.webp',
      alt: 'Weekly social content calendar with Reels, carousels, reviews and live sessions',
      flip: true,
      tone: 'grey',
      paras: ['Every platform rewards different content. We create Reels, carousels, short videos and posts designed for how people use each app.'],
      bullets: ['Short-form video and Reels', 'Carousels, graphics and copywriting', 'Monthly content calendars', 'Social SEO captions and hashtags'],
    },
    {
      type: 'media',
      id: 'paid-social',
      nav: 'Paid social',
      heading: 'Paid Social Advertising on Meta, TikTok and LinkedIn',
      image: '/pages/social/paid.webp',
      alt: 'Paid social results across Facebook, Instagram, LinkedIn, TikTok, Pinterest and YouTube',
      paras: ['Organic reach is limited. Paid social puts your best content in front of the right new audiences and turns attention into leads and sales.'],
      bullets: ['Meta, TikTok, LinkedIn and Pinterest ads', 'Lookalike and retargeting audiences', 'Lead forms and shoppable ads', 'Creative testing every week'],
    },
    {
      type: 'media',
      id: 'community',
      nav: 'Community',
      heading: 'Social Media Community Management and Engagement',
      image: '/pages/social/community.webp',
      alt: 'Engaged followers growing with fast reply times and higher engagement rate',
      flip: true,
      tone: 'grey',
      paras: ['We reply to comments and messages, join relevant conversations and report on what is growing your audience and your sales.'],
      bullets: ['Comment and inbox management', 'Social listening and trends', 'Monthly analytics and insights', 'Sales and lead attribution'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: 'Platforms',
      heading: 'What\'s Included in Our Social Media Services',
      cards: [
        { icon: 'simple-icons:facebook', title: 'Facebook Marketing', text: 'Page growth, community and lead-generating ads.' },
        { icon: 'simple-icons:instagram', title: 'Instagram Marketing', text: 'Reels, Stories, creators and Instagram Shopping.' },
        { icon: 'lucide:linkedin', title: 'LinkedIn Marketing', text: 'B2B thought leadership and lead gen campaigns.' },
        { icon: 'simple-icons:tiktok', title: 'TikTok Marketing', text: 'Trend-led video, Spark Ads and TikTok Shop.' },
        { icon: 'simple-icons:pinterest', title: 'Pinterest Marketing', text: 'Pins, boards and shopping ads that drive traffic.' },
        { icon: 'simple-icons:youtube', title: 'YouTube', text: 'Shorts and video content that ranks and converts.' },
        { icon: 'lucide:users', title: 'Influencer & UGC', text: 'Creators who make authentic content for you.' },
        { icon: 'lucide:chart-column-increasing', title: 'Social Reporting', text: 'Reach, engagement, leads and sales in one report.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our Social Media Process, Step by Step',
      steps: [
        { title: 'Audit', text: 'Your channels, audience and competitors reviewed.' },
        { title: 'Strategy', text: 'Platforms, pillars and goals agreed.' },
        { title: 'Create', text: 'A month of content planned and produced.' },
        { title: 'Publish', text: 'Posts scheduled at the best times.' },
        { title: 'Engage & amplify', text: 'Community managed and best posts boosted.' },
        { title: 'Report', text: 'Monthly insights and next month’s plan.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'Social Media Case Studies and Results',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Compare platforms',
      heading: 'Social Media Platforms Compared',
      columns: ['', 'Instagram & Facebook', 'LinkedIn', 'TikTok', 'Pinterest'],
      rows: [
        ['Best for', 'Consumer brands and local business', 'B2B and professional services', 'Reaching younger audiences fast', 'Ideas, home, food and retail'],
        ['Top formats', 'Reels, Stories, carousels', 'Documents, articles, video', 'Short video and LIVE', 'Pins and Idea Pins'],
        ['Main goal', 'Engagement and sales', 'Leads and authority', 'Reach and discovery', 'Traffic and purchases'],
      ],
      note: 'Most businesses grow fastest by mastering one or two platforms before adding more.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does Social Media Management Cost?',
      intro: 'UK social media management typically ranges from about £400 to £3,000+ per month, plus any ad spend. Your quote depends on:',
      cards: [
        { icon: 'lucide:layers', title: 'Platforms', text: 'How many channels we manage.' },
        { icon: 'lucide:calendar-days', title: 'Posting frequency', text: 'Posts, Reels and Stories per week.' },
        { icon: 'lucide:video', title: 'Content production', text: 'Photography, video and design needs.' },
        { icon: 'lucide:message-square', title: 'Community', text: 'Volume of comments and messages.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'Social Media Client Reviews and Testimonials',
      reviews: [
        { name: 'Jess A', role: 'Owner, Café Group', text: 'Our Instagram Reels now fill weekend bookings, and the team replies to every comment.' },
        { name: 'Mark L', role: 'Director, Consultancy', text: 'LinkedIn has become our best source of qualified leads since they took over.' },
        { name: 'Hannah V', role: 'Founder, Beauty Brand', text: 'TikTok creators and Spark Ads tripled our online sales in a single quarter.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'Social Media Services by Industry',
      items: [
        { slug: 'hospitality-hotels', text: 'Mouth-watering Reels and local ads that fill tables and rooms.' },
        { slug: 'e-commerce', text: 'Shoppable posts, creators and catalogue ads that drive sales.' },
        { slug: 'b2b-marketing', text: 'LinkedIn content and ads that reach decision-makers.' },
        { slug: 'education', text: 'Student-focused content on TikTok and Instagram.' },
        { slug: 'travel', text: 'Inspiring destination content that books trips.' },
        { slug: 'real-estate', text: 'Property tours and local content that wins instructions.' },
      ],
    },
  ],
  faqs: [
    { q: 'Which social media platforms should my business use?', a: 'The ones your customers use. Consumer brands usually do best on Instagram, Facebook and TikTok; B2B businesses on LinkedIn; and retail, home and food brands often see strong traffic from Pinterest. We recommend a focus after a short audit.' },
    { q: 'How often should we post?', a: 'Consistency matters more than volume. Most businesses do well with 3 to 5 posts a week per main platform, plus Stories, with more short-form video on TikTok and Instagram.' },
    { q: 'Do you create the content?', a: 'Yes. We plan, write, design and edit content, and can organise photography, video shoots and creators when needed.' },
    { q: 'How long does it take to see results?', a: 'Engagement often improves within the first month. Meaningful follower growth and sales usually build over 3 to 6 months, faster when combined with paid social.' },
    { q: 'Do you reply to comments and messages?', a: 'Yes. Community management is included, with agreed response times and escalation for anything sensitive.' },
    { q: 'How do you measure social media ROI?', a: 'We track reach, engagement and follower growth, and use tracking links, pixels and GA4 to measure the leads and sales social media drives.' },
    { q: 'Do you need a contract?', a: 'No. We work on rolling monthly terms.' },
  ],
  related: ['facebook-marketing', 'instagram-marketing', 'linkedin-marketing', 'tiktok-marketing', 'pinterest-marketing', 'paid-media'],
};

export default content;
