import type { ServiceContent } from '../types';

// Entity map: TikTok marketing -> For You feed (FYP), short-form video, trends and sounds, hooks,
// watch time and completion rate, TikTok SEO (search inside TikTok), TikTok Ads Manager, In-Feed
// ads, Spark Ads, TopView, TikTok Shop (product showcase, LIVE shopping, affiliate creators),
// TikTok Creator Marketplace, TikTok Pixel and Events API, UGC, Gen Z and millennial audiences.

const content: ServiceContent = {
  slug: 'tiktok-marketing',
  short: 'TikTok Marketing',
  metaTitle: 'TikTok Marketing Agency UK | TikTok Ads, Creators & Shop | GTech Digital',
  metaDescription:
    'UK TikTok marketing agency: trend-led video content, Spark Ads, creator campaigns and TikTok Shop that turn views into followers and sales.',
  hero: {
    eyebrow: 'TikTok Marketing Agency UK',
    title: 'TikTok Content That Turns Views Into',
    highlight: 'Sales',
    lead:
      'We create native TikTok videos, run Spark Ads and creator campaigns, and set up TikTok Shop so your brand gets discovered and bought.',
    motion: '/services/tiktok.webp',
    points: ['Free TikTok audit', 'Native, trend-led video', 'Views tracked to sales'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-tiktok-marketing',
      nav: 'What is it',
      eyebrow: 'The basics',
      heading: 'What Is TikTok Marketing?',
      paras: [
        'TikTok shows videos to people based on interest, not follower count, so even a new account can reach thousands. It is also now a search engine for many younger buyers, who look up products, places and recommendations there first.',
      ],
      bullets: [
        'Organic: native, entertaining videos built around trends and search',
        'Ads: In-Feed and Spark Ads that scale your best-performing content',
        'Commerce: creators, LIVE shopping and TikTok Shop that sell directly',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      eyebrow: 'Results in numbers',
      heading: 'Reach That Turns Into Revenue',
      text: 'The numbers behind the TikTok accounts we grow for UK brands.',
      stats: [
        { value: '38M+', label: 'Video views generated' },
        { value: '62%', label: 'Average watch-through rate' },
        { value: '3.8x', label: 'Average TikTok ad ROAS' },
        { value: '140+', label: 'Creator partnerships' },
      ],
    },
    {
      type: 'media',
      id: 'content',
      nav: 'Content',
      eyebrow: 'TikTok content',
      heading: 'Videos That Feel Native to TikTok',
      image: '/pages/tiktok/content.webp',
      alt: 'Trend-led TikTok video with views, click-through and conversion figures',
      paras: ['Polished ads look out of place on TikTok. We create authentic, fast-paced videos with hooks in the first second, built around trends and real searches.'],
      bullets: ['Trend research and scripting', 'Filming guidance and editing', 'Hooks, captions and sounds', 'TikTok SEO for in-app search'],
    },
    {
      type: 'media',
      id: 'ads',
      nav: 'TikTok ads',
      eyebrow: 'TikTok ads',
      heading: 'Scale Your Best Videos With Ads',
      image: '/pages/tiktok/ads.webp',
      alt: 'TikTok ad revenue growing with ROAS, click-through and cost per sale',
      flip: true,
      tone: 'grey',
      paras: ['We turn winning organic and creator videos into Spark Ads and test new creative every week to keep costs low.'],
      bullets: ['In-Feed and Spark Ads', 'Interest, behaviour and lookalike targeting', 'Weekly creative testing', 'TikTok Pixel and Events API'],
    },
    {
      type: 'media',
      id: 'creators',
      nav: 'Creators & Shop',
      eyebrow: 'Creators & TikTok Shop',
      heading: 'Creators and Shop That Sell for You',
      image: '/pages/tiktok/creators.webp',
      alt: 'TikTok Shop sales driven by creators, LIVE selling, product showcase and Spark Ads',
      paras: ['Creators drive most TikTok sales. We recruit affiliate creators, run LIVE shopping and manage your TikTok Shop from setup to fulfilment links.'],
      bullets: ['TikTok Shop setup and product showcase', 'Affiliate and paid creator campaigns', 'LIVE shopping events', 'UGC for ads and other channels'],
    },
    {
      type: 'media',
      id: 'analytics',
      nav: 'Analytics',
      eyebrow: 'Analytics',
      heading: 'From Views to Real Sales',
      image: '/pages/tiktok/analytics.webp',
      alt: 'TikTok funnel from video views to profile visits, clicks and orders',
      flip: true,
      tone: 'grey',
      paras: ['Views are only the start. We track watch time, profile visits, clicks and orders so you know which videos make money.'],
      bullets: ['Watch time and completion rate', 'Profile visits and follower growth', 'Clicks, Shop orders and revenue', 'Monthly content insights'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      eyebrow: 'Our TikTok service',
      heading: 'Everything Included',
      cards: [
        { icon: 'lucide:search', title: 'TikTok Audit', text: 'Account, content and competitors.' },
        { icon: 'lucide:trending-up', title: 'Trend Research', text: 'Trends and searches worth joining.' },
        { icon: 'lucide:video', title: 'Video Production', text: 'Scripts, filming guidance and editing.' },
        { icon: 'lucide:megaphone', title: 'Spark Ads', text: 'Best videos scaled with paid reach.' },
        { icon: 'lucide:users', title: 'Creator Campaigns', text: 'Creators found, briefed and managed.' },
        { icon: 'lucide:shopping-bag', title: 'TikTok Shop', text: 'Setup, showcase and affiliates.' },
        { icon: 'lucide:message-square', title: 'Community', text: 'Comments and duets handled.' },
        { icon: 'lucide:chart-column-increasing', title: 'Reporting', text: 'Views, watch time and sales.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      eyebrow: 'How we work',
      heading: 'Our TikTok Process',
      steps: [
        { title: 'Audit', text: 'Account, audience and competitors.' },
        { title: 'Ideas', text: 'Trends, hooks and video concepts.' },
        { title: 'Create', text: 'Videos filmed, edited and posted.' },
        { title: 'Partner', text: 'Creators recruited and briefed.' },
        { title: 'Scale', text: 'Winning videos boosted with Spark Ads.' },
        { title: 'Report', text: 'What worked, and what we make next.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      eyebrow: 'TikTok case studies',
      heading: 'TikTok Results We Have Delivered',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Ad types',
      eyebrow: 'Compare',
      heading: 'Which TikTok Ad Type Should You Run?',
      columns: ['', 'In-Feed Ads', 'Spark Ads', 'TikTok Shop Ads'],
      rows: [
        ['What it is', 'Ad posted from your ad account', 'Boosted organic or creator post', 'Ads that sell through your Shop'],
        ['Best for', 'Testing new offers', 'Authentic social proof', 'Direct product sales'],
        ['Key metric', 'Cost per result', 'Engagement and ROAS', 'GMV and ROAS'],
      ],
      note: 'Spark Ads using creator content usually outperform brand-made ads on TikTok.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      eyebrow: 'Investment',
      heading: 'How Much Does TikTok Marketing Cost?',
      intro: 'UK TikTok management typically ranges from about £600 to £3,500+ per month, plus ads and creator fees. Your quote depends on:',
      cards: [
        { icon: 'lucide:video', title: 'Video volume', text: 'How many videos per week.' },
        { icon: 'lucide:users', title: 'Creators', text: 'Number and size of creators.' },
        { icon: 'lucide:shopping-bag', title: 'TikTok Shop', text: 'Shop setup and affiliate management.' },
        { icon: 'lucide:wallet', title: 'Ad spend', text: 'Budget for Spark and In-Feed Ads.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      eyebrow: 'Client reviews',
      heading: 'What Our TikTok Clients Say',
      reviews: [
        { name: 'Zara H', role: 'Founder, Beauty Brand', text: 'One creator video hit 2 million views and sold out our bestseller in a weekend.' },
        { name: 'Liam C', role: 'Owner, Gym', text: 'Our TikTok went from zero to 20k local followers, and membership sign-ups followed.' },
        { name: 'Ruth B', role: 'Ecommerce Manager', text: 'TikTok Shop is now 30% of our online revenue thanks to their affiliate programme.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      eyebrow: 'Industries we serve',
      heading: 'TikTok Marketing for Your Industry',
      items: [
        { slug: 'e-commerce', text: 'TikTok Shop, creators and Spark Ads that sell products.' },
        { slug: 'hospitality-hotels', text: 'Food and venue videos that go viral locally.' },
        { slug: 'education', text: 'Student-led content that drives applications.' },
        { slug: 'travel', text: 'Destination and experience videos that book trips.' },
        { slug: 'automotive', text: 'Car reveals and walkarounds that bring in test drives.' },
        { slug: 'technology-saas', text: 'Quick demos and tips that reach young professionals.' },
      ],
    },
  ],
  faqs: [
    { q: 'Is TikTok right for my business?', a: 'If your customers are under 45, or your product is visual, fun or easy to demonstrate, TikTok can work very well. Many local and B2B businesses also succeed with educational content.' },
    { q: 'Do we need to dance or follow every trend?', a: 'No. The best TikTok content is authentic and useful. Trends help, but tips, behind-the-scenes and honest product videos often perform even better.' },
    { q: 'What are Spark Ads?', a: 'Spark Ads let you boost an existing organic TikTok post, from your account or a creator’s, as an ad. They keep the likes and comments, which builds trust and usually lowers costs.' },
    { q: 'How do I sell on TikTok Shop?', a: 'You set up a TikTok Shop account, list your products and connect fulfilment. Creators can then tag your products in videos and LIVEs for commission. We handle the setup and creator programme.' },
    { q: 'How often should we post on TikTok?', a: 'Three to seven videos a week is a good target. Consistency helps TikTok learn who your content is for.' },
    { q: 'How do you measure TikTok results?', a: 'We track views, watch time, followers and, through the TikTok Pixel, Events API and Shop data, the traffic and sales your videos drive.' },
    { q: 'Do you need a contract?', a: 'No. We work on rolling monthly terms.' },
  ],
  related: ['instagram-marketing', 'facebook-marketing', 'paid-media', 'content-marketing', 'ecommerce-development', 'pinterest-marketing'],
};

export default content;
