import type { ServiceContent } from '../types';

// Entity map: web application development -> web app, customer portal, staff portal, dashboard,
// single-page application (SPA), progressive web app (PWA), front end (React, Next.js, Vue),
// back end (Laravel, Node.js, .NET), PostgreSQL, authentication (SSO, 2FA), role-based access,
// audit logs, cloud hosting (AWS, Azure), scalability, OWASP security, accessibility, UX.

const content: ServiceContent = {
  slug: 'web-application-development',
  short: 'Web Application Development',
  metaTitle: 'Web Application Development Company UK | Portals & Dashboards | GTech Digital',
  metaDescription:
    'UK web application development company building secure customer portals, staff dashboards and business tools with React, Next.js, Laravel and Node.js.',
  hero: {
    title: 'Web Application Development',
    highlight: 'for Your Business',
    lead:
      'We build secure web applications, portals and dashboards that your customers and staff can use from any browser, on any device.',
    motion: '/services/webapp.webp',
    points: ['Free discovery call', 'Clickable prototype first', 'Secure and scalable'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-web-application-development',
      nav: 'What is it',
      heading: 'What Is a Web Application?',
      paras: [
        'A web application is software that runs in the browser, like a customer portal, booking system or internal dashboard. Unlike a website, it lets users log in, do work and manage data, with nothing to install and updates delivered instantly.',
      ],
      bullets: [
        'Customer portals: accounts, orders, bookings and documents',
        'Staff tools: dashboards, workflows and approvals',
        'Progressive web apps: installable apps that work on any device',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'Web Application Development Results in Numbers',
      text: 'The numbers behind the web applications we build and run.',
      stats: [
        { value: '60+', label: 'Web apps launched' },
        { value: '120ms', label: 'Average median response' },
        { value: '99.98%', label: 'Average uptime' },
        { value: '9h', label: 'Average admin hours saved weekly' },
      ],
    },
    {
      type: 'media',
      id: 'portals',
      nav: 'Portals',
      heading: 'Customer Portals and Dashboards',
      image: '/pages/webapp/portal.webp',
      alt: 'Web portal annotated with secure sign-in, role-based menu, live dashboard, approvals and reports',
      paras: ['We design around the tasks people do most, so they get them done in fewer clicks and need less support.'],
      bullets: ['Customer and partner portals', 'Staff dashboards and workflows', 'Approvals, tasks and notifications', 'Reports and exports'],
    },
    {
      type: 'media',
      id: 'stack',
      nav: 'Technology',
      heading: 'Web Application Technology Stack',
      image: '/pages/webapp/stack.webp',
      alt: 'Web application stack with front end, back end, data, integrations and cloud layers',
      flip: true,
      tone: 'grey',
      paras: ['We use widely supported technology so your app is fast today and easy for any developer to maintain tomorrow.'],
      bullets: ['React, Next.js and Vue front ends', 'Laravel, Node.js and .NET back ends', 'PostgreSQL, MySQL and Redis', 'AWS and Azure cloud hosting'],
    },
    {
      type: 'media',
      id: 'performance',
      nav: 'Performance',
      heading: 'Web App Performance and Live Data',
      image: '/pages/webapp/dashboard.webp',
      alt: 'Web app dashboard with jobs completed rising, active users, response time and admin time saved',
      paras: ['Your team gets live numbers instead of weekly spreadsheets, and pages respond instantly, even with thousands of users.'],
      bullets: ['Real-time dashboards', 'Fast search and filters', 'Caching and background jobs', 'Auto-scaling infrastructure'],
    },
    {
      type: 'media',
      id: 'security',
      nav: 'Security',
      heading: 'Web Application Security',
      image: '/pages/webapp/security.webp',
      alt: 'Web app security checklist with SSO, permissions, encryption, audit logs and OWASP testing',
      flip: true,
      tone: 'grey',
      paras: ['Your data and your customers’ data are protected from day one, with access controls and testing built into every release.'],
      bullets: ['SSO and two-factor sign-in', 'Role-based permissions', 'Encryption and audit logs', 'OWASP testing and GDPR'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our Web Application Development Services',
      cards: [
        { icon: 'lucide:search', title: 'Discovery', text: 'Users, tasks and requirements.' },
        { icon: 'lucide:pen-tool', title: 'UX & UI Design', text: 'Clickable prototype first.' },
        { icon: 'lucide:monitor', title: 'Front End', text: 'React, Next.js or Vue.' },
        { icon: 'lucide:server', title: 'Back End', text: 'Laravel, Node.js or .NET.' },
        { icon: 'lucide:webhook', title: 'Integrations', text: 'CRM, payments and more.' },
        { icon: 'lucide:shield-check', title: 'Security', text: 'SSO, roles and audit logs.' },
        { icon: 'lucide:flask-conical', title: 'Testing', text: 'Automated and user testing.' },
        { icon: 'lucide:cloud', title: 'Hosting & Support', text: 'Monitored cloud hosting.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our Web Application Development Process',
      steps: [
        { title: 'Discover', text: 'Goals, users and workflows.' },
        { title: 'Prototype', text: 'Clickable design tested.' },
        { title: 'Plan', text: 'Scope and fixed-price phases.' },
        { title: 'Build', text: 'Sprints with demos.' },
        { title: 'Launch', text: 'Data, training and go-live.' },
        { title: 'Improve', text: 'Analytics and new features.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'Web Application Development Case Studies',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Web app vs mobile app',
      heading: 'Web App vs Mobile App',
      columns: ['', 'Web app', 'Mobile app'],
      rows: [
        ['Access', 'Any browser, no install', 'App Store and Google Play'],
        ['Updates', 'Instant for everyone', 'Through store releases'],
        ['Device features', 'Most, via PWA', 'Full camera, GPS and offline'],
        ['Cost', 'One codebase', 'Higher for two platforms'],
      ],
      note: 'Many products start as a web app, then add a mobile app once usage grows.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does a Web Application Cost?',
      intro: 'UK web applications typically range from about £12,000 to £80,000+, delivered in phases. Your quote depends on:',
      cards: [
        { icon: 'lucide:layout-dashboard', title: 'Screens', text: 'Number and complexity.' },
        { icon: 'lucide:users', title: 'User roles', text: 'Who sees and does what.' },
        { icon: 'lucide:webhook', title: 'Integrations', text: 'Systems to connect.' },
        { icon: 'lucide:shield-check', title: 'Security', text: 'Compliance requirements.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'Web Application Development Client Reviews',
      reviews: [
        { name: 'Karen S', role: 'Director, Training Provider', text: 'Our learner portal cut admin calls in half within the first term.' },
        { name: 'Jon B', role: 'COO, Field Services', text: 'Engineers and office staff finally work from the same live data.' },
        { name: 'Ayesha R', role: 'Founder, Lettings Agency', text: 'Landlords love the portal. It sets us apart from every other agent in town.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'Web Application Development for Your Industry',
      items: [
        { slug: 'real-estate', text: 'Landlord, tenant and agent portals.' },
        { slug: 'education', text: 'Learner portals and course management.' },
        { slug: 'healthcare', text: 'Patient booking and practice dashboards.' },
        { slug: 'finance', text: 'Client portals with secure documents.' },
        { slug: 'b2b-marketing', text: 'Partner and reseller portals.' },
        { slug: 'automotive', text: 'Dealer, service and fleet systems.' },
      ],
    },
  ],
  faqs: [
    { q: 'What is the difference between a website and a web application?', a: 'A website mainly shares information. A web application lets users log in and do things, such as book, order, manage accounts or run business processes.' },
    { q: 'How long does it take to build a web app?', a: 'A first version usually takes 8 to 16 weeks, depending on features. We release in phases so you get value early.' },
    { q: 'Can the web app work on phones?', a: 'Yes. Every app we build is responsive, and we can make it an installable progressive web app (PWA).' },
    { q: 'Can it connect to our existing systems?', a: 'Yes. We integrate with CRMs, accounting, payment and industry systems through APIs.' },
    { q: 'How do you keep the app secure?', a: 'We use secure sign-in, role-based access, encryption, audit logs and OWASP testing, and keep everything patched after launch.' },
    { q: 'Who owns the code?', a: 'You do. We hand over the full source code and documentation.' },
    { q: 'Do you host and support the app?', a: 'Yes. We offer monitored cloud hosting, maintenance and ongoing development.' },
  ],
  related: ['laravel-development', 'mobile-app-development', 'api-system-integration', 'saas-product-development', 'crm-erp-development', 'mvp-development'],
};

export default content;
