import type { ServiceContent } from '../types';

// Entity map: web design and development -> website (pages, templates), UX/UI design, responsive
// design, CMS (WordPress, headless), frameworks (Next.js, Laravel, PHP), ecommerce (Shopify,
// WooCommerce), Core Web Vitals (LCP, INP, CLS), hosting, SSL, accessibility (WCAG 2.2), technical
// SEO, schema markup, GDPR cookie consent, conversion rate, maintenance and support.

const content: ServiceContent = {
  slug: 'web-design-development',
  short: 'Web Design & Development',
  metaTitle: 'Web Design & Development Agency UK | Fast, SEO-Ready Websites | GTech Digital',
  metaDescription:
    'UK web design and development agency building fast, secure, SEO-ready websites and online stores on WordPress, Laravel, Next.js and Shopify that turn visitors into customers.',
  hero: {
    keyword: 'Web Design and Development',
    title: 'Web Design and Development',
    highlight: 'That Wins Customers',
    lead:
      'GTech Digital is a UK web design and development agency that builds fast, secure, SEO-ready websites and online stores on WordPress, Laravel, Next.js and Shopify, designed to turn visitors into enquiries and sales.',
    motion: '/services/web.webp',
    points: ['Free website review', 'Mobile-first and SEO-ready', 'You own the code and content'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-web-design-development',
      nav: 'What is it',
      heading: 'What Is Web Design and Development and How Does It Work?',
      paras: [
        'Web design is how your website looks, reads and guides visitors. Web development is the code, content management system and hosting that make it fast, secure and easy to update. A good website needs both, built around what your customers want to do.',
      ],
      bullets: [
        'Design: UX research, page layouts and a brand-led interface',
        'Development: WordPress, Laravel, Next.js and Shopify builds',
        'Growth: speed, technical SEO and conversion built in from day one',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'Web Design & Development Results and Key Statistics',
      text: 'The numbers behind the websites we design and build for UK businesses.',
      stats: [
        { value: '180+', label: 'Websites launched' },
        { value: '1.4s', label: 'Average load time' },
        { value: '+64%', label: 'Average enquiry growth' },
        { value: '99.98%', label: 'Hosting uptime' },
      ],
    },
    {
      type: 'media',
      id: 'design',
      nav: 'Design',
      heading: 'Website Design: UX, UI and Mobile-First Layouts',
      image: '/pages/web/design.webp',
      alt: 'Website page annotated with headline, value proposition, hero visual, trust signals and call to action',
      paras: ['Every page has a job. We plan the structure, write clear headlines and place trust signals and calls to action where they work best.'],
      bullets: ['UX research and sitemaps', 'Wireframes and UI design', 'Brand-led visuals and copy', 'Conversion-focused layouts'],
    },
    {
      type: 'media',
      id: 'development',
      nav: 'Development',
      heading: 'Website Development With WordPress, Next.js and Laravel',
      image: '/pages/web/build.webp',
      alt: 'Code editor with load time, security grade and mobile-friendly scores',
      flip: true,
      tone: 'grey',
      paras: ['We choose the platform that fits your goals, from WordPress for easy editing to Laravel or Next.js for custom features.'],
      bullets: ['WordPress and headless CMS', 'Laravel, PHP and Next.js', 'Integrations with CRM and payments', 'Staging, testing and version control'],
    },
    {
      type: 'media',
      id: 'ecommerce',
      nav: 'Ecommerce',
      heading: 'Ecommerce Website Development With Shopify and WooCommerce',
      image: '/pages/web/ecommerce.webp',
      alt: 'Online revenue chart with conversion rate, average order value and repeat customers',
      paras: ['We build Shopify and WooCommerce stores with fast product pages, simple checkout and the integrations you need to run day to day.'],
      bullets: ['Shopify and WooCommerce', 'Product, category and checkout UX', 'Payments, shipping and VAT', 'Stock, accounting and email integrations'],
    },
    {
      type: 'media',
      id: 'performance',
      nav: 'Performance',
      heading: 'Website Speed, Technical SEO and Security',
      image: '/pages/web/performance.webp',
      alt: 'Core Web Vitals gauges with security, backup, accessibility and SEO checks',
      flip: true,
      tone: 'grey',
      paras: ['Google rewards fast, accessible websites. We build to pass Core Web Vitals and keep your site secure and backed up.'],
      bullets: ['Core Web Vitals (LCP, INP, CLS)', 'Technical SEO and schema', 'WCAG 2.2 accessibility', 'SSL, backups and monitoring'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: 'Our services',
      heading: 'What\'s Included in Our Web Design & Development Services',
      cards: [
        { icon: 'lucide:palette', title: 'Website Design', text: 'UX and UI built around your goals.' },
        { icon: 'simple-icons:wordpress', title: 'WordPress', text: 'Custom themes your team can edit.' },
        { icon: 'simple-icons:laravel', title: 'Laravel', text: 'Custom web apps and portals.' },
        { icon: 'simple-icons:php', title: 'PHP Development', text: 'Bespoke builds and legacy upgrades.' },
        { icon: 'lucide:layout-template', title: 'CMS Development', text: 'Content platforms without code.' },
        { icon: 'lucide:shopping-cart', title: 'Ecommerce', text: 'Shopify and WooCommerce stores.' },
        { icon: 'lucide:search', title: 'SEO-Ready Build', text: 'Speed, schema and clean structure.' },
        { icon: 'lucide:wrench', title: 'Maintenance', text: 'Updates, backups and support.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our Web Design & Development Process, Step by Step',
      steps: [
        { title: 'Discover', text: 'Goals, audience and competitors.' },
        { title: 'Plan', text: 'Sitemap, content and wireframes.' },
        { title: 'Design', text: 'Brand-led page designs approved.' },
        { title: 'Build', text: 'Developed, tested and optimised.' },
        { title: 'Launch', text: 'Redirects, tracking and go-live.' },
        { title: 'Grow', text: 'Support, updates and improvements.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'Web Design & Development Case Studies and Results',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Platforms',
      heading: 'WordPress vs Shopify vs Custom Websites',
      columns: ['', 'WordPress', 'Shopify', 'Custom (Laravel / Next.js)'],
      rows: [
        ['Best for', 'Brochure sites and content', 'Online stores', 'Portals and unique features'],
        ['Editing', 'Easy page builder', 'Easy product admin', 'Custom admin panel'],
        ['Cost to build', 'Lower', 'Lower to medium', 'Higher'],
        ['Flexibility', 'High with plugins', 'Medium with apps', 'Unlimited'],
      ],
      note: 'Not sure? We recommend a platform after your free website review.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does a Website Cost?',
      intro: 'UK business websites typically range from about £2,500 to £25,000+, depending on size and features. Your quote depends on:',
      cards: [
        { icon: 'lucide:file-text', title: 'Number of pages', text: 'Templates and unique layouts.' },
        { icon: 'lucide:puzzle', title: 'Features', text: 'Booking, portals or custom tools.' },
        { icon: 'lucide:shopping-cart', title: 'Ecommerce', text: 'Products, payments and shipping.' },
        { icon: 'lucide:pen-line', title: 'Content', text: 'Copywriting, photos and migration.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'Web Design & Development Client Reviews and Testimonials',
      reviews: [
        { name: 'Helen G', role: 'Director, Law Firm', text: 'Our new site loads instantly and enquiries went up within the first month.' },
        { name: 'Raj P', role: 'Founder, Retail Brand', text: 'The Shopify store they built is easy to manage and sales have nearly doubled.' },
        { name: 'Tom W', role: 'MD, Construction', text: 'Clear process, on budget and the site finally reflects the quality of our work.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'Web Design & Development Services by Industry',
      items: [
        { slug: 'e-commerce', text: 'Fast stores with simple checkout.' },
        { slug: 'healthcare', text: 'Clinic sites with online booking and compliance.' },
        { slug: 'hospitality-hotels', text: 'Restaurant and hotel sites that take bookings.' },
        { slug: 'real-estate', text: 'Property search and valuation tools.' },
        { slug: 'finance', text: 'Secure, compliant sites for financial firms.' },
        { slug: 'technology-saas', text: 'Product sites that convert trials and demos.' },
      ],
    },
  ],
  faqs: [
    { q: 'How long does it take to build a website?', a: 'A typical business website takes 4 to 8 weeks from kick-off to launch. Larger ecommerce or custom builds usually take 8 to 16 weeks.' },
    { q: 'Which platform should we use?', a: 'WordPress suits most brochure and content sites, Shopify suits most online stores, and Laravel or Next.js suit portals and custom features. We recommend the best fit after reviewing your needs.' },
    { q: 'Will our new website be SEO-friendly?', a: 'Yes. Every build includes clean structure, fast loading, schema markup, metadata and 301 redirects from your old URLs so you keep your rankings.' },
    { q: 'Can we update the website ourselves?', a: 'Yes. We build easy editing into every site and train your team, so you can change text, images and pages without code.' },
    { q: 'Do you provide hosting and maintenance?', a: 'Yes. We offer managed UK hosting, updates, backups, security monitoring and support on monthly plans.' },
    { q: 'Do we own the website?', a: 'Yes. You own the design, code, content and domain once the project is paid for.' },
    { q: 'Do you redesign existing websites?', a: 'Yes. We review what works today, keep your SEO value and rebuild for speed, clarity and conversion.' },
  ],
  related: ['website-design', 'wordpress-development', 'ecommerce-development', 'laravel-development', 'website-maintenance', 'search-engine-optimization'],
};

export default content;
