import type { ServiceContent } from '../types';

// Entity map: website maintenance -> care plan, core/theme/plugin updates, PHP version updates,
// security monitoring, malware scanning, web application firewall (WAF), SSL certificates,
// off-site backups, disaster recovery (RTO), uptime monitoring, Core Web Vitals, broken links,
// form testing, content updates, support hours, SLA response times, GDPR, hosting.

const content: ServiceContent = {
  slug: 'website-maintenance',
  short: 'Website Maintenance',
  metaTitle: 'Website Maintenance Services UK | Updates, Security & Support | GTech Digital',
  metaDescription:
    'UK website maintenance and support plans: updates, security monitoring, daily backups, uptime checks, speed tuning and content changes for one fixed monthly fee.',
  hero: {
    eyebrow: 'Website Maintenance Services UK',
    title: 'Website Care That Keeps You',
    highlight: 'Secure, Fast and Online',
    lead:
      'We look after your website every month, with updates, security, backups, monitoring and small changes, so it stays fast, safe and working while you run your business.',
    motion: '/services/maintenance.webp',
    points: ['Free website health check', 'Fixed monthly fee', 'UK support team'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-website-maintenance',
      nav: 'What is it',
      eyebrow: 'The basics',
      heading: 'What Is Website Maintenance?',
      paras: [
        'Websites need regular care. Software updates, security threats, expired certificates and broken forms can quietly cost you customers. Website maintenance is a monthly plan that prevents these problems and fixes them fast when they happen.',
      ],
      bullets: [
        'Protect: updates, security scans and a firewall',
        'Recover: daily off-site backups and fast restores',
        'Improve: speed checks, fixes and content changes',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      eyebrow: 'Results in numbers',
      heading: 'Peace of Mind, Measured',
      text: 'The numbers behind the websites on our care plans.',
      stats: [
        { value: '99.98%', label: 'Average uptime' },
        { value: '< 15 min', label: 'Response to outages' },
        { value: '365', label: 'Restore points a year' },
        { value: '0', label: 'Unplanned outages last year' },
      ],
    },
    {
      type: 'media',
      id: 'security',
      nav: 'Security',
      eyebrow: 'Updates & security',
      heading: 'Patched, Scanned and Protected',
      image: '/pages/maintenance/security.webp',
      alt: 'Monthly maintenance checklist with updates, malware scan, SSL, firewall and admin audit',
      paras: ['Most hacks exploit outdated software. We test and apply updates safely, scan for malware and block attacks before they reach you.'],
      bullets: ['Core, theme and plugin updates', 'Malware and vulnerability scans', 'Web application firewall', 'SSL and admin user audits'],
    },
    {
      type: 'media',
      id: 'uptime',
      nav: 'Monitoring',
      eyebrow: 'Uptime monitoring',
      heading: 'We Know Before Your Customers Do',
      image: '/pages/maintenance/uptime.webp',
      alt: 'Uptime chart at 99.98% with 60-second checks and fast response times',
      flip: true,
      tone: 'grey',
      paras: ['We check your site every minute. If it goes down, our team is alerted and starts fixing it straight away.'],
      bullets: ['60-second uptime checks', 'Instant alerts to our team', 'Hosting and DNS monitoring', 'Domain and SSL expiry alerts'],
    },
    {
      type: 'media',
      id: 'backups',
      nav: 'Backups',
      eyebrow: 'Backups & recovery',
      heading: 'Backups You Can Actually Restore',
      image: '/pages/maintenance/backups.webp',
      alt: 'Backup plan with daily, off-site, encrypted backups, restore time and monthly tests',
      paras: ['Backups only matter if they work. We keep daily encrypted copies off-site and test restores every month.'],
      bullets: ['Daily automatic backups', 'Two off-site locations', 'Encrypted at rest', 'Monthly restore tests'],
    },
    {
      type: 'media',
      id: 'speed',
      nav: 'Speed & fixes',
      eyebrow: 'Speed & improvements',
      heading: 'A Website That Gets Better Every Month',
      image: '/pages/maintenance/speed.webp',
      alt: 'Monthly speed checks with Core Web Vitals, image compression, database clean-up and form testing',
      flip: true,
      tone: 'grey',
      paras: ['We keep pages fast, test your forms and use your support hours for content updates and small improvements.'],
      bullets: ['Core Web Vitals checks', 'Image and database optimisation', 'Form and checkout testing', 'Content updates included'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      eyebrow: 'Our care plans',
      heading: 'Everything Included',
      cards: [
        { icon: 'lucide:refresh-cw', title: 'Updates', text: 'Tested and applied safely.' },
        { icon: 'lucide:shield-check', title: 'Security', text: 'Scans, firewall and hardening.' },
        { icon: 'lucide:database', title: 'Backups', text: 'Daily, off-site and tested.' },
        { icon: 'lucide:activity', title: 'Uptime Monitoring', text: 'Checked every minute.' },
        { icon: 'lucide:zap', title: 'Speed Checks', text: 'Core Web Vitals kept green.' },
        { icon: 'lucide:pen-line', title: 'Content Changes', text: 'Support hours every month.' },
        { icon: 'lucide:life-buoy', title: 'UK Support', text: 'Email and phone help.' },
        { icon: 'lucide:file-text', title: 'Monthly Report', text: 'What we did and found.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      eyebrow: 'How we work',
      heading: 'How Our Care Plans Work',
      steps: [
        { title: 'Health check', text: 'Full review of your site.' },
        { title: 'Fix', text: 'Urgent issues resolved first.' },
        { title: 'Secure', text: 'Backups, firewall and monitoring.' },
        { title: 'Maintain', text: 'Monthly updates and checks.' },
        { title: 'Support', text: 'Changes and help on request.' },
        { title: 'Report', text: 'Clear monthly summary.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      eyebrow: 'Maintenance case studies',
      heading: 'Websites We Look After',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Care plans',
      eyebrow: 'Compare',
      heading: 'Which Care Plan Do You Need?',
      columns: ['', 'Essential', 'Growth', 'Business'],
      rows: [
        ['Updates and backups', 'Monthly, daily backups', 'Weekly, daily backups', 'Weekly, hourly backups'],
        ['Uptime monitoring', 'Yes', 'Yes', 'Yes, with priority response'],
        ['Support hours', '1 hour', '3 hours', '8 hours'],
        ['Best for', 'Brochure sites', 'Busy business sites', 'Stores and web apps'],
      ],
      note: 'Unused support hours roll over for one month.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      eyebrow: 'Investment',
      heading: 'How Much Does Website Maintenance Cost?',
      intro: 'UK website maintenance plans typically range from about £50 to £500+ per month. Your quote depends on:',
      cards: [
        { icon: 'lucide:layers', title: 'Platform', text: 'WordPress, Laravel or custom.' },
        { icon: 'lucide:shopping-cart', title: 'Ecommerce', text: 'Stores need extra checks.' },
        { icon: 'lucide:clock', title: 'Support hours', text: 'Changes each month.' },
        { icon: 'lucide:bell', title: 'Response time', text: 'Standard or priority SLA.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      eyebrow: 'Client reviews',
      heading: 'What Our Care Plan Clients Say',
      reviews: [
        { name: 'Diane C', role: 'Owner, Florist', text: 'They spotted our site was down at 6am and had it back before we opened.' },
        { name: 'Matt J', role: 'Director, Accountancy', text: 'No more worrying about updates or hacks. It just works.' },
        { name: 'Leah O', role: 'Ecommerce Manager', text: 'Our checkout is tested every month and small changes are done within a day.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      eyebrow: 'Industries we serve',
      heading: 'Website Maintenance for Your Industry',
      items: [
        { slug: 'e-commerce', text: 'Checkout and payment testing every month.' },
        { slug: 'healthcare', text: 'Secure booking forms and patient data.' },
        { slug: 'finance', text: 'Security and compliance kept up to date.' },
        { slug: 'hospitality-hotels', text: 'Booking systems kept online at busy times.' },
        { slug: 'education', text: 'Large sites kept fast and accessible.' },
        { slug: 'b2b-marketing', text: 'Lead forms that always work.' },
      ],
    },
  ],
  faqs: [
    { q: 'Why does my website need maintenance?', a: 'Software, plugins and servers change constantly. Without updates and monitoring, sites become slow, insecure and can break without warning.' },
    { q: 'Do you maintain websites you did not build?', a: 'Yes. We start with a health check, fix any urgent issues and then add your site to a care plan.' },
    { q: 'What happens if my site is hacked?', a: 'We clean it, restore from a clean backup if needed and close the security gap. Hack clean-up is included on our care plans.' },
    { q: 'How quickly do you respond?', a: 'Outages get a response within 15 minutes during UK business hours. Change requests are usually completed within one to two working days.' },
    { q: 'Which platforms do you support?', a: 'WordPress, WooCommerce, Laravel, PHP, Shopify and most custom websites.' },
    { q: 'Is hosting included?', a: 'We can provide managed UK hosting or maintain your site on your existing host.' },
    { q: 'Do you need a contract?', a: 'No. Our care plans run on rolling monthly terms.' },
  ],
  related: ['wordpress-development', 'website-design', 'ecommerce-development', 'php-development', 'laravel-development', 'search-engine-optimization'],
};

export default content;
