import type { ServiceContent } from '../types';

// Entity map: website design -> UX (user research, user journeys, information architecture,
// wireframes), UI (visual design, typography, colour), design system (components, tokens),
// responsive/mobile-first design, Figma prototypes, usability testing, conversion-centred design
// (CTA, trust signals, social proof), accessibility (WCAG 2.2 AA), brand consistency, redesign.

const content: ServiceContent = {
  slug: 'website-design',
  short: 'Website Design',
  metaTitle: 'Website Design Agency UK | UX & UI Design That Converts | GTech Digital',
  metaDescription:
    'UK website design agency creating user-friendly, accessible and brand-led websites, with UX research, Figma prototypes and design systems that turn visitors into customers.',
  hero: {
    eyebrow: 'Website Design Agency UK',
    title: 'Website Design That Turns Visitors Into',
    highlight: 'Customers',
    lead:
      'We design clear, beautiful and accessible websites around how your customers think, so they find what they need and take action.',
    motion: '/services/webdesign.webp',
    points: ['Free design consultation', 'Clickable Figma prototype', 'Mobile-first and accessible'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-website-design',
      nav: 'What is it',
      eyebrow: 'The basics',
      heading: 'What Is Website Design?',
      paras: [
        'Website design covers how your site works (UX) and how it looks (UI). Good design makes your business look credible, makes information easy to find and guides visitors towards an enquiry or purchase, on every screen size.',
      ],
      bullets: [
        'UX design: research, user journeys and wireframes',
        'UI design: visual design, typography and imagery',
        'Design systems: reusable components that keep your site consistent',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      eyebrow: 'Results in numbers',
      heading: 'Design That Pays for Itself',
      text: 'The numbers behind the websites we redesign for UK businesses.',
      stats: [
        { value: '+71%', label: 'Average lead growth after redesign' },
        { value: '-38%', label: 'Average bounce rate reduction' },
        { value: '98%', label: 'Average accessibility score' },
        { value: '200+', label: 'Websites designed' },
      ],
    },
    {
      type: 'media',
      id: 'ux',
      nav: 'UX design',
      eyebrow: 'UX design',
      heading: 'Built Around Your Customers',
      image: '/pages/design/ux.webp',
      alt: 'Website page annotated with navigation, hierarchy, imagery, scannable sections, social proof and CTA',
      paras: ['We research your customers and plan every page around their questions, so the journey to enquiry feels natural.'],
      bullets: ['Customer and competitor research', 'Sitemaps and user journeys', 'Wireframes and content plan', 'Clickable Figma prototypes'],
    },
    {
      type: 'media',
      id: 'design-system',
      nav: 'UI & design system',
      eyebrow: 'UI & design system',
      heading: 'A Look That Is Unmistakably You',
      image: '/pages/design/system.webp',
      alt: 'Design system with brand palette, font scale, buttons, layouts, icons and mobile patterns',
      flip: true,
      tone: 'grey',
      paras: ['We turn your brand into a modern interface and a design system, so every new page looks consistent.'],
      bullets: ['Visual design from your brand', 'Typography, colour and icons', 'Reusable components', 'Developer-ready Figma files'],
    },
    {
      type: 'media',
      id: 'conversion',
      nav: 'Conversion',
      eyebrow: 'Conversion-centred design',
      heading: 'More Enquiries From the Same Traffic',
      image: '/pages/design/conversion.webp',
      alt: 'Redesign funnel from visitors to enquiries with higher enquiry rate and lower bounce rate',
      paras: ['Design is not just looks. We place clear calls to action, trust signals and proof where they lift enquiries the most.'],
      bullets: ['Clear calls to action', 'Reviews, logos and case studies', 'Simple, short forms', 'A/B testing after launch'],
    },
    {
      type: 'media',
      id: 'accessibility',
      nav: 'Accessibility',
      eyebrow: 'Responsive & accessible',
      heading: 'Works for Everyone, on Every Device',
      image: '/pages/design/accessibility.webp',
      alt: 'Accessibility checklist with WCAG 2.2 AA contrast, keyboard navigation and responsive layouts',
      flip: true,
      tone: 'grey',
      paras: ['Most visits are on mobile, and one in five people has a disability. We design for both from the start.'],
      bullets: ['Mobile-first layouts', 'WCAG 2.2 AA accessibility', 'Readable type and contrast', 'Keyboard and screen reader friendly'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      eyebrow: 'Our design service',
      heading: 'Everything Included',
      cards: [
        { icon: 'lucide:search', title: 'Research', text: 'Customers, competitors and goals.' },
        { icon: 'lucide:git-branch', title: 'User Journeys', text: 'Sitemaps and key paths.' },
        { icon: 'lucide:layout-template', title: 'Wireframes', text: 'Structure before visuals.' },
        { icon: 'lucide:palette', title: 'UI Design', text: 'Brand-led page designs.' },
        { icon: 'lucide:mouse-pointer-click', title: 'Prototype', text: 'Clickable Figma prototype.' },
        { icon: 'lucide:shapes', title: 'Design System', text: 'Reusable components.' },
        { icon: 'lucide:accessibility', title: 'Accessibility', text: 'WCAG 2.2 AA checked.' },
        { icon: 'lucide:pen-line', title: 'Copywriting', text: 'Clear, SEO-friendly words.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      eyebrow: 'How we work',
      heading: 'Our Design Process',
      steps: [
        { title: 'Discover', text: 'Workshop on goals and customers.' },
        { title: 'Structure', text: 'Sitemap and wireframes.' },
        { title: 'Style', text: 'Visual direction agreed.' },
        { title: 'Design', text: 'Full pages for desktop and mobile.' },
        { title: 'Test', text: 'Prototype tested with users.' },
        { title: 'Hand over', text: 'Ready for development.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      eyebrow: 'Design case studies',
      heading: 'Website Designs We Have Delivered',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Custom vs template',
      eyebrow: 'Compare',
      heading: 'Custom Design vs Template',
      columns: ['', 'Custom design', 'Template'],
      rows: [
        ['Brand fit', 'Built around your brand', 'Generic, shared look'],
        ['User journeys', 'Planned for your customers', 'Fixed layouts'],
        ['Conversion', 'Designed to drive enquiries', 'Depends on luck'],
        ['Cost', 'Higher upfront', 'Lower upfront'],
      ],
      note: 'Templates suit very small budgets. Custom design pays back when your website drives revenue.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      eyebrow: 'Investment',
      heading: 'How Much Does Website Design Cost?',
      intro: 'UK website design typically ranges from about £1,500 to £12,000+, with development priced separately or as a package. Your quote depends on:',
      cards: [
        { icon: 'lucide:file-text', title: 'Pages', text: 'Unique page templates.' },
        { icon: 'lucide:search', title: 'Research', text: 'Depth of UX research and testing.' },
        { icon: 'lucide:shapes', title: 'Design system', text: 'Components and guidelines.' },
        { icon: 'lucide:pen-line', title: 'Copywriting', text: 'Content written for you.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      eyebrow: 'Client reviews',
      heading: 'What Our Design Clients Say',
      reviews: [
        { name: 'Olivia R', role: 'Founder, Architecture Studio', text: 'The new design finally shows the quality of our work. Clients comment on it.' },
        { name: 'James K', role: 'Marketing Lead, B2B', text: 'Enquiries rose by 70% with the same traffic. The prototype testing made a real difference.' },
        { name: 'Fatima Z', role: 'Director, Clinic', text: 'Patients find treatments and book easily on their phones now.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      eyebrow: 'Industries we serve',
      heading: 'Website Design for Your Industry',
      items: [
        { slug: 'healthcare', text: 'Calm, trustworthy designs that drive bookings.' },
        { slug: 'finance', text: 'Clear, credible designs for regulated firms.' },
        { slug: 'b2b-marketing', text: 'Lead-focused sites for complex services.' },
        { slug: 'real-estate', text: 'Property-led designs with strong search.' },
        { slug: 'hospitality-hotels', text: 'Atmospheric designs that fill tables and rooms.' },
        { slug: 'technology-saas', text: 'Product sites that explain and convert.' },
      ],
    },
  ],
  faqs: [
    { q: 'What makes a good website design?', a: 'A good design is clear, fast, accessible and on-brand. It answers visitor questions quickly, builds trust and makes the next step obvious.' },
    { q: 'How long does website design take?', a: 'Design usually takes 3 to 6 weeks, depending on the number of pages, research and rounds of feedback.' },
    { q: 'Will we see the design before it is built?', a: 'Yes. You review wireframes, page designs and a clickable Figma prototype before any development starts.' },
    { q: 'Do you design for mobile?', a: 'Yes. We design mobile-first, then scale up to tablet and desktop.' },
    { q: 'Can you work with our existing brand?', a: 'Yes. We follow your brand guidelines, or refresh them with our branding team if needed.' },
    { q: 'Do you also build the website?', a: 'Yes. Our developers build the design on WordPress, Shopify, Laravel or Next.js.' },
    { q: 'Is the design accessible?', a: 'Yes. We design to WCAG 2.2 AA, covering colour contrast, keyboard use and screen readers.' },
  ],
  related: ['wordpress-development', 'search-engine-optimization', 'branding', 'conversion-rate-optimization', 'ecommerce-development', 'website-maintenance'],
};

export default content;
