import type { ServiceContent } from '../types';

// Entity map: WordPress development -> WordPress core, custom themes (block themes, FSE), Gutenberg
// blocks, block patterns, ACF, custom post types, plugins (custom and third-party), WooCommerce,
// WP REST API, headless WordPress, PHP 8, MySQL, caching (object cache, CDN), Core Web Vitals,
// Yoast/Rank Math, security hardening, Wordfence, 2FA, managed hosting, multisite.

const content: ServiceContent = {
  slug: 'wordpress-development',
  short: 'WordPress Development',
  metaTitle: 'WordPress Development Agency UK | Custom Themes & Plugins',
  metaDescription:
    'UK WordPress development agency building fast custom themes, Gutenberg blocks, plugins and WooCommerce stores that are secure, SEO-ready and easy to edit.',
  hero: {
    keyword: 'WordPress Development',
    title: 'WordPress Development for',
    highlight: 'Fast, Secure Websites',
    lead:
      'GTech Digital is a UK WordPress development agency that builds fast custom themes, Gutenberg blocks, plugins and WooCommerce stores that are secure, SEO-ready and easy for teams to edit.',
    motion: '/services/wordpress.webp',
    points: ['Free WordPress audit', 'No page-builder bloat', 'Your team trained to edit'],
  },
  sections: [
    { type: 'logos', id: 'clients' },
    {
      type: 'text',
      id: 'what-is-wordpress-development',
      nav: 'What is it',
      heading: 'What Is WordPress Development and How Does It Work?',
      paras: [
        'WordPress powers over 40% of the web. WordPress development means building a theme, blocks and plugins tailored to your business, rather than relying on a heavy off-the-shelf theme and dozens of plugins that slow your site down.',
      ],
      bullets: [
        'Custom themes: block themes and Gutenberg blocks built for your brand',
        'Custom plugins: features and integrations built to WordPress standards',
        'WooCommerce: online stores on the platform you already know',
      ],
    },
    {
      type: 'impact',
      id: 'impact',
      heading: 'WordPress Development Results and Key Statistics',
      text: 'The numbers behind the WordPress sites we build and rebuild for UK businesses.',
      stats: [
        { value: '120+', label: 'WordPress sites built' },
        { value: '96', label: 'Average PageSpeed score' },
        { value: '-62%', label: 'Average page weight reduction' },
        { value: '0', label: 'Known vulnerabilities at launch' },
      ],
    },
    {
      type: 'media',
      id: 'themes',
      nav: 'Custom themes',
      heading: 'Custom WordPress Theme Development Without Page Builders',
      image: '/pages/wordpress/theme.webp',
      alt: 'Custom WordPress theme code with plugins reduced, zero vulnerabilities and lower page weight',
      paras: ['We code lightweight themes from your design, with only the features you need. Less code means faster pages and fewer security risks.'],
      bullets: ['Block themes and full site editing', 'Pixel-accurate from your design', 'Custom post types and fields (ACF)', 'Coding to WordPress standards'],
    },
    {
      type: 'media',
      id: 'blocks',
      nav: 'Blocks & editing',
      heading: 'Custom Gutenberg Blocks and Editor Experience',
      image: '/pages/wordpress/plugins.webp',
      alt: 'WordPress page built from custom header, pattern, hero, content and form blocks',
      flip: true,
      tone: 'grey',
      paras: ['Your team builds pages from custom blocks and patterns that always match your brand, with no code and no page-builder clutter.'],
      bullets: ['Custom Gutenberg blocks', 'Reusable block patterns', 'Locked layouts where needed', 'Editor training and guides'],
    },
    {
      type: 'media',
      id: 'woocommerce',
      nav: 'WooCommerce',
      heading: 'WooCommerce Development and Ecommerce Integrations',
      image: '/pages/wordpress/woocommerce.webp',
      alt: 'WooCommerce sales chart with conversion rate, payment methods and shipping rules',
      paras: ['We build WooCommerce stores with fast product pages, a simple checkout and integrations for payments, shipping and stock.'],
      bullets: ['Custom product and category templates', 'Stripe, PayPal and Apple Pay', 'Royal Mail and courier shipping rules', 'Stock and accounting sync'],
    },
    {
      type: 'media',
      id: 'speed-security',
      nav: 'Speed & security',
      heading: 'WordPress Speed, Security and Hosting',
      image: '/pages/wordpress/speed.webp',
      alt: 'WordPress Core Web Vitals gauges with updates, caching, backups and malware scanning',
      flip: true,
      tone: 'grey',
      paras: ['Slow and hacked WordPress sites are usually caused by bloat and missed updates. We fix both, then keep your site fast and protected.'],
      bullets: ['Core Web Vitals optimisation', 'Caching, CDN and WebP images', 'Security hardening and 2FA', 'Updates, backups and malware scans'],
    },
    {
      type: 'cards',
      id: 'services',
      nav: "What's included",
      heading: 'What\'s Included in Our WordPress Development Services',
      cards: [
        { icon: 'lucide:search', title: 'WordPress Audit', text: 'Speed, plugins and security reviewed.' },
        { icon: 'lucide:palette', title: 'Custom Theme', text: 'Built from your design.' },
        { icon: 'lucide:blocks', title: 'Gutenberg Blocks', text: 'On-brand blocks your team can use.' },
        { icon: 'lucide:puzzle', title: 'Custom Plugins', text: 'Features without plugin bloat.' },
        { icon: 'lucide:shopping-cart', title: 'WooCommerce', text: 'Stores with simple checkout.' },
        { icon: 'lucide:webhook', title: 'Integrations', text: 'CRM, email and booking tools.' },
        { icon: 'lucide:zap', title: 'Speed & SEO', text: 'Core Web Vitals and schema.' },
        { icon: 'lucide:shield-check', title: 'Security & Care', text: 'Updates, backups and monitoring.' },
      ],
    },
    {
      type: 'steps',
      id: 'process',
      nav: 'Process',
      heading: 'Our WordPress Development Process, Step by Step',
      steps: [
        { title: 'Audit', text: 'Current site, content and goals.' },
        { title: 'Plan', text: 'Sitemap, blocks and features.' },
        { title: 'Design', text: 'Page designs approved.' },
        { title: 'Develop', text: 'Theme, blocks and plugins built.' },
        { title: 'Launch', text: 'Migration, redirects and go-live.' },
        { title: 'Support', text: 'Training, updates and care.' },
      ],
    },
    {
      type: 'cases',
      id: 'case-studies',
      nav: 'Case studies',
      heading: 'WordPress Development Case Studies and Results',
    },
    {
      type: 'table',
      id: 'compare',
      nav: 'Custom vs theme',
      heading: 'Custom Theme vs Off-the-Shelf Theme',
      columns: ['', 'Custom theme', 'Off-the-shelf theme'],
      rows: [
        ['Speed', 'Lean code, fast pages', 'Heavy, many unused features'],
        ['Design', 'Unique to your brand', 'Shared with thousands of sites'],
        ['Security', 'Fewer plugins, fewer risks', 'More plugins to patch'],
        ['Editing', 'Custom blocks made for you', 'Complex page builder'],
      ],
      note: 'A custom theme costs more upfront but usually saves money on fixes, speed work and redesigns.',
    },
    {
      type: 'cards',
      id: 'pricing',
      nav: 'Pricing',
      heading: 'How Much Does WordPress Development Cost?',
      intro: 'UK custom WordPress websites typically range from about £3,000 to £15,000+, and WooCommerce stores from about £5,000. Your quote depends on:',
      cards: [
        { icon: 'lucide:file-text', title: 'Templates', text: 'Number of unique page layouts.' },
        { icon: 'lucide:blocks', title: 'Custom blocks', text: 'How many blocks and patterns.' },
        { icon: 'lucide:puzzle', title: 'Functionality', text: 'Plugins and integrations.' },
        { icon: 'lucide:database', title: 'Migration', text: 'Content moved from your old site.' },
      ],
    },
    {
      type: 'reviews',
      id: 'reviews',
      nav: 'Reviews',
      heading: 'WordPress Development Client Reviews and Testimonials',
      reviews: [
        { name: 'Claire B', role: 'Marketing Manager, Charity', text: 'We went from 38 plugins to 9 and the site is twice as fast.' },
        { name: 'Ahmed S', role: 'Owner, Dental Practice', text: 'The custom blocks make editing pages simple for our whole team.' },
        { name: 'Paul H', role: 'Director, Consultancy', text: 'After years of hacks and fixes, our WordPress site is finally stable and secure.' },
      ],
    },
    {
      type: 'industries',
      id: 'industries',
      nav: 'Industries',
      heading: 'WordPress Development Services by Industry',
      items: [
        { slug: 'education', text: 'School and course sites staff can update.' },
        { slug: 'healthcare', text: 'Clinic sites with booking and treatment pages.' },
        { slug: 'b2b-marketing', text: 'Content-rich sites that generate leads.' },
        { slug: 'e-commerce', text: 'WooCommerce stores for growing brands.' },
        { slug: 'hospitality-hotels', text: 'Menus, rooms and bookings in one place.' },
        { slug: 'finance', text: 'Secure, compliant WordPress for advisers.' },
      ],
    },
  ],
  faqs: [
    { q: 'Is WordPress good for business websites?', a: 'Yes. WordPress is flexible, SEO-friendly and easy to edit. Built well, with a custom theme and few plugins, it is fast and secure enough for most businesses.' },
    { q: 'Do you use page builders like Elementor?', a: 'We prefer custom Gutenberg blocks because they are faster and keep your design consistent. We can still work with existing page-builder sites such as Elementor if needed, and tidy them up for speed and security.' },
    { q: 'Can you fix a slow WordPress website?', a: 'Yes. We remove unnecessary plugins, optimise images and code, add caching and a CDN, and fix Core Web Vitals issues. Most slow WordPress sites load two to four times faster after our speed work.' },
    { q: 'Can you fix a hacked WordPress site?', a: 'Yes. We clean the malware, close the vulnerability, restore from clean backups where needed and harden the site to stop it happening again. WordPress security is part of every build and every care plan we run.' },
    { q: 'Can you migrate our site to WordPress?', a: 'Yes. We move pages, posts, images and SEO metadata and set up 301 redirects so you keep your rankings. We test the new site on a staging copy and only switch over once everything is checked.' },
    { q: 'Do you offer WordPress maintenance?', a: 'Yes. Our care plans cover updates, backups, security monitoring, uptime checks and small changes each month, with a fixed fee so there are no surprise bills when a plugin or PHP update goes wrong.' },
    { q: 'Do we own the theme and code?', a: 'Yes. Everything we build for you is yours, including the theme, custom blocks and code. We keep it in your own version control with notes, so any competent WordPress developer can take it on.' },
    { q: 'Which PHP version should my WordPress site use?', a: 'Use a currently supported PHP version, which is PHP 8.2 or newer for most sites in 2026. Older PHP versions no longer get security fixes and run slower, so we test your theme and plugins and upgrade PHP safely as part of maintenance.' },
  ],
  related: ['website-design', 'website-maintenance', 'ecommerce-development', 'cms-development', 'php-development', 'search-engine-optimization'],
};

export default content;
