// Extracts only the icons the site uses from the installed Iconify packs
// into lib/icon-data.ts, so no full icon set ships to the browser.
// Run: npm run icons   (after editing the `used` list below or lib/icons.ts)
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const packs = {
  lucide: JSON.parse(readFileSync(require.resolve('@iconify-json/lucide/icons.json'), 'utf8')),
  'simple-icons': JSON.parse(readFileSync(require.resolve('@iconify-json/simple-icons/icons.json'), 'utf8')),
};

const src = readFileSync(new URL('../lib/icons.ts', import.meta.url), 'utf8');
const names = [...new Set([...src.matchAll(/'((?:lucide|simple-icons):[a-z0-9-]+)'/g)].map((m) => m[1]))].sort();

const out = {};
const missing = [];
for (const full of names) {
  const [prefix, name] = full.split(':');
  const pack = packs[prefix];
  const icon = pack.icons[name] ?? (pack.aliases?.[name] && pack.icons[pack.aliases[name].parent]);
  if (!icon) { missing.push(full); continue; }
  out[full] = { body: icon.body, w: icon.width ?? pack.width ?? 24, h: icon.height ?? pack.height ?? 24 };
}
if (missing.length) {
  console.error('Missing icons:', missing.join(', '));
  process.exit(1);
}
writeFileSync(
  new URL('../lib/icon-data.ts', import.meta.url),
  `// Generated by scripts/build-icons.mjs. Do not edit.\nexport const iconData: Record<string, { body: string; w: number; h: number }> = ${JSON.stringify(out, null, 2)};\n`,
);
console.log(`Wrote ${names.length} icons`);
